import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(['https://buyshub.me','https://www.buyshub.me','https://beaustwrt248-netizen.github.io']);
const clean=(v:unknown,n=1000)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,n);
const uuid=(v:unknown)=>{const s=clean(v,80);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:''};
function headers(req:Request){const o=req.headers.get('Origin')||'';return {'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://buyshub.me','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'};}
async function auth(req:Request){if(!SUPABASE_URL||!SERVICE_ROLE)return{error:'Nova action service unavailable',status:503} as const;const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return{error:'Authentication required',status:401} as const;const{data:{user},error}=await admin.auth.getUser(token);if(error||!user)return{error:'Invalid session',status:401} as const;const{data:p,error:pe}=await admin.from('profiles').select('role,is_enabled').eq('id',user.id).maybeSingle();if(pe)throw pe;if(!p?.is_enabled||p.role!=='admin')return{error:'Admin access required',status:403} as const;return{user} as const;}
async function audit(userId:string,action:string,targetType:string,targetId:string|null,details:any){const{data,error}=await admin.from('admin_audit_log').insert({actor_user_id:userId,action,target_type:targetType,target_id:targetId,details:{source:'nova-actions',...details}}).select('id,created_at').single();if(error)throw error;return data;}
async function device(id:number){const{data,error}=await admin.from('device_catalog').select('id,active,brand,model_name,model_number,release_year,storage_options,image_reference_url').eq('id',id).maybeSingle();if(error)throw error;if(!data?.active)throw new Error('Active catalogue device not found');return data;}
async function ticket(id:string){const{data,error}=await admin.from('support_tickets').select('id,status,priority,category,subject,description,app_version,device_model,android_version').eq('id',id).maybeSingle();if(error)throw error;if(!data)throw new Error('Support ticket not found');return data;}
Deno.serve(async(req:Request)=>{const h=headers(req),reply=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:h});if(req.method==='OPTIONS')return new Response('ok',{headers:h});if(req.method!=='POST')return reply({error:'POST required'},405);try{const a=await auth(req);if('error'in a)return reply({error:a.error},a.status);let body:any={};try{body=await req.json()}catch{return reply({error:'Invalid JSON request'},400)}const action=clean(body.action,60).toLowerCase();
if(action==='catalogue_queue'){const deviceId=Number(body.device_id);if(!Number.isSafeInteger(deviceId)||deviceId<=0)return reply({error:'Valid device_id required'},400);await device(deviceId);const priority=Math.min(100,Math.max(1,Number(body.priority)||50));const reason=clean(body.reason,220)||'manual_admin_review';const{data,error}=await admin.from('nova_catalog_audit_queue').insert({device_id:deviceId,priority,status:'pending',reason,next_attempt_at:new Date().toISOString()}).select('id,device_id,priority,status,reason,created_at').single();if(error)throw error;await audit(a.user.id,'nova.catalogue.queue','device_catalog',String(deviceId),{queue_id:data.id,priority,reason});return reply({ok:true,action,item:data},201)}
if(action==='catalogue_finding'){const deviceId=Number(body.device_id);if(!Number.isSafeInteger(deviceId)||deviceId<=0)return reply({error:'Valid device_id required'},400);const d=await device(deviceId);const field=clean(body.field_name,80);const allowed=new Set(['model_number','release_year','storage_options','image_reference_url','model_name','family','market_region']);if(!allowed.has(field))return reply({error:'Field is not eligible for Nova proposal'},400);const sourceUrl=clean(body.source_url,1000),sourceName=clean(body.source_name,180);if(!/^https:\/\//i.test(sourceUrl)||!sourceName)return reply({error:'HTTPS source_url and source_name required'},400);const confidence=Math.max(0,Math.min(1,Number(body.confidence)||0));if(confidence<0.5)return reply({error:'Finding confidence must be at least 0.5'},400);const severity=['low','medium','high'].includes(clean(body.severity,20).toLowerCase())?clean(body.severity,20).toLowerCase():'medium';const proposed=body.proposed_patch&&typeof body.proposed_patch==='object'&&!Array.isArray(body.proposed_patch)?body.proposed_patch:{};if(!Object.prototype.hasOwnProperty.call(proposed,field))return reply({error:'proposed_patch must contain the selected field'},400);const current=(d as any)[field]??null;const{data,error}=await admin.from('nova_catalog_audit_findings').insert({device_id:deviceId,field_name:field,current_value:current,observed_value:body.observed_value??proposed[field],severity,confidence,source_url:sourceUrl,source_name:sourceName,source_region:clean(body.source_region,80)||null,source_tier:Math.min(5,Math.max(1,Number(body.source_tier)||5)),evidence_excerpt:clean(body.evidence_excerpt,1000)||null,proposed_patch:proposed,status:'open',requires_approval:true}).select('id,device_id,field_name,severity,confidence,status,requires_approval,detected_at').single();if(error)throw error;await audit(a.user.id,'nova.catalogue.finding_proposed','device_catalog',String(deviceId),{finding_id:data.id,field,confidence,source_url:sourceUrl,requires_approval:true});return reply({ok:true,action,item:data},201)}
if(action==='support_draft'){const ticketId=uuid(body.ticket_id);if(!ticketId)return reply({error:'Valid ticket_id required'},400);const t=await ticket(ticketId);const draft=clean(body.draft_body,4000);if(draft.length<20)return reply({error:'Draft body is too short'},400);const terminal=new Set(['resolved','closed','cancelled','dismissed']);if(terminal.has(String(t.status||'').toLowerCase()))return reply({error:'Drafts are limited to active support tickets'},409);const noteBody=`[Nova draft — not sent]\n${draft}`;const{data:note,error}=await admin.from('support_ticket_internal_notes').insert({ticket_id:ticketId,author_user_id:a.user.id,body:noteBody}).select('id,ticket_id,created_at').single();if(error)throw error;const{error:eventError}=await admin.from('support_ticket_events').insert({ticket_id:ticketId,actor_user_id:a.user.id,event_type:'nova_draft_created',details:{note_id:note.id,not_sent:true,source:'nova-actions'}});if(eventError)throw eventError;await audit(a.user.id,'nova.support.draft','support_ticket',ticketId,{note_id:note.id,not_sent:true});return reply({ok:true,action,item:{...note,not_sent:true}},201)}
if(action==='support_triage_proposal'){const ticketId=uuid(body.ticket_id);if(!ticketId)return reply({error:'Valid ticket_id required'},400);await ticket(ticketId);const summary=clean(body.summary,1800),area=clean(body.probable_area,240);const confidence=Math.max(0,Math.min(1,Number(body.confidence)||0));if(!summary||confidence<0.3)return reply({error:'Triage summary and confidence >= 0.3 required'},400);const files=Array.isArray(body.candidate_files)?body.candidate_files.map((x:any)=>clean(x,240)).filter(Boolean).slice(0,20):[];const tests=Array.isArray(body.test_plan)?body.test_plan.map((x:any)=>clean(x,300)).filter(Boolean).slice(0,20):[];const details={summary,probable_area:area||null,candidate_files:files,test_plan:tests,confidence,proposal_only:true,requires_human_merge:true};const{data:event,error}=await admin.from('support_ticket_events').insert({ticket_id:ticketId,actor_user_id:a.user.id,event_type:'nova_triage_proposal',details}).select('id,ticket_id,event_type,created_at').single();if(error)throw error;await audit(a.user.id,'nova.support.triage_proposal','support_ticket',ticketId,{event_id:event.id,confidence,candidate_files:files,proposal_only:true});return reply({ok:true,action,item:event,details},201)}
if(action==='engineering_proposal'){const title=clean(body.title,240),summary=clean(body.summary,3000);if(!title||!summary)return reply({error:'Proposal title and summary required'},400);const confidence=Math.max(0,Math.min(1,Number(body.confidence)||0));const files=Array.isArray(body.candidate_files)?body.candidate_files.map((x:any)=>clean(x,240)).filter(Boolean).slice(0,30):[];const tests=Array.isArray(body.test_plan)?body.test_plan.map((x:any)=>clean(x,300)).filter(Boolean).slice(0,30):[];const sourceTicket=uuid(body.support_ticket_id)||null;const rec=await audit(a.user.id,'nova.engineering.proposal','repository','beaustwrt248-netizen/Buys-Mock',{title,summary,confidence,candidate_files:files,test_plan:tests,support_ticket_id:sourceTicket,proposal_only:true,merge:false,deploy:false});return reply({ok:true,action,item:{id:rec.id,created_at:rec.created_at,title,proposal_only:true}},201)}
const forbidden=['pricing_approve','pricing_write','guardian_approve','guardian_repair','guardian_decide','release','deploy','ota','role_change','user_change','delete','catalogue_apply','support_send','support_message_send','github_merge','github_release'];if(forbidden.some(x=>action===x||action.startsWith(x+'.')))return reply({error:'This action remains human-gated or prohibited for Nova execution'},403);
return reply({error:'Unsupported Nova action'},400);}catch(error){const m=error instanceof Error?error.message:clean(error,500)||'Nova action error';console.error(`[nova-actions] ${m}`);return new Response(JSON.stringify({error:m}),{status:500,headers:headers(req)});}});