(()=>{
const $=id=>document.getElementById(id);
function removeMetric(id){const el=$(id);const box=el?.closest?.('.stats>div');if(box)box.remove()}
function removeHomeTile(page){const home=$('home');if(!home)return;home.querySelectorAll('.tiles button').forEach(b=>{const oc=b.getAttribute('onclick')||'';if(oc.includes(`show('${page}')`)||oc.includes(`show(\"${page}\")`))b.remove()})}
function addMore(){const sec=$('settings');if(!sec||$('moreManagement'))return;const first=sec.querySelector('.card');const card=document.createElement('div');card.id='moreManagement';card.className='card';card.innerHTML=`<h2>📂 Management</h2><p class="muted">Stock, saved deals and sales tools.</p><div class="stats"><div><small>STOCK UNITS</small><b id="moreStockUnits">0</b></div></div><div class="tiles" style="margin-top:10px"><button id="moreInventory">📦<b>Inventory</b><small>View and manage stock</small></button><button id="moreDeals">⭐<b>Saved Deals</b><small>Review saved valuations</small></button><button id="moreSales">📈<b>Sales</b><small>Sales history and realised profit</small></button></div>`;if(first)first.insertAdjacentElement('afterend',card);else sec.appendChild(card);$('moreInventory').onclick=()=>window.show?.('inventory');$('moreDeals').onclick=()=>window.show?.('deals');$('moreSales').onclick=()=>window.show?.('sales')}
function syncUnits(){const src=$('dUnits'),dst=$('moreStockUnits');if(dst)dst.textContent=src?.textContent||'0'}
function ensureDesktopNav(){const nav=document.querySelector('nav');if(!nav||nav.querySelector('[data-page="desktop"]'))return;const laptop=nav.querySelector('[data-page="laptop"]');const b=document.createElement('button');b.dataset.page='desktop';b.innerHTML='🖥️<small>Desktop</small>';b.onclick=()=>window.show?.('desktop');if(laptop)laptop.insertAdjacentElement('afterend',b);else nav.appendChild(b)}
function cleanNav(){document.querySelectorAll('nav button').forEach(b=>{const p=b.dataset.page;if(p==='deals'||p==='inventory')b.remove()});ensureDesktopNav();const nav=document.querySelector('nav');if(nav){const count=nav.children.length||5;nav.style.gridTemplateColumns=`repeat(${count},1fr)`}}
function ensureStatusTiles(){const home=$('home');if(!home)return;let api=$('apiStatus');let stats=api?.closest('.stats');if(!stats){stats=document.createElement('div');stats.className='stats';const hero=home.querySelector('.hero');if(hero)hero.insertAdjacentElement('afterend',stats);else home.prepend(stats)}if(api&&!api.closest('.stats'))stats.appendChild(api.closest('div')||api);if(!$('onlineStatus')){const d=document.createElement('div');d.innerHTML='<small>ONLINE STATUS</small><b id="onlineStatus" class="good">ONLINE</b>';stats.appendChild(d)}updateOnline();stats.style.gridTemplateColumns='repeat(2,1fr)'}
function updateOnline(){const el=$('onlineStatus');if(!el)return;const on=navigator.onLine!==false;el.textContent=on?'ONLINE':'OFFLINE';el.className=on?'good':'bad'}
function cleanDashboard(){['dUnits','dCost','dSales','dProfit','dDeals','dRealProfit','dSaleCount'].forEach(removeMetric);['inventory','sales','deals'].forEach(removeHomeTile);document.querySelectorAll('#home .stats').forEach(s=>{if(!s.children.length)s.remove()});ensureStatusTiles()}
function boot(){addMore();syncUnits();cleanDashboard();cleanNav();window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);setInterval(syncUnits,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,360));else setTimeout(boot,360);
})();