(()=>{
'use strict';
const SB='https://ghdhairijqjqivqriigi.supabase.co',KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt',STORE='morley_web_auth';
const $=(s,r=document)=>r.querySelector(s);let client=null,channel=null,activeTicket=null,rows=[];
function session(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(v){return String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function loadSdk(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve();const existing=document.querySelector('script[data-guardian-supabase]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.dataset.guardianSupabase='1';s.onload=resolve;s.onerror=()=>reject(new Error('Guardian live service could not load.'));document.head.appendChild(s)})}
async function getClient(){if(client)return client;await loadSdk();const s=session();if(!s?.access_token)throw new Error('Sign in to view Guardian activity.');client=window.supabase.createClient(SB,KEY,{auth:{persistSession:false,autoRefreshToken:false}});client.realtime.setAuth(s.access_token);return client}
function icon(status){return status==='success'?'✓':status==='error'?'!':status==='warning'?'△':status==='waiting'?'◷':status==='stopped'?'■':'●'}
function timeline(list){if(!list.length)return '<div style="padding:18px 0;color:#9db0c9">No Guardian activity is visible for this account yet.</div>';return list.map(x=>`<div style="display:grid;grid-template-columns:28px 1fr;gap:10px;padding:12px 0;border-bottom:1px solid rgba(142,166,196,.13)"><div style="font-weight:900;color:${x.status==='error'?'#ff8a9b':x.status==='success'?'#57e389':x.status==='waiting'?'#ffd166':'#66b3ff'}">${icon(x.status)}</div><div><div style="display:flex;justify-content:space-between;gap:8px;align-items:flex-start"><b style="color:#fff">${esc(x.summary)}</b><span style="font-size:10px;color:#7890ad;white-space:nowrap">${new Date(x.created_at).toLocaleTimeString()}</span></div><div style="margin-top:4px;color:#8ea6c4;font-size:11px;text-transform:uppercase;font-weight:800">${esc(label(x.phase))}${x.progress!=null?` • ${Number(x.progress)}%`:''}</div>${x.detail?`<div style="margin-top:6px;color:#aebfd3;font-size:12px;line-height:1.45">${esc(x.detail)}</div>`:''}</div></div>`).join('')}
function dialog(){let d=$('#morleyGuardianLive');if(!d){d=document.createElement('div');d.id='morleyGuardianLive';d.className='morley-menu-dialog';document.body.appendChild(d)}return d}
function render(){const d=dialog();const visible=activeTicket?rows.filter(x=>x.ticket_id===activeTicket):rows;d.innerHTML=`<div class="morley-menu-dialog-card" style="max-height:84vh;overflow:auto"><button class="morley-menu-dialog-close">×</button><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><div><h2 style="margin-bottom:4px">Guardian Activity</h2><div style="color:#8ea6c4;font-size:12px">Live, user-safe progress from Guardian.</div></div><span style="font-size:10px;font-weight:900;color:#57e389">● LIVE</span></div>${activeTicket?`<button id="guardianShowAll" style="margin-top:12px;border:1px solid rgba(47,124,255,.35);background:#0a1b33;color:#fff;border-radius:10px;padding:8px 10px">Show all my Guardian activity</button>`:''}<div id="guardianLiveTimeline" style="margin-top:8px">${timeline(visible)}</div></div>`;d.classList.add('open');$('.morley-menu-dialog-close',d).onclick=()=>d.classList.remove('open');d.onclick=e=>{if(e.target===d)d.classList.remove('open')};$('#guardianShowAll',d)?.addEventListener('click',()=>{activeTicket=null;render()})}
async function refresh(){const s=session();if(!s?.access_token)throw new Error('Sign in to view Guardian activity.');await getClient();const url=`${SB}/rest/v1/guardian_activity?select=id,incident_id,ticket_id,phase,status,summary,detail,progress,created_at&order=created_at.desc&limit=250`;const r=await fetch(url,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`},cache:'no-store'});let data=[];try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.message||data?.error||`Guardian activity request failed (${r.status})`);rows=(Array.isArray(data)?data:[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));if($('#morleyGuardianLive')?.classList.contains('open'))render()}
async function subscribe(){const c=await getClient();if(channel)return;channel=c.channel('morley-guardian-user-activity').on('postgres_changes',{event:'INSERT',schema:'public',table:'guardian_activity'},payload=>{rows.push(payload.new);rows.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));if($('#morleyGuardianLive')?.classList.contains('open'))render()}).subscribe()}
async function open(ticketId=null){activeTicket=ticketId||null;try{await refresh();await subscribe();render()}catch(e){const d=dialog();d.innerHTML=`<div class="morley-menu-dialog-card"><button class="morley-menu-dialog-close">×</button><h2>Guardian Activity</h2><p style="color:#ff9dac">${esc(e.message||e)}</p></div>`;d.classList.add('open');$('.morley-menu-dialog-close',d).onclick=()=>d.classList.remove('open')}}
function addRow(){const root=$('#morleyRelevantMore');if(!root||$('#morleyGuardianActivityRow'))return;const report=[...root.querySelectorAll('.morley-menu-row')].find(b=>(b.textContent||'').includes('Report an Issue'));if(!report)return;const row=document.createElement('button');row.id='morleyGuardianActivityRow';row.className='morley-menu-row';row.type='button';row.innerHTML='<span class="morley-menu-icon">◉</span><span class="morley-menu-copy"><b>Guardian Activity</b><small>Watch Guardian assess and work through your reported issues in real time.</small></span><span class="morley-menu-chevron">›</span>';row.onclick=()=>open();report.parentElement.insertBefore(row,report)}
function init(){addRow();new MutationObserver(addRow).observe(document.body,{childList:true,subtree:true});const s=session();if(s?.access_token)getClient().then(()=>subscribe()).catch(()=>{})}
window.MorleyGuardianLive={open,watchTicket:(id)=>open(id),refresh};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();