(()=>{
'use strict';
const nativeFetch=window.fetch.bind(window);
const norm=s=>String(s||'').toLowerCase().replace(/\b(refurbished|refurb|brand\s+new|new|used|preowned|pre-owned)\b/g,' ').replace(/[^a-z0-9.]+/g,' ').replace(/\s+/g,' ').trim();
const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
const pct=(a,p)=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?s[l]:s[l]+(s[h]-s[l])*(i-l)};
const brands=['apple','lenovo','dell','hp','acer','asus','msi','alienware','gigabyte','razer','microsoft','samsung','lg','framework'];
const families=['macbook air','macbook pro','macbook','thinkpad','ideapad','thinkbook','yoga','legion','loq','latitude','inspiron','xps','precision','vostro','alienware','elitebook','probook','pavilion','envy','spectre','omen','victus','zbook','aspire','swift','travelmate','chromebook','predator','nitro','zenbook','vivobook','expertbook','proart','rog zephyrus','zephyrus','tuf gaming','tuf','modern','prestige','stealth','katana','raider','creator','vector','blade','aero','aorus','surface laptop','surface book','galaxy book','gram','framework laptop'];
const ACCESSORY=/\b(charger|adapter|power\s*supply|screen|display\s*assembly|lcd|keyboard|keycap|battery|shell|case|cover|sleeve|bag|motherboard|logic\s*board|palmrest|trackpad|touchpad|hinge|fan|heatsink|parts?|spares?|repair|box\s*only|dock|docking\s*station|cable)\b/i;
const WHOLE_DEVICE=/\b(laptop|notebook|macbook|thinkpad|ideapad|thinkbook|latitude|inspiron|xps|elitebook|probook|pavilion|envy|spectre|omen|victus|zbook|aspire|swift|predator|nitro|zenbook|vivobook|rog|zephyrus|tuf|raider|katana|blade|surface\s+laptop|surface\s+book|galaxy\s+book|gram|framework)\b/i;
function cpuMaker(x){if(/\b(apple\s+)?m[1-5](?:\s+(?:pro|max|ultra))?\b/.test(x))return'apple';if(/\b(?:intel|core\s+ultra|core\s+i[3579]|i[3579][ -]?\d{4,5})\b/.test(x))return'intel';if(/\b(?:amd|ryzen)\b/.test(x))return'amd';if(/\bsnapdragon\b/.test(x))return'qualcomm';return''}
function cpuToken(x){return x.match(/\bm[1-5](?:\s+(?:pro|max|ultra))?\b/)?.[0]||x.match(/\bcore\s+ultra\s+[3579]\s+\d{3,4}[a-z]{0,3}\b/)?.[0]||x.match(/\bi[3579][ -]?\d{4,5}[a-z]{0,3}\b/)?.[0]||x.match(/\bryzen(?:\s+ai)?\s+[3579]\s+[a-z0-9]+\b/)?.[0]||x.match(/\bsnapdragon\s+x(?:2)?(?:\s+(?:plus|elite))?\b/)?.[0]||''}
function capacity(x){return[...x.matchAll(/\b(4|8|12|16|18|24|32|36|48|64|96|128)\s*gb\b/g)].map(m=>Number(m[1]))}
function storageCap(x){const out=[];for(const m of x.matchAll(/\b(128|256|512)\s*gb\b/g))out.push(Number(m[1]));for(const m of x.matchAll(/\b(1|2|4|8)\s*tb\b/g))out.push(Number(m[1])*1024);return out}
function extract(q){const x=norm(q),brand=brands.find(b=>new RegExp(`\\b${b}\\b`).test(x))||'',family=families.find(f=>x.includes(f))||'',gen=x.match(/\bgen\s*(\d+)\b/)?.[1]||'',year=x.match(/\b(20(?:1\d|2\d))\b/)?.[1]||'',cpu=cpuToken(x),maker=cpuMaker(x),gpu=x.match(/\b((?:rtx|gtx|rx|arc)\s*\d{3,4}(?:\s*(?:ti|super|xt|xtx|gre))?)\b/)?.[1]||'',caps=capacity(x),stores=storageCap(x),ram=caps.length?String(caps[0]):'',storage=stores.length?stores[0]:'',size=x.match(/\b(11|12|13|14|15|16|17|18)(?:\.\d+)?(?:\s*inch|\s*in)?\b/)?.[0]||'',modelTokens=x.split(' ').filter(z=>z.length>=3&&(/[a-z]/.test(z)&&/\d/.test(z))&&!/^(?:rtx|gtx|rx|arc)?\d+$/.test(z)&&!/^\d+(?:gb|tb)?$/.test(z)&&!cpu.includes(z));return{x,brand,family,gen,year,cpu,maker,gpu,ram,storage,size,modelTokens}}
function listingCaps(t){const x=norm(t);return{ram:capacity(x),storage:storageCap(x),maker:cpuMaker(x),cpu:cpuToken(x),year:x.match(/\b(20(?:1\d|2\d))\b/)?.[1]||'',gen:x.match(/\bgen\s*(\d+)\b/)?.[1]||'',gpu:x.match(/\b((?:rtx|gtx|rx|arc)\s*\d{3,4}(?:\s*(?:ti|super|xt|xtx|gre))?)\b/)?.[1]||''}}
function score(query,title){const q=extract(query),t=norm(title),lc=listingCaps(t);let s=8,reasons=[],warnings=[],hardReject=false;
if(ACCESSORY.test(title))return{score:0,label:'Rejected',reasons:[],warnings:['accessory / part listing'],hardReject:true};
if(q.brand){if(new RegExp(`\\b${q.brand}\\b`).test(t)||q.brand==='apple'&&/\bmacbook\b/.test(t)){s+=18;reasons.push('Brand')}else{s-=45;warnings.push('wrong brand');hardReject=true}}
if(q.family){const words=q.family.split(' ').filter(x=>x.length>2);if(t.includes(q.family)){s+=30;reasons.push('Exact family')}else if(words.every(x=>new RegExp(`\\b${x}\\b`).test(t))){s+=26;reasons.push('Exact family')}else{s-=35;warnings.push('wrong family');hardReject=true}}
if(q.modelTokens.length){const hits=q.modelTokens.filter(z=>new RegExp(`\\b${z.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`).test(t));if(hits.length){s+=Math.min(24,hits.length*12);reasons.push(hits.length===q.modelTokens.length?'Exact model':'Model token')}else{s-=12;warnings.push('model code absent')}}
if(q.gen){if(lc.gen===q.gen){s+=10;reasons.push('Same generation')}else if(lc.gen){s-=35;warnings.push('different generation');hardReject=true}}
if(q.year){if(lc.year===q.year){s+=7;reasons.push('Same year')}else if(lc.year){s-=24;warnings.push('different year');hardReject=true}}
if(q.maker&&lc.maker){if(q.maker===lc.maker){s+=5;reasons.push('CPU maker')}else{s-=50;warnings.push('different CPU platform');hardReject=true}}
if(q.cpu){if(t.includes(norm(q.cpu))){s+=16;reasons.push('Exact CPU')}else if(lc.cpu){s-=35;warnings.push('different CPU');hardReject=true}}
if(q.gpu){const g=norm(q.gpu);if(t.includes(g)){s+=16;reasons.push('Exact GPU')}else if(lc.gpu){s-=28;warnings.push('different GPU');hardReject=true}}
if(q.ram){const qr=Number(q.ram);if(lc.ram.includes(qr)){s+=8;reasons.push('RAM')}else if(lc.ram.length){s-=30;warnings.push('different RAM');hardReject=true}}
if(q.storage){const qs=Number(q.storage);if(lc.storage.includes(qs)){s+=8;reasons.push('Storage')}else if(lc.storage.length){s-=30;warnings.push('different storage');hardReject=true}}
if(q.size){const num=Number(q.size.match(/\d+(?:\.\d+)?/)?.[0]||0),tm=Number(t.match(/\b(11|12|13|14|15|16|17|18)(?:\.\d+)?\s*(?:inch|in)\b/)?.[0]?.match(/\d+(?:\.\d+)?/)?.[0]||0);if(num&&tm){if(Math.abs(num-tm)<=.6){s+=4;reasons.push('Screen size')}else{s-=20;warnings.push('different screen size');hardReject=true}}}
if(WHOLE_DEVICE.test(t)){s+=8;reasons.push('Complete device')}else{s-=10;warnings.push('whole-device wording absent')}
s=Math.max(0,Math.min(100,s));if(hardReject)s=Math.min(s,35);const label=hardReject?'Rejected':s>=88?'Excellent match':s>=72?'Strong match':s>=55?'Good match':s>=40?'Broadened match':'Weak match';return{score:s,label,reasons:[...new Set(reasons)].slice(0,6),warnings:[...new Set(warnings)].slice(0,4),hardReject}}
function price(x){return Number(x?.deliveredPrice||x?.price)||0}
function apply(d,q){const isOEM=!!d?.parsed,device=d?.mode==='device'||isOEM||/\b(laptop|notebook|macbook|thinkpad|latitude|xps|elitebook|surface laptop|galaxy book|blade|zephyrus|tuf|nitro|predator)\b/i.test(q);if(!d||!device)return d;for(const key of ['ebay','google','webRetail']){const src=d[key];if(!src?.items)continue;src.items=src.items.map(x=>({...x,matchQuality:score(q,`${x.title||''} ${x.description||x.snippet||''}`)})).sort((a,b)=>Number(a.matchQuality.hardReject)-Number(b.matchQuality.hardReject)||b.matchQuality.score-a.matchQuality.score||price(a)-price(b));const eligible=src.items.filter(x=>!x.matchQuality.hardReject&&x.matchQuality.score>=55&&price(x)>0);src.rejectedListings=src.items.length-eligible.length;src.qualityEligible=eligible.length;src.items=eligible;src.analysedListings=eligible.length;const ps=eligible.map(price).filter(Boolean);src.pricing=src.pricing||{};if(key==='ebay'&&ps.length){src.pricing.typicalUsed=median(ps);src.pricing.p25=pct(ps,.25);src.pricing.p75=pct(ps,.75);src.pricing.lowest=Math.min(...ps);src.pricing.highest=Math.max(...ps);src.pricing.matchClass=eligible.some(x=>x.matchQuality.score>=88)?'exact_or_strong':'family_match'}if((key==='google'||key==='webRetail')&&ps.length){src.pricing.typicalNew=median(ps);src.pricing.competitiveLow=pct(ps,.2);src.pricing.competitiveHigh=pct(ps,.8);src.pricing.matchClass=eligible.some(x=>x.matchQuality.score>=88)?'exact_or_strong':'family_match'}}d.matchQualityApplied=true;d.matchQuery=q;return d}
window.fetch=async function(input,init){const r=await nativeFetch(input,init),url=typeof input==='string'?input:input?.url||'';if(!/\/functions\/v1\/(?:ebay-search|oem-search|market-search-v2)/.test(url))return r;try{let q='',body={};if(init?.body){body=JSON.parse(init.body);q=[body.query,body.model,body.search,body.specs,body.cpu,body.ram,body.storage].filter(Boolean).join(' ')}const d=await r.clone().json();if(!d?.success)return r;const domLaptop=String(body?.mode||'').toLowerCase()==='device'?[document.getElementById('lapModel')?.value,document.getElementById('lapSpecs')?.value].filter(Boolean).join(' '):'';const fullQuery=[q,domLaptop,d.query,d.inputQuery,d?.parsed?.brand,d?.parsed?.model,d?.parsed?.cpu,d?.parsed?.gpu,d?.parsed?.ram,d?.parsed?.storage].filter(Boolean).join(' ');const out=apply(d,fullQuery);return new Response(JSON.stringify(out),{status:r.status,statusText:r.statusText,headers:r.headers})}catch{return r}}
function currentQuery(type){if(type==='lap')return[document.getElementById('lapModel')?.value,document.getElementById('lapSpecs')?.value].filter(Boolean).join(' ');return[document.getElementById('deskSpecs')?.value,...[...document.querySelectorAll('#parts .pq')].map(x=>x.value)].filter(Boolean).join(' ')}
function listingTitle(el){const direct=[...el.children].find(c=>c.tagName==='DIV'&&!c.querySelector('a')&&!c.classList.contains('matchQualityBadge')&&!/^\s*\$/.test(c.textContent||'')&&(c.textContent||'').trim().length>8);if(direct)return direct.textContent.trim();const candidates=[...el.querySelectorAll('div')].filter(c=>!c.querySelector('a')&&!c.classList.contains('matchQualityBadge')).map(c=>(c.textContent||'').trim()).filter(t=>t.length>8&&!/^\$/.test(t)&&!/^open$/i.test(t));return candidates.sort((a,b)=>b.length-a.length)[0]||''}
function badge(el,q){if(!el)return;el.querySelector('.matchQualityBadge')?.remove();const title=listingTitle(el);if(!title)return;const m=score(q,title),b=document.createElement('div');b.className='matchQualityBadge';b.style.cssText='margin-top:7px;display:inline-block;padding:5px 8px;border:1px solid #565656;border-radius:999px;font-size:11px;font-weight:800;color:'+(m.hardReject?'#ff8a98':m.score>=72?'#72e79b':m.score>=55?'#ffe06a':'#bbb')+';background:#181818';b.textContent=`${m.score}% · ${m.label}${m.reasons.length?' · '+m.reasons.join(' + '):''}${m.warnings.length?' · '+m.warnings.join(', '):''}`;el.appendChild(b)}
function annotate(){const lq=currentQuery('lap');if(lq)document.querySelectorAll('#lapEbay .item,#lapEbay .result,#lapGoogle .item,#lapGoogle .result').forEach(el=>badge(el,lq));const dq=currentQuery('desk');if(dq)document.querySelectorAll('#deskEvidence>div>div').forEach(el=>{if((el.textContent||'').includes('$')&&el.querySelector('a'))badge(el,dq)})}
let timer;const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(annotate,80)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mo.observe(document.body,{childList:true,subtree:true});annotate()});else{mo.observe(document.body,{childList:true,subtree:true});annotate()}
window.MorleyMatchQuality={version:2,extract,score};
})();
