(()=>{
const nativeFetch=window.fetch.bind(window);
const norm=s=>String(s||'').toLowerCase().replace(/\b(gaming\s+desktop|gaming\s+pc|desktop\s+pc|computer|refurbished|refurb|brand\s+new|new)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
const pct=(a,p)=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?s[l]:s[l]+(s[h]-s[l])*(i-l)};
const brands=['apple','lenovo','dell','hp','acer','asus','msi','alienware','gigabyte','razer','microsoft'];
const families=['macbook air','macbook pro','macbook neo','thinkcentre','thinkstation','thinkpad','optiplex','precision','elitedesk','prodesk','legion','loq','omen','victus','predator','nitro','tuf','rog','zephyrus','vivobook','zenbook','inspiron','latitude','xps','mpg trident as','trident as','trident','aegis','infinite','codex','raider','katana','stealth','vector','surface laptop'];
function extract(q){const x=norm(q),brand=brands.find(b=>new RegExp(`\\b${b}\\b`).test(x))||'',family=families.find(f=>x.includes(f))||'',gen=x.match(/\bgen\s*(\d+)\b/)?.[1]||'',year=x.match(/\b(20(?:1\d|2\d))\b/)?.[1]||'',cpu=(x.match(/\b(?:core\s+ultra\s+[3579]\s+)?(?:i[3579][ -]?)?(\d{3,5}[a-z]{0,3})\b/)?.[1]||x.match(/\bryzen\s+[3579]\s+(\d{4,5}[a-z0-9]*)\b/)?.[1]||''),gpu=x.match(/\b((?:rtx|gtx|rx|arc)\s*\d{3,4}(?:\s*(?:ti|super|xt|xtx|gre))?)\b/)?.[1]||'',ram=x.match(/\b(8|12|16|18|24|32|36|48|64|96|128)\s*gb\b/)?.[1]||'',storage=x.match(/\b(128|256|512)\s*gb\b|\b(1|2|4|8)\s*tb\b/)?.[0]||'',size=x.match(/\b(11|12|13|14|15|16|17|18)(?:\s*inch|\s*in)?\b/)?.[1]||'',modelTokens=x.split(' ').filter(z=>z.length>=3&&(/[a-z]/.test(z)&&/\d/.test(z))&&!/^(?:rtx|gtx|rx|arc)?\d+$/.test(z)&&z!==cpu);return{x,brand,family,gen,year,cpu,gpu,ram,storage,size,modelTokens}}
function score(query,title){const q=extract(query),t=norm(title);let s=8,reasons=[],pen=[];
if(q.brand){if(new RegExp(`\\b${q.brand}\\b`).test(t)){s+=18;reasons.push('Brand')}else{s-=24;pen.push('brand missing')}}
if(q.family){if(t.includes(q.family)){s+=30;reasons.push('Exact family')}else if(q.family.split(' ').filter(x=>x.length>2).every(x=>new RegExp(`\\b${x}\\b`).test(t))){s+=26;reasons.push('Exact family')}else if(q.family.split(' ').some(x=>x.length>3&&new RegExp(`\\b${x}\\b`).test(t))){s+=10;reasons.push('Family keyword')}else{s-=18;pen.push('family missing')}}
if(q.modelTokens.length){const hits=q.modelTokens.filter(z=>new RegExp(`\\b${z}\\b`).test(t));if(hits.length){s+=Math.min(24,hits.length*12);reasons.push(hits.length===q.modelTokens.length?'Exact model':'Model token')}else{s-=8;pen.push('model code missing')}}
if(q.gen){const g=t.match(/\bgen\s*(\d+)\b/)?.[1]||'';if(g===q.gen){s+=10;reasons.push('Same generation')}else if(g){s-=18;pen.push('different generation')}}
if(q.year){if(new RegExp(`\\b${q.year}\\b`).test(t)){s+=7;reasons.push('Same year')}else if(/\b20(?:1\d|2\d)\b/.test(t)){s-=8;pen.push('different year')}}
if(q.cpu){if(new RegExp(`\\b${q.cpu}\\b`).test(t)){s+=16;reasons.push('Exact CPU')}else if(/\b(core|intel|ryzen|i[3579])\b/.test(t)){s-=12;pen.push('different CPU')}}
if(q.gpu){const g=norm(q.gpu);if(t.includes(g)){s+=16;reasons.push('Exact GPU')}else if(/\b(rtx|gtx|rx|arc)\s*\d{3,4}/.test(t)){s-=14;pen.push('different GPU')}}
if(q.ram&&new RegExp(`\\b${q.ram}\\s*gb\\b`).test(t)){s+=6;reasons.push('RAM')}
if(q.storage&&t.includes(q.storage)){s+=6;reasons.push('Storage')}
if(q.size&&new RegExp(`\\b${q.size}(?:\\s*inch|\\s*in)?\\b`).test(t)){s+=4;reasons.push('Screen size')}
if(/\b(laptop|notebook|macbook|desktop|pc|workstation|all in one|aio|thinkcentre|thinkstation|optiplex|precision|elitedesk|prodesk|trident|aegis|infinite|codex)\b/.test(t)){s+=8;reasons.push('Complete device')}
s=Math.max(0,Math.min(100,s));let label=s>=88?'Excellent match':s>=72?'Strong match':s>=55?'Good match':s>=40?'Broadened match':'Weak match';return{score:s,label,reasons:[...new Set(reasons)].slice(0,5),warnings:pen.slice(0,3)}}
function price(x){return Number(x?.deliveredPrice||x?.price)||0}
function apply(d,q){const isOEM=!!d?.parsed,device=d?.mode==='device'||isOEM;if(!d||!device)return d;for(const key of ['ebay','google']){const src=d[key];if(!src?.items)continue;src.items=src.items.map(x=>({...x,matchQuality:score(q,x.title)})).sort((a,b)=>b.matchQuality.score-a.matchQuality.score||price(a)-price(b));const good=src.items.filter(x=>x.matchQuality.score>=40),use=good.length?good:src.items;src.qualityEligible=good.length;src.items=use;src.analysedListings=use.length;const ps=use.map(price).filter(Boolean);src.pricing=src.pricing||{};if(key==='ebay'&&ps.length){src.pricing.typicalUsed=median(ps);src.pricing.p25=pct(ps,.25);src.pricing.p75=pct(ps,.75);src.pricing.lowest=Math.min(...ps);src.pricing.highest=Math.max(...ps)}if(key==='google'&&ps.length){src.pricing.typicalNew=median(ps);src.pricing.competitiveLow=Math.min(...ps);src.pricing.competitiveHigh=Math.max(...ps)}}d.matchQualityApplied=true;return d}
window.fetch=async function(input,init){const r=await nativeFetch(input,init),url=typeof input==='string'?input:input?.url||'';if(!/\/functions\/v1\/(?:ebay-search|oem-search)/.test(url))return r;try{let q='';if(init?.body){const b=JSON.parse(init.body);q=String(b.query||b.model||b.search||b.specs||'')}const d=await r.clone().json();if(!d?.success)return r;const fullQuery=[q,d.query,d.inputQuery,d?.parsed?.brand,d?.parsed?.model,d?.parsed?.cpu,d?.parsed?.gpu,d?.parsed?.ram,d?.parsed?.storage].filter(Boolean).join(' ');const out=apply(d,fullQuery);return new Response(JSON.stringify(out),{status:r.status,statusText:r.statusText,headers:r.headers})}catch{return r}}
function currentQuery(type){if(type==='lap')return [document.getElementById('lapModel')?.value,document.getElementById('lapSpecs')?.value].filter(Boolean).join(' ');return [document.getElementById('deskSpecs')?.value,...[...document.querySelectorAll('#parts .pq')].map(x=>x.value)].filter(Boolean).join(' ')}
function badge(el,q){if(!el)return;el.querySelector('.matchQualityBadge')?.remove();const title=el.querySelector('a')?.textContent||el.querySelector('div:nth-child(2)')?.textContent||el.textContent||'',m=score(q,title);const b=document.createElement('div');b.className='matchQualityBadge';b.style.cssText='margin-top:7px;display:inline-block;padding:5px 8px;border:1px solid #565656;border-radius:999px;font-size:11px;font-weight:800;color:'+(m.score>=72?'#72e79b':m.score>=55?'#ffe06a':'#bbb')+';background:#181818';b.textContent=`${m.score}% · ${m.label}${m.reasons.length?' · '+m.reasons.join(' + '):''}`;el.appendChild(b)}
function annotate(){const lq=currentQuery('lap');if(lq)document.querySelectorAll('#lapEbay .item,#lapEbay .result,#lapGoogle .item,#lapGoogle .result').forEach(el=>badge(el,lq));const dq=currentQuery('desk');if(dq)document.querySelectorAll('#deskEvidence .item,#deskEvidence .result,#deskEvidence>div>div').forEach(el=>{if((el.textContent||'').includes('$'))badge(el,dq)})}
let timer;const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(annotate,80)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mo.observe(document.body,{childList:true,subtree:true});annotate()});else{mo.observe(document.body,{childList:true,subtree:true});annotate()}
})();