(()=>{
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
 const SB='https://ghdhairijqjqivqriigi.supabase.co', KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt', AUTH='morley_web_auth', PREF='morley_menu_prefs';
 let lastPage='home';
 function currentPage(){const active=$('.section.active');return active?.id||'home'}
 function go(page){if(page==='settings'&&currentPage()!=='settings')lastPage=currentPage();if(typeof window.morleyDesktopGo==='function')window.morleyDesktopGo(page);else if(typeof window.show==='function')window.show(page)}
 function row(icon,title,sub,action){return `<button class="morley-menu-row" data-action="${action}"><span class="morley-menu-icon">${icon}</span><span class="morley-menu-copy"><b>${title}</b><small>${sub}</small></span><span class="morley-menu-chevron">›</span></button>`}
 function group(title,rows){return `<section class="morley-menu-group"><h3>${title}</h3><div class="morley-menu-card">${rows}</div></section>`}
 function buildMenu(){const sec=$('#settings');if(!sec)return;if(!$('#morleyRelevantMore',sec)){sec.innerHTML=`<div id="morleyRelevantMore" class="morley-relevant-more"><div class="morley-menu-head"><div><small>B&L MORLEY</small><h1>Menu</h1></div></div>${group('Workspace',row('◷','Valuations & Deals','Saved valuations and deal history.','deals')+row('▣','Inventory','Stock, costs and resale values.','inventory')+row('↗','Sales History','Revenue and realised profit.','sales')+row('⌗','Barcode Scanner','Find or add stock quickly.','scanner'))}${group('Your account',row('●','Account & Profile','Signed-in account and profile details.','account')+row('⌁','Privacy & Security','Account privacy and session security.','privacy'))}${group('Data & preferences',row('☁','Backup & Data','Export, import and local app data.','backup')+row('♢','Notifications','Update and app notification preferences.','notifications')+row('◐','Display','Interface and display preferences.','display'))}${group('App',row('↻','Updates','Check app version and update status.','updates')+row('⚑','Report an Issue','Record an app problem for follow-up.','report')+row('§','Legal & Privacy','Privacy and application information.','legal')+row('ⓘ','About B&L Morley','Version and product information.','about'))}<button class="morley-menu-signout" data-action="signout">↪ <span>Sign out</span></button></div>`;$$('[data-action]',sec).forEach(b=>b.onclick=()=>act(b.dataset.action))}}
 function addTrigger(){let b=$('#morleyMenuTrigger');if(!b){b=document.createElement('button');b.id='morleyMenuTrigger';b.type='button';b.className='morley-menu-trigger morley-menu-trigger-fixed';b.innerHTML='<span class="morley-menu-bars">☰</span><span class="morley-menu-trigger-label">Menu</span>';b.setAttribute('aria-label','Open B&L Morley menu');b.onclick=()=>currentPage()==='settings'?go(lastPage||'home'):go('settings')}if(b.parentElement!==document.body)document.body.appendChild(b);b.classList.add('morley-menu-trigger-fixed')}
 function hideBottomMore(){$$('nav [data-page="settings"],nav [data-target="settings"],nav button,nav a').forEach(el=>{const t=(el.textContent||'').trim().toLowerCase();if(el.dataset?.page==='settings'||el.dataset?.target==='settings'||t==='more'||t==='menu')el.classList.add('morley-hide-more-tab')});$$('.desktop-side-nav [data-target="settings"]').forEach(el=>el.classList.add('morley-hide-more-tab'))}
 function removeProductionBadge(){$$('body *').forEach(el=>{if(el.children.length===0&&(el.textContent||'').trim().toLowerCase()==='production'){const target=el.closest('button,a,[class*="badge"],[class*="pill"],[class*="env"],[class*="status"]')||el;target.style.setProperty('display','none','important');target.setAttribute('aria-hidden','true')}})}
 function auth(){try{return JSON.parse(localStorage.getItem(AUTH)||'null')}catch{return null}}
 function uid(token){try{let p=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(p+'='.repeat((4-p.length%4)%4))).sub||''}catch{return''}}
 function prefs(){try{return JSON.parse(localStorage.getItem(PREF)||'{}')}catch{return{}}}
 function savePrefs(p){localStorage.setItem(PREF,JSON.stringify(p));applyPrefs()}
 function applyPrefs(){const p=prefs();document.documentElement.classList.toggle('morley-reduce-motion',!!p.reduceMotion);document.documentElement.classList.toggle('morley-compact-ui',!!p.compact);let st=$('#morleyPreferenceStyle');if(!st){st=document.createElement('style');st.id='morleyPreferenceStyle';document.head.appendChild(st)}st.textContent=`.morley-reduce-motion *{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important;scroll-behavior:auto!important}.morley-compact-ui .card,.morley-compact-ui [class*="card"]{padding-top:10px!important;padding-bottom:10px!important}`}
 function dialog(title,html,onOpen){let d=$('#morleyMenuDialog');if(!d){d=document.createElement('div');d.id='morleyMenuDialog';d.className='morley-menu-dialog';document.body.appendChild(d)}d.innerHTML=`<div class="morley-menu-dialog-card" style="max-height:82vh;overflow:auto"><button class="morley-menu-dialog-close">×</button><h2>${title}</h2><div class="morley-settings-body">${html}</div></div>`;d.classList.add('open');$('.morley-menu-dialog-close',d).onclick=()=>d.classList.remove('open');d.onclick=e=>{if(e.target===d)d.classList.remove('open')};onOpen?.(d)}
 const field=(label,id,value='',type='text')=>`<label style="display:block;margin:14px 0 6px;color:#9db0c9;font-size:12px;font-weight:800">${label}</label><input id="${id}" type="${type}" value="${String(value).replace(/"/g,'&quot;')}" style="box-sizing:border-box;width:100%;padding:12px 13px;border-radius:12px;border:1px solid rgba(47,124,255,.35);background:#041024;color:#fff">`;
 const btn=(id,text,secondary=false)=>`<button id="${id}" style="width:100%;margin-top:12px;padding:12px;border-radius:12px;border:1px solid ${secondary?'rgba(47,124,255,.35)':'#2f7cff'};background:${secondary?'#0a1b33':'linear-gradient(120deg,#1f5fd8,#2f7cff,#12c9ff)'};color:#fff;font-weight:900;cursor:pointer">${text}</button>`;
 function msg(d,text,ok=true){let m=$('.morley-settings-msg',d);if(!m){m=document.createElement('div');m.className='morley-settings-msg';$('.morley-settings-body',d).prepend(m)}m.textContent=text;m.style.cssText=`margin:0 0 10px;padding:10px 12px;border-radius:10px;background:${ok?'rgba(37,217,145,.1)':'rgba(255,90,110,.1)'};color:${ok?'#63efb5':'#ff9aa8'}`}
 async function profile(){const s=auth(),id=uid(s?.access_token||'');if(!s?.access_token||!id)throw new Error('Your session is not available. Sign in again.');const r=await fetch(`${SB}/rest/v1/profiles?select=id,email,display_name,is_enabled&id=eq.${encodeURIComponent(id)}`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok)throw new Error('Could not load your profile.');const a=await r.json();return a[0]||{email:s.email||'',display_name:''}}
 async function account(){dialog('Account & Profile','<p style="color:#9db0c9">Loading your authorised profile…</p>');const d=$('#morleyMenuDialog');try{const p=await profile();$('.morley-settings-body',d).innerHTML=`<p style="color:#9db0c9">Manage the name shown across B&L Morley.</p>${field('Email','mmEmail',p.email||auth()?.email||'','email')}${field('First and last name','mmName',p.display_name||'')}${btn('mmSave','Save Profile')}`;$('#mmEmail',d).disabled=true;$('#mmSave',d).onclick=async()=>{try{const s=auth(),id=uid(s.access_token),name=$('#mmName',d).value.trim();if(name.length<2)throw new Error('Enter your first and last name.');const r=await fetch(`${SB}/rest/v1/profiles?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({display_name:name})});if(!r.ok)throw new Error('Profile update failed.');localStorage.setItem('morley_profile_name',name);window.dispatchEvent(new Event('morley-profile-updated'));msg(d,'Profile updated successfully.')}catch(e){msg(d,e.message||String(e),false)}}}catch(e){$('.morley-settings-body',d).innerHTML=`<p style="color:#ff9aa8">${e.message}</p>`}}
 async function privacy(){const s=auth();dialog('Privacy & Security',`<p style="color:#9db0c9;line-height:1.5">Your web session is authenticated through B&L Morley. Authentication tokens are excluded from workspace backups.</p>${btn('mmCheck','Check Secure Session')}${btn('mmGlobal','Sign Out Everywhere',true)}`,d=>{$('#mmCheck',d).onclick=async()=>{try{await profile();msg(d,'Secure session is valid.')}catch(e){msg(d,e.message,false)}};$('#mmGlobal',d).onclick=async()=>{try{const a=auth();if(a?.access_token)await fetch(`${SB}/auth/v1/logout?scope=global`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${a.access_token}`}});localStorage.removeItem(AUTH);location.reload()}catch(e){msg(d,e.message||String(e),false)}}})}
 function backup(){dialog('Backup & Data',`<p style="color:#9db0c9;line-height:1.5">Export browser workspace/preferences without login credentials. Import restores saved local app data.</p>${btn('mmExport','Export Web Backup')}${field('Import backup file','mmImport','', 'file')}${btn('mmRestore','Restore Selected Backup',true)}`,d=>{$('#mmExport',d).onclick=()=>{const data={format:'bl-morley-web-backup-v1',exportedAt:new Date().toISOString(),storage:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k!==AUTH)data.storage[k]=localStorage.getItem(k)}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`BL-Morley-web-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);msg(d,'Backup exported.')} ;$('#mmRestore',d).onclick=async()=>{try{const f=$('#mmImport',d).files?.[0];if(!f)throw new Error('Choose a backup file first.');const data=JSON.parse(await f.text());if(data.format!=='bl-morley-web-backup-v1'||!data.storage)throw new Error('This is not a B&L Morley web backup.');Object.entries(data.storage).forEach(([k,v])=>{if(k!==AUTH)localStorage.setItem(k,String(v))});msg(d,'Backup restored. Reloading…');setTimeout(()=>location.reload(),700)}catch(e){msg(d,e.message||String(e),false)}}})}
 function notifications(){const p=prefs();dialog('Notifications',`<p style="color:#9db0c9">Control useful browser notifications and update prompts.</p><label style="display:flex;gap:10px;align-items:center;margin:14px 0"><input id="mmUpdateN" type="checkbox" ${p.updateAlerts!==false?'checked':''}> Update alerts</label><label style="display:flex;gap:10px;align-items:center;margin:14px 0"><input id="mmErrorN" type="checkbox" ${p.errorAlerts?'checked':''}> Valuation/error alerts</label>${btn('mmBrowserN','Enable Browser Notifications')}${btn('mmSaveN','Save Preferences',true)}`,d=>{$('#mmSaveN',d).onclick=()=>{savePrefs({...prefs(),updateAlerts:$('#mmUpdateN',d).checked,errorAlerts:$('#mmErrorN',d).checked});msg(d,'Notification preferences saved.')};$('#mmBrowserN',d).onclick=async()=>{if(!('Notification'in window))return msg(d,'This browser does not support notifications.',false);const r=await Notification.requestPermission();msg(d,r==='granted'?'Browser notifications enabled.':`Notification permission: ${r}`,r==='granted')}})}
 function display(){const p=prefs();dialog('Display',`<p style="color:#9db0c9">Keep the current cyber theme while adjusting motion and spacing.</p><label style="display:flex;gap:10px;align-items:center;margin:14px 0"><input id="mmMotion" type="checkbox" ${p.reduceMotion?'checked':''}> Reduce animations</label><label style="display:flex;gap:10px;align-items:center;margin:14px 0"><input id="mmCompact" type="checkbox" ${p.compact?'checked':''}> Compact interface</label>${btn('mmSaveD','Apply Display Settings')}`,d=>{$('#mmSaveD',d).onclick=()=>{savePrefs({...prefs(),reduceMotion:$('#mmMotion',d).checked,compact:$('#mmCompact',d).checked});msg(d,'Display settings applied.')}})}
 function updates(){dialog('Updates',`<p style="color:#9db0c9;line-height:1.5">The web app updates automatically from the production deployment. Reloading below bypasses normal browser cache for the latest shell.</p><div style="margin:12px 0;color:#dce9ff">Current web build: <b>${document.lastModified||'current deployment'}</b></div>${btn('mmReload','Check & Reload Latest Web Build')}`,d=>{$('#mmReload',d).onclick=()=>{const u=new URL(location.href);u.searchParams.set('_update',Date.now());location.replace(u)}})}
 function report(){dialog('Report an Issue',`<p style="color:#9db0c9">Create a detailed issue email with page and browser information already included.</p>${field('What happened?','mmIssue','')}${btn('mmIssueSend','Create Issue Email')}`,d=>{$('#mmIssueSend',d).onclick=()=>{const text=$('#mmIssue',d).value.trim();const body=`B&L Morley web issue%0A%0APage: ${encodeURIComponent(location.href)}%0ABrowser: ${encodeURIComponent(navigator.userAgent)}%0A%0AWhat happened:%0A${encodeURIComponent(text)}`;location.href=`mailto:?subject=${encodeURIComponent('B&L Morley web issue')}&body=${body}`}})}
 function legal(){dialog('Legal & Privacy','<p style="color:#9db0c9;line-height:1.65"><b style="color:#fff">Privacy</b><br>B&L Morley is an authorised business workspace. Authentication data is used to control access. Pricing requests may be sent to configured pricing providers to return market evidence.</p><p style="color:#9db0c9;line-height:1.65"><b style="color:#fff">Local browser data</b><br>Some workspace and preference data is stored in this browser. Exported backups deliberately exclude the web authentication session.</p>')}
 function about(){dialog('About B&L Morley',`<p style="color:#9db0c9;line-height:1.65"><b style="color:#fff">Buys & Loans Hub</b><br>Valuation and business workspace for B&L Morley.</p><p style="color:#9db0c9">Web deployment: ${document.lastModified||'current'}<br>Release channel: Production web</p>`)}
 function act(a){if(['deals','inventory','sales','scanner'].includes(a))return go(a);if(a==='signout'){const b=$('.morley-web-signout');if(b)return b.click();localStorage.removeItem(AUTH);location.reload();return}({account,privacy,backup,notifications,display,updates,report,legal,about}[a]||(()=>{}))()}
 function sync(){buildMenu();addTrigger();hideBottomMore();removeProductionBadge();applyPrefs()}
 function init(){sync();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;sync()})}).observe(document.body,{childList:true,subtree:true})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();