(()=>{
  const SUPABASE_URL='https://ghdhairijqjqivqriigi.supabase.co';
  const API_KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';
  const STORE='morley_web_auth';
  function session(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function when(v){if(!v)return '—';try{return new Intl.DateTimeFormat('en-AU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}}
  async function findings(){const token=session()?.access_token;if(!token)return[];const r=await fetch(`${SUPABASE_URL}/rest/v1/recovery_health_findings?select=id,kind,severity,status,summary,detail,occurrence_count,last_seen_at,resolved_at&order=last_seen_at.desc&limit=30`,{headers:{apikey:API_KEY,Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Could not load recovery health.');return r.json()}
  function inject(){const settings=document.getElementById('settings');if(!settings||document.getElementById('recoveryHealthCard'))return;const card=document.createElement('div');card.id='recoveryHealthCard';card.className='card';card.innerHTML=`<h2>✨ Nova + Guardian Recovery Monitor</h2><p class="muted">Read-only recovery intelligence. Nova and Guardian watch backup freshness, failures and repeated sync conflicts without gaining restore or repair authority.</p><div class="stats"><div><small>OPEN FINDINGS</small><b id="recoveryOpenCount">—</b></div><div><small>HIGH PRIORITY</small><b id="recoveryHighCount">—</b></div><div><small>MONITOR</small><b style="font-size:14px">Hourly</b></div><div><small>AUTO-REPAIR</small><b style="font-size:14px">Disabled</b></div></div><div class="bar"><button id="recoveryHealthRefresh" class="secondary">Refresh Monitor</button></div><p id="recoveryHealthStatus" class="muted">Loading recovery health…</p><div id="recoveryHealthList" class="list"></div>`;settings.appendChild(card);document.getElementById('recoveryHealthRefresh').onclick=()=>refresh().catch(showError)}
  function showError(e){const s=document.getElementById('recoveryHealthStatus');if(s){s.className='bad';s.textContent=e.message||String(e)}}
  async function refresh(){const rows=await findings(),open=rows.filter(x=>x.status==='open'),high=open.filter(x=>x.severity==='high');document.getElementById('recoveryOpenCount').textContent=String(open.length);document.getElementById('recoveryHighCount').textContent=String(high.length);const s=document.getElementById('recoveryHealthStatus');s.className=open.length?'warn':'good';s.textContent=open.length?`${open.length} recovery finding${open.length===1?'':'s'} need attention.`:'Recovery monitoring is healthy.';const host=document.getElementById('recoveryHealthList');host.innerHTML=rows.length?rows.map(x=>`<div class="item"><div><b>${esc(x.summary)}</b><small>${esc(x.severity.toUpperCase())} • ${esc(x.status)} • ${esc(when(x.last_seen_at))}${x.occurrence_count>1?` • seen ${x.occurrence_count} times`:''}</small></div></div>`).join(''):'<div class="item"><small>No recovery findings.</small></div>'}
  function init(){inject();refresh().catch(showError);setInterval(()=>refresh().catch(()=>{}),10*60*1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
  window.MorleyRecoveryHealth={refresh};
})();
