(()=>{
const $=id=>document.getElementById(id);
const busy=new WeakMap();
function inject(){const s=document.createElement('style');s.textContent=`
html{scroll-behavior:smooth}.app{overflow-x:hidden}.section{min-width:0}.card,.hero,.item,.result{min-width:0;overflow-wrap:anywhere}.bar{align-items:center}.bar button{min-height:44px}.pricingBusy{position:relative;pointer-events:none;opacity:.78}.pricingBusy:after{content:"";display:inline-block;width:13px;height:13px;margin-left:8px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;vertical-align:-2px;animation:spin .7s linear infinite}.appToast{position:fixed;left:50%;bottom:calc(78px + env(safe-area-inset-bottom));transform:translateX(-50%);z-index:60;width:min(92vw,560px);padding:12px 14px;border-radius:13px;background:#242424;border:1px solid #4a4a4a;box-shadow:0 15px 45px #0008;color:#f5f5f5;font-size:13px;font-weight:750;opacity:0;pointer-events:none;transition:.18s opacity,.18s transform}.appToast.show{opacity:1;transform:translateX(-50%) translateY(-4px)}.appToast.warn{border-color:#76661e;color:#ffe175}.appToast.bad{border-color:#7b343b;color:#ffadb4}.connectionBanner{display:none;margin-top:10px;padding:10px 12px;border-radius:12px;border:1px solid #745f19;background:#2b260d;color:#ffe47c;font-size:12px;font-weight:800}.connectionBanner.show{display:block}.statusDetail{font-size:11px;color:#aaa;margin-top:5px;line-height:1.4}@keyframes spin{to{transform:rotate(360deg)}}
@media(max-width:600px){button,input,select,textarea{font-size:16px}.card{padding:15px}.stats{grid-template-columns:1fr 1fr}.stats>div{min-width:0}.item{align-items:flex-start}.item button{flex:0 0 auto}.bar{display:grid;grid-template-columns:1fr 1fr}.bar button{width:100%}.bar>*:only-child{grid-column:1/-1}.decisionGrid{grid-template-columns:1fr 1fr!important}#parts .part{grid-template-columns:1fr 1fr!important}#parts .part>div:first-child{grid-column:1/-1}nav{overflow-x:auto;grid-auto-flow:column;grid-auto-columns:minmax(66px,1fr);grid-template-columns:none!important}nav button{min-width:66px}}
`;document.head.appendChild(s)}
function toast(msg,type=''){let t=$('appToast');if(!t){t=document.createElement('div');t.id='appToast';t.className='appToast';document.body.appendChild(t)}t.textContent=msg;t.className='appToast '+type+' show';clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3200)}
function banner(){let b=$('connectionBanner');if(b)return b;const home=$('home'),hero=home?.querySelector('.hero');if(!home||!hero)return null;b=document.createElement('div');b.id='connectionBanner';b.className='connectionBanner';b.textContent='Offline — live pricing is unavailable until your connection returns.';hero.insertAdjacentElement('afterend',b);return b}
function syncOnline(){const online=navigator.onLine,b=banner(),tile=$('onlineStatus');if(b)b.classList.toggle('show',!online);if(tile){tile.textContent=online?'ONLINE':'OFFLINE';tile.className=online?'good':'bad'}if(!online){['lapAnalyse','deskAnalyse'].forEach(id=>{const el=$(id);if(el)el.title='Live pricing requires an internet connection.'})}}
function markBusy(btn,label){if(!btn||busy.has(btn))return;busy.set(btn,{text:btn.textContent,disabled:btn.disabled});btn.textContent=label;btn.classList.add('pricingBusy');btn.disabled=true}
function clearBusy(btn){const s=busy.get(btn);if(!s)return;btn.textContent=s.text;btn.classList.remove('pricingBusy');btn.disabled=s.disabled;busy.delete(btn)}
function statusText(type){return $(type==='laptop'?'lapStatus':'deskStatus')}
function hasUsefulResult(type){const ids=type==='laptop'?['lapNew','lapUsed']:['deskNew','deskUsed'];return ids.some(id=>Number(($(id)?.textContent||'').replace(/[^0-9.]/g,''))>0)}
function watchPricing(type){const btn=$(type==='laptop'?'lapAnalyse':'deskAnalyse');if(!btn)return;btn.addEventListener('click',()=>{if(!navigator.onLine){toast('You are offline. Reconnect before running live pricing.','warn');return}markBusy(btn,type==='laptop'?'Pricing laptop…':'Pricing desktop…');const status=statusText(type),start=Date.now();const timer=setInterval(()=>{const txt=(status?.textContent||'').toLowerCase(),done=hasUsefulResult(type)||/hold|buy|pass|negotiate|price ready|estimated|priced|valuation/.test(txt),failed=/error|failed|unavailable|both sources failed|network|http 5|timed out/.test(txt);if(done||failed||Date.now()-start>15000){clearInterval(timer);clearBusy(btn);if(failed)toast('Live pricing could not complete. Check your connection and try again.','bad');else if(Date.now()-start>15000&&!done)toast('Pricing is taking longer than expected. You can retry safely.','warn')}} ,300)},{capture:false})}
function protectDisabled(){document.addEventListener('click',e=>{const b=e.target?.closest?.('button');if(!b||!b.disabled)return;e.preventDefault();e.stopPropagation();toast('This action becomes available after a valid valuation is ready.','warn')},true)}
function enhanceStatuses(){[['lapStatus','Laptop pricing status'],['deskStatus','Desktop pricing status']].forEach(([id,label])=>{const p=$(id);if(!p||p.nextElementSibling?.classList?.contains('statusDetail'))return;const d=document.createElement('div');d.className='statusDetail';d.textContent=`${label} will show whether results are exact, estimated, low-confidence or unavailable.`;p.insertAdjacentElement('afterend',d)})}
function navGuard(){document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}))}))}
function boot(){inject();banner();syncOnline();enhanceStatuses();watchPricing('laptop');watchPricing('desktop');protectDisabled();navGuard();window.addEventListener('online',()=>{syncOnline();toast('Back online — live pricing is available.');});window.addEventListener('offline',()=>{syncOnline();toast('You are offline. Live pricing is temporarily unavailable.','warn')});window.addEventListener('error',e=>{if(/fetch|network/i.test(String(e?.message||'')))toast('A network error occurred. Please retry the pricing search.','bad')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,500));else setTimeout(boot,500);
})();