(()=>{
const SUPABASE_URL='https://ghdhairijqjqivqriigi.supabase.co';
const API_KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';
const STORE='morley_web_auth';
const $=(s,r=document)=>r.querySelector(s);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let captchaToken='';

function loadSession(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function saveSession(s){localStorage.setItem(STORE,JSON.stringify(s))}
function clearSession(){localStorage.removeItem(STORE)}
function jwtSub(token){try{const p=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(p+'='.repeat((4-p.length%4)%4))).sub||''}catch{return''}}
async function jsonFetch(url,opt={}){const r=await fetch(url,opt);let body={};try{body=await r.json()}catch{};if(!r.ok){const msg=body.error_description||body.msg||body.message||body.error||`Request failed (${r.status})`;throw new Error(msg)}return body}
async function verifyAuthorised(token){const id=jwtSub(token);if(!id)return false;const r=await fetch(`${SUPABASE_URL}/rest/v1/profiles?select=is_enabled&id=eq.${encodeURIComponent(id)}`,{headers:{apikey:API_KEY,Authorization:`Bearer ${token}`}});if(!r.ok)return false;const a=await r.json();return !!(a[0]&&a[0].is_enabled)}
async function refreshSession(s){if(!s?.refresh_token)return null;const b=await jsonFetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{'Content-Type':'application/json',apikey:API_KEY},body:JSON.stringify({refresh_token:s.refresh_token})});if(!(await verifyAuthorised(b.access_token)))throw new Error('This account is no longer authorised for B&L Morley.');const n={access_token:b.access_token,refresh_token:b.refresh_token||s.refresh_token,expires_at:Date.now()+((b.expires_in||3600)*1000),email:s.email||''};saveSession(n);return n}
async function validSession(){let s=loadSession();if(!s)return null;if(s.access_token&&(!s.expires_at||s.expires_at>Date.now()+60000)){if(await verifyAuthorised(s.access_token))return s;clearSession();return null}try{return await refreshSession(s)}catch{clearSession();return null}}
function authPayload(obj){if(!captchaToken)throw new Error('Complete the security check first.');return {...obj,gotrue_meta_security:{captcha_token:captchaToken}}}
async function signIn(email,password){const b=await jsonFetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{'Content-Type':'application/json',apikey:API_KEY},body:JSON.stringify(authPayload({email:email.trim(),password}))});if(!(await verifyAuthorised(b.access_token)))throw new Error('This account is not authorised for B&L Morley. Contact an administrator.');saveSession({access_token:b.access_token,refresh_token:b.refresh_token||'',expires_at:Date.now()+((b.expires_in||3600)*1000),email:email.trim().toLowerCase()});}
async function signUp(email,password,inviteCode){if(password.length<10)throw new Error('Password must be at least 10 characters.');await jsonFetch(`${SUPABASE_URL}/functions/v1/redeem-app-invite`,{method:'POST',headers:{'Content-Type':'application/json',apikey:API_KEY},body:JSON.stringify({email:email.trim(),password,inviteCode:inviteCode.trim(),captchaToken})});}
async function resetPassword(email){await jsonFetch(`${SUPABASE_URL}/auth/v1/recover?redirect_to=${encodeURIComponent(location.origin+location.pathname)}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:API_KEY},body:JSON.stringify(authPayload({email:email.trim()}))});}
function friendly(e){const m=String(e?.message||e||'Something went wrong.');const n=m.toLowerCase();if(n.includes('invalid login credentials'))return'Incorrect email address or password.';if(n.includes('captcha'))return'Security check failed or expired. Complete it again.';if(n.includes('rate')||n.includes('too many'))return'Too many attempts. Please wait a few minutes and try again.';return m}

function styles(){const s=document.createElement('style');s.textContent=`
#morleyWebAuth{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;background:#111;color:#fff;overflow:hidden;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}
#morleyWebAuth video{position:absolute;inset:-3%;width:106%;height:106%;object-fit:cover;filter:blur(5px) saturate(.9);transform:scale(1.015)}
#morleyWebAuth .wa-shade{position:absolute;inset:0;background:rgba(0,0,0,.62)}
#morleyWebAuth .wa-card{position:relative;width:min(470px,calc(100% - 36px));padding:30px;border-radius:26px;background:rgba(22,22,22,.78);border:1px solid rgba(255,255,255,.14);box-shadow:0 28px 80px rgba(0,0,0,.48);backdrop-filter:blur(18px)}
#morleyWebAuth .wa-brand{font-size:34px;font-weight:950;letter-spacing:-1px;margin:0 0 5px}#morleyWebAuth .wa-title{color:#ffd400;font-size:26px;font-weight:900;margin:0 0 18px}
#morleyWebAuth label{display:block;margin:11px 0 6px;color:#ddd;font-size:12px;font-weight:800}#morleyWebAuth input{width:100%;padding:13px 14px;background:rgba(12,12,12,.82);border:1px solid #555;border-radius:13px;color:#fff;outline:none;font:inherit}#morleyWebAuth input:focus{border-color:#ffd400;box-shadow:0 0 0 3px rgba(255,212,0,.14)}
#morleyWebAuth iframe{width:100%;height:112px;border:0;background:transparent;margin:8px 0 2px}#morleyWebAuth button{width:100%;padding:13px 15px;border-radius:13px;border:1px solid #d9b900;background:#ffd400;color:#111;font-weight:950;cursor:pointer;margin-top:10px}#morleyWebAuth button.secondary{background:transparent;color:#ffd400;border-color:#6e611e}#morleyWebAuth button.link{background:transparent;border:0;color:#ddd;margin-top:5px;padding:8px}#morleyWebAuth .wa-msg{min-height:20px;margin-top:9px;font-size:13px;color:#ff8a98}#morleyWebAuth .wa-msg.ok{color:#57d68d}#morleyWebAuth .wa-note{font-size:12px;color:#aaa;margin-top:13px;line-height:1.45}
#morleyWebAuth .hide{display:none!important}.morley-web-signout{border:1px solid #5a501b!important;background:#2a2612!important;color:#ffd400!important;border-radius:999px!important;padding:8px 12px!important;font-size:12px!important;box-shadow:none!important}
@media(max-width:600px){#morleyWebAuth .wa-card{padding:22px;border-radius:20px}#morleyWebAuth .wa-brand{font-size:30px}}
`;document.head.appendChild(s)}
function markup(){const root=document.createElement('div');root.id='morleyWebAuth';root.innerHTML=`<video autoplay muted loop playsinline preload="auto" src="web-assets/morley_buys_login_bg_app.mp4"></video><div class="wa-shade"></div><div class="wa-card"><div class="wa-brand">B&L Morley</div><div class="wa-title" id="waTitle">Sign in</div><div id="waInvite" class="hide"><label>Invite code</label><input id="waInviteCode" autocomplete="one-time-code"></div><label>Email</label><input id="waEmail" type="email" autocomplete="email"><div id="waPasswords"><label>Password</label><input id="waPassword" type="password" autocomplete="current-password"></div><div id="waConfirm" class="hide"><label>Confirm password</label><input id="waConfirmPassword" type="password" autocomplete="new-password"></div><iframe id="waTurnstile" src="admin/turnstile.html" title="Security check"></iframe><div id="waMsg" class="wa-msg"></div><button id="waPrimary">Sign in</button><button id="waSignup" class="secondary">Sign Up with Invite</button><button id="waForgot" class="link">Forgot Password</button><button id="waBack" class="link hide">Back to Sign in</button><div class="wa-note">Private B&L Morley system. Access is limited to authorised accounts.</div></div>`;document.body.appendChild(root);return root}
function addSignOut(){const tryAdd=()=>{const host=$('#desktopWorkspaceHeader .desktop-header-actions')||$('.top');if(!host||$('.morley-web-signout'))return false;const b=document.createElement('button');b.className='morley-web-signout';b.textContent='Sign out';b.onclick=()=>{clearSession();location.reload()};host.appendChild(b);return true};if(!tryAdd()){let n=0;const t=setInterval(()=>{if(tryAdd()||++n>30)clearInterval(t)},200)}}
async function init(){styles();const existing=await validSession();if(existing){addSignOut();return}const root=markup(),title=$('#waTitle',root),msg=$('#waMsg',root),primary=$('#waPrimary',root),signup=$('#waSignup',root),forgot=$('#waForgot',root),back=$('#waBack',root),invite=$('#waInvite',root),confirm=$('#waConfirm',root),passwords=$('#waPasswords',root);let mode='signin';
const resetCaptcha=()=>{captchaToken='';const f=$('#waTurnstile',root);f.src=f.src.split('?')[0]+'?r='+Date.now()};const setMode=m=>{mode=m;msg.textContent='';invite.classList.toggle('hide',m!=='signup');confirm.classList.toggle('hide',m!=='signup');passwords.classList.toggle('hide',m==='reset');signup.classList.toggle('hide',m!=='signin');forgot.classList.toggle('hide',m!=='signin');back.classList.toggle('hide',m==='signin');title.textContent=m==='signin'?'Sign in':m==='signup'?'Private sign up':'Forgot password';primary.textContent=m==='signin'?'Sign in':m==='signup'?'Create authorised account':'Send reset email';resetCaptcha()};
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;const d=e.data||{};if(d.source!=='morley-turnstile')return;if(d.type==='token'){captchaToken=d.value||'';msg.textContent='Security check complete.';msg.className='wa-msg ok'}else{captchaToken='';msg.textContent=d.type==='expired'?'Security check expired. Complete it again.':'Security check failed. Please retry.';msg.className='wa-msg'}});
signup.onclick=()=>setMode('signup');forgot.onclick=()=>setMode('reset');back.onclick=()=>setMode('signin');primary.onclick=async()=>{const email=$('#waEmail',root).value,password=$('#waPassword',root).value,confirmPassword=$('#waConfirmPassword',root).value,code=$('#waInviteCode',root).value;if(!email){msg.textContent='Enter your email address.';return}if(!captchaToken){msg.textContent='Complete the security check first.';return}primary.disabled=true;msg.className='wa-msg';msg.textContent='Please wait…';try{if(mode==='signin'){if(!password)throw new Error('Enter your password.');await signIn(email,password);root.remove();addSignOut()}else if(mode==='signup'){if(password!==confirmPassword)throw new Error('Passwords do not match.');await signUp(email,password,code);msg.className='wa-msg ok';msg.textContent='Account created. You can sign in now.';setMode('signin')}else{await resetPassword(email);msg.className='wa-msg ok';msg.textContent='Password reset email sent. Check your inbox.';setMode('signin')}}catch(e){msg.textContent=friendly(e);resetCaptcha()}finally{primary.disabled=false}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();