import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(['https://buyshub.me','https://www.buyshub.me','https://beaustwrt248-netizen.github.io']);
const clean=(v:unknown,n=240)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,n);
function mask(v:unknown,n=240){let s=clean(v,n);s=s.replace(/\b(IMEI(?:\s*\d)?|serial(?:\s*(?:number|no\.?))?)\s*[:#-]?\s*([A-Za-z0-9-]{6,})/gi,(_m,label,value)=>`${label} ••••${String(value).replace(/-/g,'').slice(-4)}`);s=s.replace(/\b\d{10,20}\b/g,value=>`••••${value.slice(-4)}`);return s}
function headers(req:Request){const origin=req.headers.get('Origin')||'';return{'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGINS.has(origin)?origin:'https://buyshub.me','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'}}
async function authorise(req:Request){if(!SUPABASE_URL||!SERVICE_ROLE)return{error:'Camera audit configuration unavailable',status:503}as const;const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return{error:'Authentication required',status:401}as const;const{data:{user},error}=await admin.auth.getUser(token);if(error||!user)return{error:'Invalid session',status:401}as const;const{data:profile,error:profileError}=await admin.from('profiles').select('role,is_enabled').eq('id',user.id).maybeSingle();if(profileError)throw profileError;if(!profile?.is_enabled||profile.role!=='admin')return{error:'Admin access required',status:403}as const;return{user}as const}
function textArray(v:unknown,max=12,n=180){return Array.isArray(v)?v.map(x=>mask(x,n)).filter(Boolean).slice(0,max):[]}
function ids(v:unknown){if(!Array.isArray(v))return[];const out:string[]=[];for(const row of v){const id=clean((row as any)?.id,100);if(id&&!out.includes(id))out.push(id);if(out.length>=10)break}return out}
function functionality(v:any){const allow=(x:unknown)=>Array.isArray(x)?x.map(y=>clean(y,60)).filter(Boolean).slice(0,16):[];return{complete:Boolean(v?.complete),passed:allow(v?.passed),failed:allow(v?.failed),pending:allow(v?.pending),source:'staff-manual-checklist'}}
function finite(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?Math.round(n*100)/100:null}
Deno.serve(async(req:Request)=>{const h=headers(req),reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:h});if(req.method==='OPTIONS')return new Response('ok',{headers:h});if(req.method!=='POST')return reply({error:'POST required'},405);try{const auth=await authorise(req);if('error'in auth)return reply({error:auth.error},auth.status);let body:any={};try{body=await req.json()}catch{return reply({error:'Invalid JSON request'},400)}const assessment=body?.assessment&&typeof body.assessment==='object'?body.assessment:{};const market=body?.market_summary&&typeof body.market_summary==='object'?body.market_summary:{};const func=functionality(body?.functionality_gate||{});const details={source:'nova-camera-assistant',privacy:{photos_stored:false,full_identifiers_stored:false},identity:{likely_brand:clean(assessment.likely_brand,100)||null,likely_family:clean(assessment.likely_family,140)||null,likely_model:clean(assessment.likely_model,180)||null,model_number:mask(assessment.model_number,120)||null,colour:clean(assessment.colour,100)||null,storage:clean(assessment.storage,100)||null,confidence:Math.max(0,Math.min(1,Number(assessment.confidence)||0))},condition:{grade:clean(assessment.condition_grade,16)||null,summary:mask(assessment.condition_summary,300)||null,visible_condition:textArray(assessment.visible_condition,16,180),damage_flags:textArray(assessment.damage_flags,12,180),accessories_present:textArray(assessment.accessories_present,12,180),missing_parts:textArray(assessment.missing_parts,12,180)},evidence_by_photo:Array.isArray(assessment.evidence_by_photo)?assessment.evidence_by_photo.slice(0,6).map((group:any)=>({photo_index:Number(group?.photo_index)||null,evidence:textArray(group?.evidence,8,220)})).filter((group:any)=>Number.isInteger(group.photo_index)&&group.photo_index>=1&&group.photo_index<=6):[],catalogue_match_ids:ids(body?.matches),market:{median_aud:finite(market.market_median_aud),suggested_max_buy_aud:finite(market.suggested_max_buy_aud),identity_verified:Boolean(market.identity_verified),listing_count:Number.isFinite(Number(market.listing_count))?Math.max(0,Math.min(500,Math.trunc(Number(market.listing_count)))):0},functionality_gate:func,final_offer_ready:Boolean(body?.final_offer_ready)&&func.complete&&func.failed.length===0};const targetId=details.catalogue_match_ids[0]||details.identity.model_number||details.identity.likely_model||null;const{data,error}=await admin.from('admin_audit_log').insert({actor_user_id:auth.user.id,action:'nova_camera_assessment_saved',target_type:'device_assessment',target_id:targetId,details}).select('id,created_at').single();if(error)throw error;return reply({ok:true,audit_id:data.id,created_at:data.created_at})}catch(error){console.error('[nova-camera-audit-save]',error instanceof Error?error.message:String(error));return new Response(JSON.stringify({error:'Camera assessment could not be saved'}),{status:500,headers:headers(req)})}});
