import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../admin/morley-ai.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../admin/nova-control-centre.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../admin/nova-control-centre.css',import.meta.url),'utf8');
const brand=fs.readFileSync(new URL('../admin/nova-brand.js',import.meta.url),'utf8');
for(const label of ['Overview','Nova Chat','Training','Knowledge','Performance','Guardian','Memory','Activity','Settings']) assert.ok(html.includes(label),`missing ${label}`);
assert.ok(html.includes('© 2026 Morley Buys • Backed by Nova AI'));
assert.ok(html.includes('The intelligence behind Morley Buys'));
assert.ok(html.includes('GUARDIAN PROTECTED'));
assert.ok(html.includes('human-approved'));
assert.ok(html.includes('aria-label="Nova Core status"'));
assert.ok(html.includes('aria-label="Nova control centre"'));
assert.ok(html.indexOf('morley-ai-core.js') < html.indexOf('nova-brand.js'));
assert.ok(brand.includes("window,'NovaAI'"));
assert.ok(brand.includes('window.MorleyAI'));
for(const cap of ["catalogue.summary","valuation.summary","guardian.diagnostics","learning.persisted"]) assert.ok(js.includes(`safeRun('${cap}')`),`missing live capability ${cap}`);
assert.ok(!js.includes('system.overview'));
assert.ok(js.includes("window.MorleyAI.run('learning.harvest'"));
assert.ok(js.includes("setAttribute('aria-pressed'"));
assert.ok(js.includes('No protected action was taken'));
assert.ok(css.includes('@media(max-width:900px)'));
assert.ok(css.includes('@media(max-width:560px)'));
for(const forbidden of ['SUPABASE_SERVICE_ROLE_KEY','service_role','auth.admin']) assert.ok(![html,js,css,brand].join('\n').includes(forbidden),`forbidden client authority token: ${forbidden}`);
console.log('Nova control centre contract passed');
