const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const read = (path) => fs.readFileSync(path, 'utf8');

test('Resend edge function keeps credentials and recipients server-side', () => {
  const source = read('supabase/functions/send-morley-email/index.ts');
  assert.match(source, /RESEND_API_KEY/);
  assert.match(source, /RESEND_FROM_EMAIL/);
  assert.match(source, /getCaller/);
  assert.match(source, /activeAdminEmails/);
  assert.doesNotMatch(source, /body\?\.to|body\.to|reqBody\.to/);
  assert.match(source, /target_installation_id/);
  assert.match(source, /Device-only target is not linked to an email recipient/);
});

test('web admin invite secrets are generated by the authenticated backend', () => {
  const source = read('admin/invites.js');
  assert.match(source, /send-morley-email/);
  assert.match(source, /action:'create_invite'/);
  assert.doesNotMatch(source, /crypto\.getRandomValues|sha256Hex|admin_create_team_invite/);
});

test('support and notification email calls use persisted object identifiers', () => {
  const support = read('admin/support-tickets.js');
  const notifications = read('admin/targeted-notifications.js');
  assert.match(support, /action:'support_ticket_reply'/);
  assert.match(support, /message_id:message\.id/);
  assert.match(notifications, /action:'notification_job'/);
  assert.match(notifications, /job_id:job\.id/);
  assert.match(notifications, /if\(!target_installation_id\)/);
});

test('Android Admin shares the same emailed invite endpoint', () => {
  const source = read('android/adminapp/src/main/java/com/buysloans/admin/TeamInviteApi.kt');
  assert.match(source, /\/functions\/v1\/send-morley-email/);
  assert.match(source, /put\("action", "create_invite"\)/);
  assert.match(source, /put\("action", "reissue_invite"\)/);
  assert.match(source, /delivery/);
  assert.doesNotMatch(source, /invite_code/);
});

test('private invite codes are delivered by email and are not returned to clients', () => {
  const edgeFunction = read('supabase/functions/send-morley-email/index.ts');
  const androidPanel = read('android/adminapp/src/main/java/com/buysloans/admin/TeamInvitePanel.kt');
  const adminHtml = read('admin/index.html');
  assert.match(edgeFunction, /delivery: "email"/);
  assert.doesNotMatch(edgeFunction, /invite_code:/);
  assert.doesNotMatch(androidPanel, /Copy code|ONE-TIME INVITE CODE/);
  assert.match(androidPanel, /Email private invite/);
  assert.match(adminHtml, /Email private invite/);
});
