import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});
const MAX_BYTES=2_000_000;
const KEYS=['bm_inv','bm_sales','bm_recent'] as const;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
function reply(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
function msg(e:unknown){return e instanceof Error?e.message:String(e)}
async function user(req:Request){const h=req.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))throw new Error('AUTH_REQUIRED');const token=h.slice(7).trim();const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw new Error('AUTH_REQUIRED');return data.user}
function cleanState(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('STATE_INVALID');const out:Record<string,unknown[]>={bm_inv:[],bm_sales:[],bm_recent:[]};for(const key of KEYS){const v=(input as Record<string,unknown>)[key];if(v!=null&&!Array.isArray(v))throw new Error('STATE_INVALID');out[key]=Array.isArray(v)?v:[]}const bytes=new TextEncoder().encode(JSON.stringify(out)).byteLength;if(bytes>MAX_BYTES)throw new Error('STATE_TOO_LARGE');return out}
function identity(row:unknown,index:number){if(row&&typeof row==='object'){const r=row as Record<string,unknown>;for(const k of ['id','uuid','stock_number','stockNumber','barcode']){if(r[k]!=null&&String(r[k]))return `${k}:${String(r[k])}`}}return `anon:${index}:${JSON.stringify(row)}`}
function timestamp(row:unknown){if(!row||typeof row!=='object')return 0;const r=row as Record<string,unknown>;for(const k of ['updated_at','updatedAt','modified_at','modifiedAt','created_at','createdAt','date','time']){const t=Date.parse(String(r[k]||''));if(Number.isFinite(t))return t}return 0}
function mergeArray(server:unknown[],client:unknown[]){const map=new Map<string,unknown>();server.forEach((r,i)=>map.set(identity(r,i),r));client.forEach((r,i)=>{const k=identity(r,i),old=map.get(k);if(old===undefined||timestamp(r)>=timestamp(old))map.set(k,r)});return Array.from(map.values())}
function mergeState(server:Record<string,unknown[]>,client:Record<string,unknown[]>){return {bm_inv:mergeArray(server.bm_inv||[],client.bm_inv||[]),bm_sales:mergeArray(server.bm_sales||[],client.bm_sales||[]),bm_recent:mergeArray(server.bm_recent||[],client.bm_recent||[]).slice(-250)}}
async function current(uid:string){const {data,error}=await admin.from('user_sync_state').select('revision,state,updated_by_installation,updated_at').eq('user_id',uid).maybeSingle();if(error)throw error;return data||{revision:0,state:{bm_inv:[],bm_sales:[],bm_recent:[]},updated_by_installation:null,updated_at:null}}
async function log(uid:string,type:string,revision:number|null,installation:string,detail:Record<string,unknown>={}){await admin.from('user_sync_events').insert({user_id:uid,event_type:type,revision,installation_id:installation||null,detail})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return reply({error:'Method not allowed'},405);try{const u=await user(req);const b=await req.json().catch(()=>({}));const action=String(b?.action||'pull');const installation=String(b?.installation_id||'').slice(0,200);if(action==='pull'){const row=await current(u.id);await log(u.id,'pull',Number(row.revision),installation);return reply(row)}if(action==='push'||action==='offline_replay'){const state=cleanState(b?.state);const expected=Math.max(0,Number(b?.base_revision)||0);const row=await current(u.id);if(Number(row.revision)!==expected){await log(u.id,'conflict',Number(row.revision),installation,{client_revision:expected});return reply({error:'SYNC_CONFLICT',server:row},409)}const next=expected+1;const now=new Date().toISOString();const {data,error}=await admin.from('user_sync_state').upsert({user_id:u.id,revision:next,state,updated_by_installation:installation||null,updated_at:now},{onConflict:'user_id'}).select('revision,state,updated_by_installation,updated_at').single();if(error)throw error;await log(u.id,action==='offline_replay'?'offline_replay':'push',next,installation);return reply(data)}if(action==='merge'){const client=cleanState(b?.state);const row=await current(u.id);const server=cleanState(row.state);const merged=mergeState(server,client);const next=Number(row.revision)+1;const now=new Date().toISOString();const {data,error}=await admin.from('user_sync_state').upsert({user_id:u.id,revision:next,state:merged,updated_by_installation:installation||null,updated_at:now},{onConflict:'user_id'}).select('revision,state,updated_by_installation,updated_at').single();if(error)throw error;await log(u.id,'merge',next,installation,{from_revision:Number(row.revision)});return reply(data)}return reply({error:'Unsupported action'},400)}catch(e){const m=msg(e);if(m==='AUTH_REQUIRED')return reply({error:'Authentication required'},401);if(m==='STATE_INVALID'||m==='STATE_TOO_LARGE')return reply({error:'Sync state invalid or too large'},400);console.error('user-sync-state',m);return reply({error:'Sync operation failed'},500)}});