from pathlib import Path

main = Path(__file__).resolve().parent / 'app' / 'src' / 'main' / 'java' / 'com' / 'buysloans' / 'hub' / 'MainActivity.kt'
text = main.read_text(encoding='utf-8')

old_features = '''private fun features(s:String):Features{val x=norm(s);val brand=brands.firstOrNull{x.contains(Regex("\\b${Regex.escape(it)}\\b"))}.orEmpty();val family=families.firstOrNull{x.contains(it)}.orEmpty();val cpu=Regex("\\b(?:i[3579][ -]?)?(\\d{4,5}[a-z]{0,3})\\b").find(x)?.groupValues?.get(1).orEmpty();val gpu=Regex("\\b((?:rtx|gtx|rx|arc)\\s*\\d{3,4}(?:\\s*(?:ti|super|xt|xtx))?)\\b").find(x)?.groupValues?.get(1).orEmpty();val ram=Regex("\\b(8|12|16|18|24|32|36|48|64|96|128)\\s*gb\\b").find(x)?.groupValues?.get(1).orEmpty();val storage=Regex("\\b(?:128|256|512)\\s*gb\\b|\\b(?:1|2|4|8)\\s*tb\\b").find(x)?.value.orEmpty();val alphaNum=x.split(" ").filter{it.length>=3&&it.any(Char::isLetter)&&it.any(Char::isDigit)&&it!=cpu};val gen=Regex("\\bgen\\s*(\\d+)\\b").find(x)?.groupValues?.get(1)?.let{"gen$it"};val tokens=(alphaNum+listOfNotNull(gen)).distinct();return Features(brand,family,cpu,gpu,ram,storage,tokens)}'''

new_features = '''private fun features(s:String):Features{val x=norm(s);val brand=brands.firstOrNull{x.contains(Regex("\\b${Regex.escape(it)}\\b"))}.orEmpty();val family=families.firstOrNull{x.contains(it)}.orEmpty();val intelCpu=Regex("\\b(?:i[3579][ -]?)?(\\d{4,5}[a-z]{0,3})\\b").find(x)?.groupValues?.get(1).orEmpty();val appleCpu=Regex("\\bm[1-4](?:\\s*(?:pro|max|ultra))?\\b").find(x)?.value.orEmpty();val cpu=if(appleCpu.isNotBlank())appleCpu else intelCpu;val gpu=Regex("\\b((?:rtx|gtx|rx|arc)\\s*\\d{3,4}(?:\\s*(?:ti|super|xt|xtx))?)\\b").find(x)?.groupValues?.get(1).orEmpty();val ram=Regex("\\b(8|12|16|18|24|32|36|48|64|96|128)\\s*gb\\b").find(x)?.groupValues?.get(1).orEmpty();val storage=Regex("\\b(?:128|256|512)\\s*gb\\b|\\b(?:1|2|4|8)\\s*tb\\b").find(x)?.value.orEmpty();val alphaNum=x.split(" ").filter{it.length>=3&&it.any(Char::isLetter)&&it.any(Char::isDigit)&&it!=cpu&&!it.startsWith("gen")};return Features(brand,family,cpu,gpu,ram,storage,alphaNum.distinct())}'''

old_classify = '''private fun classify(query:String,title:String):Triple<MatchTier,Int,String>{val q=features(query);val t=features(title);val tx=norm(title);val compact=tx.replace(" ","");var score=0;val r=mutableListOf<String>();val brandMismatch=q.brand.isNotBlank()&&t.brand.isNotBlank()&&q.brand!=t.brand;if(q.brand.isNotBlank()&&q.brand==t.brand){score+=30;r+="Brand"};if(q.family.isNotBlank()&&tx.contains(q.family)){score+=28;r+="Family"};val hits=q.modelTokens.count{compact.contains(it.replace(" ",""))||tx.contains(Regex("\\b${Regex.escape(it)}\\b"))};if(hits>0){score+=minOf(32,hits*16);r+="Model"};if(q.cpu.isNotBlank()&&tx.contains(Regex("\\b${Regex.escape(q.cpu)}\\b"))){score+=14;r+="CPU"};if(q.gpu.isNotBlank()&&tx.contains(norm(q.gpu))){score+=14;r+="GPU"};if(q.ram.isNotBlank()&&tx.contains(Regex("\\b${q.ram}\\s*gb\\b"))){score+=5;r+="RAM"};if(q.storage.isNotBlank()&&tx.contains(norm(q.storage))){score+=5;r+="Storage"};score=score.coerceAtMost(100);val accessory=Regex("\\b(cable|adapter|charger|battery|keyboard|mouse|case|cover|stand|webcam|module|ssd|ram kit|memory|motherboard|heatsink|fan|screen|display|replacement|part|parts|bezel|hinge|dock|docking|power supply|psu)\\b").containsMatchIn(tx);val modelSatisfied=q.modelTokens.isEmpty()||hits==q.modelTokens.size;val exact=!brandMismatch&&!accessory&&q.brand.isNotBlank()&&q.brand==t.brand&&q.family.isNotBlank()&&tx.contains(q.family)&&modelSatisfied;val similar=!accessory&&!exact&&!brandMismatch&&score>=24;val tier=when{exact->MatchTier.EXACT;similar->MatchTier.SIMILAR;else->MatchTier.REJECTED};if(brandMismatch)r+="Different brand";if(accessory)r+="Part/accessory";if(q.modelTokens.isNotEmpty()&&!modelSatisfied)r+="Model mismatch";return Triple(tier,score,r.distinct().joinToString(" + "))}'''

new_classify = '''private fun classify(query:String,title:String):Triple<MatchTier,Int,String>{val q=features(query);val t=features(title);val tx=norm(title);val compact=tx.replace(" ","");var score=0;val r=mutableListOf<String>();val brandMatched=q.brand.isNotBlank()&&q.brand==t.brand;val brandMismatch=q.brand.isNotBlank()&&t.brand.isNotBlank()&&q.brand!=t.brand;val familyMatched=q.family.isNotBlank()&&tx.contains(q.family);val cpuMatched=q.cpu.isNotBlank()&&tx.contains(norm(q.cpu));val gpuMatched=q.gpu.isNotBlank()&&tx.contains(norm(q.gpu));if(brandMatched){score+=30;r+="Brand"};if(familyMatched){score+=28;r+="Family"};val hits=q.modelTokens.count{compact.contains(it.replace(" ",""))||tx.contains(Regex("\\b${Regex.escape(it)}\\b"))};if(hits>0){score+=minOf(32,hits*16);r+="Model"};if(cpuMatched){score+=14;r+="CPU"};if(gpuMatched){score+=14;r+="GPU"};if(q.ram.isNotBlank()&&tx.contains(Regex("\\b${q.ram}\\s*gb\\b"))){score+=5;r+="RAM"};if(q.storage.isNotBlank()&&tx.contains(norm(q.storage))){score+=5;r+="Storage"};score=score.coerceAtMost(100);val accessory=Regex("\\b(cable|adapter|charger|battery|keyboard|mouse|case|cover|stand|webcam|module|ssd|ram kit|memory|motherboard|heatsink|fan|screen|display|replacement|part|parts|bezel|hinge|dock|docking|power supply|psu|box only|empty box|for parts|faulty|repair)\\b").containsMatchIn(tx);val qGen=Regex("\\bgen(?:eration)?\\s*(\\d+)\\b").find(norm(query))?.groupValues?.get(1).orEmpty();val tGen=Regex("\\bgen(?:eration)?\\s*(\\d+)\\b").find(tx)?.groupValues?.get(1).orEmpty();val generationMismatch=qGen.isNotBlank()&&tGen.isNotBlank()&&qGen!=tGen;val requiredHits=when{q.modelTokens.isEmpty()->0;q.modelTokens.size<=2->1;else->(q.modelTokens.size+1)/2};val modelSatisfied=q.modelTokens.isEmpty()||hits>=requiredHits;val specificIdentity=when{q.modelTokens.isNotEmpty()->modelSatisfied;q.cpu.isNotBlank()||q.gpu.isNotBlank()->cpuMatched||gpuMatched;else->false};val exact=!brandMismatch&&!accessory&&!generationMismatch&&brandMatched&&familyMatched&&specificIdentity;val similar=!accessory&&!generationMismatch&&!exact&&!brandMismatch&&score>=24;val tier=when{exact->MatchTier.EXACT;similar->MatchTier.SIMILAR;else->MatchTier.REJECTED};if(brandMismatch)r+="Different brand";if(accessory)r+="Part/accessory";if(generationMismatch)r+="Generation mismatch";if(q.modelTokens.isNotEmpty()&&!modelSatisfied)r+="Model mismatch";if(!specificIdentity)r+="Insufficient model identity";return Triple(tier,score,r.distinct().joinToString(" + "))}'''

changed = False
if old_features in text:
    text = text.replace(old_features, new_features)
    changed = True
elif new_features not in text:
    raise SystemExit('Could not locate core feature extractor')

if old_classify in text:
    text = text.replace(old_classify, new_classify)
    changed = True
elif new_classify not in text:
    raise SystemExit('Could not locate core exact matcher')

if changed:
    main.write_text(text, encoding='utf-8')
    print('Applied safer exact-model matching to eBay/Google pricing')
else:
    print('Core exact-model matching already improved')
