import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { parseCashConverters, parseGumtree } from "./parser.mjs";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(['https://buyshub.me','https://www.buyshub.me','https://beaustwrt248-netizen.github.io']);
const CASH_BASE='https://www.cashconverters.com.au/search-results?Sort=default&page=1&query=&f%5Bcategory%5D%5B0%5D=all&f%5Bstores%5D%5BWA%5D%5B0%5D=Morley';
const GUMTREE_BASE='https://www.gumtree.com.au/web/s-user/7667200309546';
const clean=(v:unknown,n=500)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,n);
function headers(req:Request){const o=req.headers.get('Origin')||'';return {'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://buyshub.me','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'}}
async function caller(req:Request){if(!SUPABASE_URL||!SERVICE_ROLE)return{error:'Marketplace reconciliation source unavailable',status:503} as const;const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return{error:'Authentication required',status:401} as const;const{data:{user},error}=await admin.auth.getUser(token);if(error||!user)return{error:'Invalid session',status:401} as const;const{data:p,error:pe}=await admin.from('profiles').select('role,is_enabled').eq('id',user.id).maybeSingle();if(pe)throw pe;if(!p?.is_enabled||p.role!=='admin')return{error:'Admin access required',status:403} as const;return{user} as const}
async function fetchHtml(url:string){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(url,{headers:{'Accept':'text/html,application/xhtml+xml','Accept-Language':'en-AU,en;q=0.9','User-Agent':'Mozilla/5.0 (compatible; Morley-Reconciliation/1.0; +https://buyshub.me)'},redirect:'follow',signal:controller.signal});const final=new URL(r.url),requested=new URL(url);if(final.protocol!=='https:'||final.hostname!==requested.hostname)throw new Error(`Unexpected redirect host for ${requested.hostname}`);if(!r.ok)throw new Error(`${requested.hostname} HTTP ${r.status}`);const html=await r.text();if(html.length<500)throw new Error(`${requested.hostname} returned incomplete HTML`);return html}finally{clearTimeout(timer)}}
function sameAllowedPage(url:string,kind:'cash'|'gumtree'){try{const u=new URL(url),base=new URL(kind==='cash'?CASH_BASE:GUMTREE_BASE);if(u.protocol!=='https:'||u.hostname!==base.hostname)return false;if(kind==='gumtree'&&!u.pathname.startsWith('/web/s-user/7667200309546'))return false;if(kind==='cash'&&!u.pathname.startsWith('/search-results'))return false;return true}catch{return false}}
async function crawl(kind:'cash'|'gumtree',base:string){const parse=kind==='cash'?parseCashConverters:parseGumtree;let url=base,total:number|null=null;const rows:any[]=[],seenUrls=new Set<string>(),visited=new Set<string>();for(let page=0;page<100;page++){if(visited.has(url)||!sameAllowedPage(url,kind))break;visited.add(url);const parsed=parse(await fetchHtml(url),url);if(Number.isSafeInteger(parsed.total)&&Number(parsed.total)>=0)total=Number(parsed.total);for(const row of parsed.rows){if(!seenUrls.has(row.url)){seenUrls.add(row.url);rows.push(row)}}if(total!==null&&rows.length>=total)break;if(!parsed.next||!sameAllowedPage(parsed.next,kind))break;url=parsed.next}return{rows,total,exact:total!==null&&rows.length===total,pages:visited.size}}
Deno.serve(async req=>{const h=headers(req),reply=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:h});if(req.method==='OPTIONS')return new Response('ok',{headers:h});if(req.method!=='POST')return reply({error:'POST required'},405);try{const c=await caller(req);if('error'in c)return reply({error:c.error},c.status);let body:any={};try{body=await req.json()}catch{return reply({error:'Invalid JSON request'},400)}if(clean(body.action,40).toLowerCase()!=='snapshot')return reply({error:'Unsupported action'},400);const checkedAt=new Date().toISOString();const [cr,gr]=await Promise.allSettled([crawl('cash',CASH_BASE),crawl('gumtree',GUMTREE_BASE)]);const cash=cr.status==='fulfilled'?cr.value:null,gumtree=gr.status==='fulfilled'?gr.value:null;const cashError=cr.status==='rejected'?clean(cr.reason instanceof Error?cr.reason.message:cr.reason):null,gumtreeError=gr.status==='rejected'?clean(gr.reason instanceof Error?gr.reason.message:gr.reason):null;const confirmed=!!cash?.exact&&!!gumtree?.exact&&cash.rows.length>0;return reply({ok:true,state:confirmed?'confirmed':'unavailable',checked_at:checkedAt,source_urls:{cash_converters:CASH_BASE,gumtree:GUMTREE_BASE},stock:confirmed?cash!.rows.map(x=>({...x,checked_at:checkedAt})):[],listings:confirmed?gumtree!.rows.map(x=>({...x,checked_at:checkedAt})):[],source_health:{cash_converters:{state:cash?.exact?'confirmed':cash?'partial':'unavailable',rows:cash?.rows.length||0,total:cash?.total??null,pages:cash?.pages||0,error:cashError},gumtree:{state:gumtree?.exact?'confirmed':gumtree?'partial':'unavailable',rows:gumtree?.rows.length||0,total:gumtree?.total??null,pages:gumtree?.pages||0,error:gumtreeError}},authoritative:confirmed,note:confirmed?'Both fixed sources returned complete explicit listing evidence.':'Reconciliation is unavailable until both fixed sources expose a complete count-matched listing snapshot. No empty/partial source is treated as zero listings.'})}catch(e){const m=e instanceof Error?e.message:clean(e)||'Marketplace reconciliation source error';console.error('[marketplace-reconciliation-source]',m);return reply({error:m,state:'unavailable'},500)}});
