const decode=s=>String(s||'').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ');
const text=s=>decode(String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());
const money=s=>{const m=String(s||'').match(/(?:A\$|AUD\s*\$?|\$)\s*([0-9][0-9,]*(?:\.[0-9]{1,2})?)/i);if(!m)return null;const n=Number(m[1].replace(/,/g,''));return Number.isFinite(n)&&n>=0?n:null};
const stock=s=>{const m=String(s||'').match(/(?:stock|item)(?:\s*(?:no\.?|number|#))?\s*[:#-]?\s*(\d{5,12})/i);return m?m[1]:null};
function absolute(href,base){try{return new URL(decode(href),base).href}catch{return null}}
function total(html){const raw=String(html||'');for(const re of [/"total(?:Results|Count|Listings|Items)"\s*:\s*(\d{1,7})/i,/"active(?:Listings|Ads)"\s*:\s*(\d{1,7})/i,/\b(\d{1,7})\s+(?:active\s+)?(?:listings|ads|results|items)\b/i]){const m=raw.match(re);if(m){const n=Number(m[1]);if(Number.isSafeInteger(n)&&n>=0)return n}}return null}
function anchors(html,base,kind){const out=[],raw=String(html||''),re=/<a\b([^>]*?)href=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(raw))){const href=absolute(m[2],base);if(!href)continue;let ok=false;try{const u=new URL(href);ok=kind==='cash'?(u.hostname.endsWith('cashconverters.com.au')&&/\/shop\//i.test(u.pathname)):(u.hostname.endsWith('gumtree.com.au')&&/\/s-ad\//i.test(u.pathname))}catch{}if(!ok)continue;const attrs=`${m[1]} ${m[3]}`,body=m[4],around=text(raw.slice(Math.max(0,m.index-900),Math.min(raw.length,re.lastIndex+1400)));const title=text((attrs.match(/(?:aria-label|title)=["']([^"']+)["']/i)||[])[1]||body)||null;const explicit=kind==='cash'?(attrs.match(/data-(?:item|stock)-(?:number|id)=["'](\d{5,12})["']/i)||[])[1]:null;out.push({url:href,title,description:kind==='gumtree'?around.slice(0,1200)||null:null,price:money(around),stockNumber:explicit||stock(around)||null})}return out}
function dedupe(rows){const seen=new Set;return rows.filter(r=>{if(!r.url||seen.has(r.url))return false;seen.add(r.url);return true})}
function nextPage(html,base,kind){const host=kind==='cash'?'cashconverters.com.au':'gumtree.com.au';for(const re of [/<a\b[^>]*rel=["']next["'][^>]*href=["']([^"']+)["']/i,/<a\b[^>]*href=["']([^"']+)["'][^>]*aria-label=["'][^"']*next[^"']*["']/i]){const m=String(html||'').match(re);if(!m)continue;const url=absolute(m[1],base);try{const u=new URL(url);if(u.protocol==='https:'&&(u.hostname===host||u.hostname.endsWith('.'+host)))return u.href}catch{}}return null}
export function parseCashConverters(html,url){return {rows:dedupe(anchors(html,url,'cash')).filter(r=>r.stockNumber),total:total(html),next:nextPage(html,url,'cash')}}
export function parseGumtree(html,url){return {rows:dedupe(anchors(html,url,'gumtree')),total:total(html),next:nextPage(html,url,'gumtree')}}
export const helpers=Object.freeze({text,money,stock,total});
