package com.buysloans.hub

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.text.NumberFormat
import java.util.Locale

private const val API="https://ghdhairijqjqivqriigi.supabase.co/functions/v1/ebay-search"
private val Yellow=Color(0xFFFFD400); private val Bg=Color(0xFF111111); private val Card=Color(0xFF222222)
class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);window.statusBarColor=android.graphics.Color.rgb(17,17,17);window.navigationBarColor=android.graphics.Color.rgb(17,17,17);setContent{App()}}}
enum class Page(val label:String,val icon:String){Home("Home","⌂"),Laptop("Laptop","💻"),Desktop("Desktop","🖥"),GP("GP","$"),More("More","⚙")}
enum class MatchTier{EXACT,SIMILAR,REJECTED}
data class Features(val brand:String="",val family:String="",val cpu:String="",val gpu:String="",val ram:String="",val storage:String="",val modelTokens:List<String> = emptyList())
data class Listing(val title:String,val price:Double,val source:String,val url:String,val condition:String,val tier:MatchTier,val score:Int,val reasons:String)
data class ComponentValue(val label:String,val query:String,val value:Double,val evidence:List<Listing>)
data class MarketResult(val exactGoogle:List<Listing>,val exactEbay:List<Listing>,val similarGoogle:List<Listing>,val similarEbay:List<Listing>,val rejected:List<Listing>,val components:List<ComponentValue> = emptyList())
private val brands=listOf("apple","lenovo","dell","hp","acer","asus","msi","alienware","gigabyte","razer","microsoft","thermaltake","corsair")
private val families=listOf("mpg trident as","trident as","trident","macbook pro","macbook air","thinkcentre","thinkstation","thinkpad","optiplex","precision","elitedesk","prodesk","legion","loq","omen","victus","predator","nitro","tuf","rog","zephyrus","vivobook","zenbook","inspiron","latitude","xps","aegis","infinite","codex","surface laptop")
private fun norm(s:String)=s.lowercase().replace(Regex("[^a-z0-9]+")," ").replace(Regex("\\s+")," ").trim()
private fun features(s:String):Features{val x=norm(s);val brand=brands.firstOrNull{x.contains(Regex("\\b${Regex.escape(it)}\\b"))}.orEmpty();val family=families.firstOrNull{x.contains(it)}.orEmpty();val cpu=Regex("\\b(?:i[3579][ -]?)?(\\d{4,5}[a-z]{0,3})\\b").find(x)?.groupValues?.get(1).orEmpty();val gpu=Regex("\\b((?:rtx|gtx|rx|arc)\\s*\\d{3,4}(?:\\s*(?:ti|super|xt|xtx))?)\\b").find(x)?.groupValues?.get(1).orEmpty();val ram=Regex("\\b(8|12|16|18|24|32|36|48|64|96|128)\\s*gb\\b").find(x)?.groupValues?.get(1).orEmpty();val storage=Regex("\\b(?:128|256|512)\\s*gb\\b|\\b(?:1|2|4|8)\\s*tb\\b").find(x)?.value.orEmpty();val tokens=x.split(" ").filter{it.length>=4&&it.any(Char::isLetter)&&it.any(Char::isDigit)&&it!=cpu};return Features(brand,family,cpu,gpu,ram,storage,tokens)}
private fun classify(query:String,title:String):Triple<MatchTier,Int,String>{val q=features(query);val t=features(title);val tx=norm(title);var score=0;val r=mutableListOf<String>();val brandMismatch=q.brand.isNotBlank()&&t.brand.isNotBlank()&&q.brand!=t.brand;if(q.brand.isNotBlank()&&q.brand==t.brand){score+=30;r+="Brand"};if(q.family.isNotBlank()&&tx.contains(q.family)){score+=40;r+="Exact family"};val hits=q.modelTokens.count{tx.contains(Regex("\\b${Regex.escape(it)}\\b"))};if(hits>0){score+=minOf(18,hits*9);r+="Model"};if(q.cpu.isNotBlank()&&tx.contains(Regex("\\b${Regex.escape(q.cpu)}\\b"))){score+=14;r+="CPU"};if(q.gpu.isNotBlank()&&tx.contains(norm(q.gpu))){score+=14;r+="GPU"};if(q.ram.isNotBlank()&&tx.contains(Regex("\\b${q.ram}\\s*gb\\b"))){score+=5;r+="RAM"};if(q.storage.isNotBlank()&&tx.contains(norm(q.storage))){score+=5;r+="Storage"};score=score.coerceAtMost(100);val accessory=Regex("\\b(cable|adapter|charger|battery|keyboard|mouse|case|cover|stand|webcam|module|ssd|ram kit|memory|motherboard|heatsink|fan|screen|display|replacement|part|parts)\\b").containsMatchIn(tx);val exact=!brandMismatch&&!accessory&&q.brand.isNotBlank()&&q.brand==t.brand&&((q.family.isNotBlank()&&tx.contains(q.family))||(q.modelTokens.isNotEmpty()&&hits==q.modelTokens.size));val similar=!accessory&&!exact&&score>=18;val tier=when{exact->MatchTier.EXACT;similar->MatchTier.SIMILAR;else->MatchTier.REJECTED};if(brandMismatch)r+="Different brand";if(accessory)r+="Part/accessory";return Triple(tier,score,r.distinct().joinToString(" + "))}
private fun median(v:List<Double>):Double{val s=v.filter{it>0}.sorted();if(s.isEmpty())return 0.0;val m=s.size/2;return if(s.size%2==1)s[m] else (s[m-1]+s[m])/2}
private fun money(v:Double)=NumberFormat.getCurrencyInstance(Locale("en","AU")).apply{maximumFractionDigits=0}.format(v)
@Composable fun App(){var page by remember{mutableStateOf(Page.Home)};MaterialTheme(colorScheme=darkColorScheme(primary=Yellow,background=Bg,surface=Card)){Scaffold(containerColor=Bg,bottomBar={NavigationBar(containerColor=Color(0xFF101010)){Page.entries.forEach{p->NavigationBarItem(selected=page==p,onClick={page=p},icon={Text(p.icon,fontSize=20.sp)},label={Text(p.label)},colors=NavigationBarItemDefaults.colors(indicatorColor=Yellow.copy(alpha=.25f),selectedTextColor=Yellow))}}}){pad->Box(Modifier.padding(pad).fillMaxSize()){when(page){Page.Home->Home({page=Page.Laptop},{page=Page.Desktop},{page=Page.GP});Page.Laptop->Laptop();Page.Desktop->Desktop();Page.GP->GP();Page.More->More()}}}}}
@Composable fun Screen(title:String,body:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("B&L Morley",fontSize=28.sp,fontWeight=FontWeight.Black);Text(title,fontSize=24.sp,fontWeight=FontWeight.Bold,color=Yellow);body();Spacer(Modifier.height(16.dp))}}
@Composable fun Home(l:()->Unit,d:()->Unit,g:()->Unit)=Screen("Native valuation workspace"){Block("WELCOME","Live valuation and buying targets in a native Android interface.");Btn("💻 Laptop / MacBook",l);Btn("🖥 Desktop / Gaming PC",d);Btn("$ GP Calculator",g);Block("ONLINE PRICING","Direct live-pricing API access with client-side OEM verification.")}
@Composable fun Laptop()=Screen("💻 Laptop / MacBook"){var q by remember{mutableStateOf("")};var ask by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)};var result by remember{mutableStateOf<MarketResult?>(null)};var status by remember{mutableStateOf("Ready")};val scope=rememberCoroutineScope();Field("Exact model / clean search",q,{q=it});Field("Seller asking price",ask,{ask=it},true);Btn(if(busy)"Searching…" else "Analyse Laptop",{busy=true;scope.launch{runCatching{market(q)}.onSuccess{result=it;status=summary(it)}.onFailure{status=it.message?:"Search failed"};busy=false}},!busy&&q.isNotBlank());Text(status,color=Color.LightGray);result?.let{Valuation(it,ask,0.30,0.58)}}
@Composable fun Desktop()=Screen("🖥 Desktop / Gaming PC"){var q by remember{mutableStateOf("")};var ask by remember{mutableStateOf("")};var gp by remember{mutableStateOf("30")};var busy by remember{mutableStateOf(false)};var result by remember{mutableStateOf<MarketResult?>(null)};var status by remember{mutableStateOf("Paste full OEM model/specs")};val scope=rememberCoroutineScope();Field("Seller asking price",ask,{ask=it},true);Field("Target gross profit %",gp,{gp=it},true);Field("Paste PC specs",q,{q=it});Btn(if(busy)"Searching…" else "Detect + Price All",{busy=true;scope.launch{runCatching{market(q)}.onSuccess{result=it;status=summary(it)}.onFailure{status=it.message?:"Search failed"};busy=false}},!busy&&q.isNotBlank());Text(status,color=Color.LightGray);result?.let{Valuation(it,ask,(gp.toDoubleOrNull()?:30.0)/100.0,0.65)}}
private fun summary(r:MarketResult)="${r.exactGoogle.size+r.exactEbay.size} exact • ${r.similarGoogle.size+r.similarEbay.size} similar • ${r.components.count{it.value>0}} components • ${r.rejected.size} rejected"
@Composable fun Valuation(r:MarketResult,ask:String,gp:Double,estimateRate:Double){val exactNew=median(r.exactGoogle.map{it.price});val exactUsed=median(r.exactEbay.map{it.price});val exactEvidence=r.exactGoogle.isNotEmpty()||r.exactEbay.isNotEmpty();val used=when{exactUsed>0->exactUsed;exactNew>0->exactNew*estimateRate;else->0.0};val componentEstimate=r.components.sumOf{it.value};val primary=if(exactEvidence)used else componentEstimate;val max=if(primary>0)primary*(1-gp) else 0.0;val a=ask.toDoubleOrNull()?:0.0;if(exactEvidence&&used>0){Metrics(listOf("NEW RETAIL" to exactNew,"USED VALUE" to used,"MAX BUY" to max,"AVERAGE RESULT" to used));Verdict(if(a<=0)"PRICE READY" else if(a<=max)"BUY" else if(a<=max*1.1)"NEGOTIATE" else "PASS")}else{Block("EXACT MARKET VALUE UNAVAILABLE","No verified exact-brand/model listing was found. A conservative component fallback is used only when CPU/GPU/RAM/storage evidence can be independently validated.");if(componentEstimate>0){Metrics(listOf("COMPONENT ESTIMATE" to componentEstimate,"COMPONENT MAX BUY" to max));ComponentBreakdown(r.components);Verdict(if(a<=0)"LOW CONFIDENCE" else if(a<=max)"BUY — LOW CONFIDENCE" else if(a<=max*1.1)"NEGOTIATE — LOW CONFIDENCE" else "PASS — LOW CONFIDENCE")}else Verdict("LOW CONFIDENCE")};Confidence(r);Evidence(r)}
@Composable fun ComponentBreakdown(items:List<ComponentValue>){Text("Component valuation breakdown",fontSize=21.sp,fontWeight=FontWeight.Black);items.forEach{x->Block(x.label,"${if(x.value>0)money(x.value) else "No validated value"} • ${x.evidence.size} matched result${if(x.evidence.size==1)"" else "s"}\nSearch: ${x.query}")}}
@Composable fun Confidence(r:MarketResult){val exact=r.exactGoogle.size+r.exactEbay.size;val similar=r.similarGoogle.size+r.similarEbay.size;val componentCount=r.components.count{it.value>0};val label=when{exact>=2->"HIGH";exact==1->"MEDIUM";componentCount>=3->"LOW — COMPONENT BASED";similar>0||componentCount>0->"LOW";else->"UNAVAILABLE"};Block("MATCH QUALITY","Exact matches: $exact\nSimilar/spec matches: $similar\nValidated components: $componentCount/${r.components.size}\nRejected results: ${r.rejected.size}\nConfidence: $label")}
@Composable fun Evidence(r:MarketResult){Section("Exact eBay AU used comparables",r.exactEbay,"No exact used listings found.");Section("Exact Google Shopping AU new offers",r.exactGoogle,"No exact new listings found.");if(r.components.any{it.evidence.isNotEmpty()}){Text("Validated component evidence — fallback only",fontSize=21.sp,fontWeight=FontWeight.Black);r.components.filter{it.evidence.isNotEmpty()}.forEach{x->Section(x.label,x.evidence,"")}};Section("Similar whole-PC results — excluded from valuation",r.similarEbay+r.similarGoogle,"No similar results retained.");if(r.rejected.isNotEmpty())Section("Rejected results — not used",r.rejected.take(8),"")}
@Composable fun Section(title:String,items:List<Listing>,empty:String){Text(title,fontSize=21.sp,fontWeight=FontWeight.Black);if(items.isEmpty()&&empty.isNotBlank())Text(empty,color=Color.LightGray) else items.take(12).forEach{ListingCard(it)}}
@Composable fun ListingCard(x:Listing){val c=LocalContext.current;Card(colors=CardDefaults.cardColors(containerColor=Color(0xFF1B1B1B)),shape=RoundedCornerShape(18.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(money(x.price),fontSize=20.sp,fontWeight=FontWeight.Black);if(x.url.isNotBlank())TextButton(onClick={runCatching{c.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(x.url)))}}){Text("Open")}};Text(x.title,color=Color(0xFFE2E2E2));if(x.source.isNotBlank())Text(x.source,color=Color.Gray);Surface(color=Color(0xFF171717),shape=RoundedCornerShape(999.dp),border=BorderStroke(1.dp,when(x.tier){MatchTier.EXACT->Color(0xFF57E389);MatchTier.SIMILAR->Yellow;MatchTier.REJECTED->Color(0xFFFF6B6B)})){Text("${x.tier.name} • ${x.score}%${if(x.reasons.isNotBlank())" • ${x.reasons}" else ""}",Modifier.padding(horizontal=10.dp,vertical=6.dp),fontSize=11.sp,fontWeight=FontWeight.Bold)}}}}
@Composable fun GP()=Screen("$ GP Calculator"){var sale by remember{mutableStateOf("")};var gp by remember{mutableStateOf("30")};val s=sale.toDoubleOrNull()?:0.0;val p=gp.toDoubleOrNull()?:30.0;Metrics(listOf("SALE PRICE" to s,"MAX COST" to s*(1-p/100),"TARGET PROFIT" to s*p/100));Field("Sale price",sale,{sale=it},true);Field("Target GP %",gp,{gp=it},true)}
@Composable fun More()=Screen("⚙ More"){val context=LocalContext.current;val scope=rememberCoroutineScope();var checking by remember{mutableStateOf(false)};var status by remember{mutableStateOf("Automatic update checks are ready.")};var update by remember{mutableStateOf<AppUpdate?>(null)};Block("B&L MORLEY","Native Android v${BuildConfig.VERSION_NAME}");Block("VALUATION SAFETY","Primary prices require verified OEM/model matches. Similar and wrong-brand whole-PC results cannot drive Max Buy. Component fallback requires independently validated part matches.");Block("OTA UPDATES",status);Btn(if(checking)"Checking…" else "Check for Updates",{checking=true;scope.launch{runCatching{UpdateManager.check()}.onSuccess{u->update=u;status=if(u==null)"You're up to date." else "${u.versionName} is available. ${u.notes}"}.onFailure{status="Update check failed: ${it.message?:"network error"}"};checking=false}},!checking);update?.let{Btn("Download ${it.versionName}",{if(android.os.Build.VERSION.SDK_INT>=26&&!context.packageManager.canRequestPackageInstalls())UpdateManager.openInstallerPermission(context) else UpdateManager.openDownload(context,it)})}}
@Composable fun Field(label:String,v:String,set:(String)->Unit,single:Boolean=false){OutlinedTextField(v,set,label={Text(label)},modifier=Modifier.fillMaxWidth(),singleLine=single,colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=Yellow,focusedLabelColor=Yellow))}
@Composable fun Btn(text:String,click:()->Unit,enabled:Boolean=true){Button(click,modifier=Modifier.fillMaxWidth().height(56.dp),enabled=enabled,colors=ButtonDefaults.buttonColors(containerColor=Yellow,contentColor=Color.Black),shape=RoundedCornerShape(16.dp)){Text(text,fontWeight=FontWeight.Black,fontSize=17.sp)}}
@Composable fun Block(title:String,body:String){Card(colors=CardDefaults.cardColors(containerColor=Card),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(title,color=Yellow,fontWeight=FontWeight.Black);Text(body,color=Color(0xFFD0D0D0),lineHeight=22.sp)}}}
@Composable fun Verdict(v:String){Card(colors=CardDefaults.cardColors(containerColor=Card),modifier=Modifier.fillMaxWidth()){Text(v,Modifier.padding(18.dp),color=when{v.startsWith("BUY")->Color(0xFF57E389);v.startsWith("PASS")->Color(0xFFFF6B6B);v.contains("LOW CONFIDENCE")->Color(0xFFFFA726);else->Yellow},fontSize=25.sp,fontWeight=FontWeight.Black)}}
@Composable fun Metrics(items:List<Pair<String,Double>>){Column(verticalArrangement=Arrangement.spacedBy(10.dp)){items.chunked(2).forEach{row->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){row.forEach{(k,v)->Card(colors=CardDefaults.cardColors(containerColor=Card),modifier=Modifier.weight(1f)){Column(Modifier.padding(16.dp)){Text(k,color=Color.Gray,fontSize=11.sp,fontWeight=FontWeight.Bold);Text(if(v>0)money(v) else "—",fontSize=23.sp,fontWeight=FontWeight.Black)}}};if(row.size==1)Spacer(Modifier.weight(1f))}}}}
private fun parse(obj:JSONObject?,query:String):List<Listing>{if(obj==null)return emptyList();val a=obj.optJSONArray("items")?:JSONArray();val out=mutableListOf<Listing>();for(i in 0 until a.length()){val x=a.optJSONObject(i)?:continue;val title=x.optString("title",x.optString("name","Untitled result"));val p=listOf("deliveredPrice","price","itemPrice").asSequence().map{x.optDouble(it,0.0)}.firstOrNull{it>0}?:0.0;val(tier,score,reasons)=classify(query,title);out+=Listing(title,p,x.optString("seller",x.optString("store",x.optString("source",x.optString("merchant","")))),x.optString("url",x.optString("link",x.optString("itemWebUrl",""))),x.optString("condition",""),tier,score,reasons)};return out}
private fun rawListings(obj:JSONObject?):List<Listing>{if(obj==null)return emptyList();val a=obj.optJSONArray("items")?:JSONArray();val out=mutableListOf<Listing>();for(i in 0 until a.length()){val x=a.optJSONObject(i)?:continue;val p=listOf("deliveredPrice","price","itemPrice").asSequence().map{x.optDouble(it,0.0)}.firstOrNull{it>0}?:0.0;if(p<=0)continue;out+=Listing(x.optString("title",x.optString("name","Untitled result")),p,x.optString("seller",x.optString("store",x.optString("source",x.optString("merchant","")))),x.optString("url",x.optString("link",x.optString("itemWebUrl",""))),x.optString("condition",""),MatchTier.SIMILAR,100,"Component match")};return out}
private suspend fun request(query:String,limit:Int=40):JSONObject=withContext(Dispatchers.IO){val c=(URL(API).openConnection() as HttpURLConnection).apply{requestMethod="POST";connectTimeout=15000;readTimeout=20000;doOutput=true;setRequestProperty("Content-Type","application/json")};val body=JSONObject().put("query",query).put("limit",limit).put("australiaOnly",true).put("mode","device").toString();c.outputStream.use{it.write(body.toByteArray())};val code=c.responseCode;val text=(if(code in 200..299)c.inputStream else c.errorStream).bufferedReader().use{it.readText()};val root=JSONObject(text);if(code !in 200..299||!root.optBoolean("success"))throw IllegalStateException(root.optString("error","HTTP $code"));root}
private fun componentMatch(label:String,needle:String,x:Listing):Boolean{val t=norm(x.title);val n=norm(needle);val bad=Regex("\\b(wanted|box only|empty box|manual|sticker|decal|backplate|waterblock|heatsink|cooler|fan only|cable|adapter|bracket|for parts|faulty|repair)\\b").containsMatchIn(t);if(bad)return false;return when(label){"CPU"->t.contains(Regex("\\b${Regex.escape(n)}\\b"))&&!Regex("\\b(desktop pc|gaming pc|laptop|computer system|workstation)\\b").containsMatchIn(t);"GPU"->t.contains(n)&&!Regex("\\b(desktop pc|gaming pc|laptop|computer system|workstation)\\b").containsMatchIn(t);"RAM"->t.contains(Regex("\\b${Regex.escape(n)}\\s*gb\\b"))&&Regex("\\b(ram|memory|ddr[345])\\b").containsMatchIn(t);"STORAGE"->t.contains(n)&&Regex("\\b(ssd|nvme|solid state|m 2)\\b").containsMatchIn(t);else->false}}
private suspend fun componentValue(label:String,needle:String,search:String):ComponentValue{if(needle.isBlank())return ComponentValue(label,search,0.0,emptyList());return runCatching{val root=request(search,24);val all=rawListings(root.optJSONObject("ebay"))+rawListings(root.optJSONObject("google"));val good=all.filter{componentMatch(label,needle,it)}.sortedBy{it.price}.let{xs->if(xs.size>=5)xs.drop(1).dropLast(1) else xs}.take(8);ComponentValue(label,search,median(good.map{it.price}),good)}.getOrElse{ComponentValue(label,search,0.0,emptyList())}}
private suspend fun components(query:String): List<ComponentValue> = coroutineScope{val f=features(query);listOf(async{componentValue("CPU",f.cpu,if(f.cpu.isBlank())"CPU not detected" else "${f.cpu} processor")},async{componentValue("GPU",f.gpu,if(f.gpu.isBlank())"GPU not detected" else "${f.gpu} graphics card")},async{componentValue("RAM",f.ram,if(f.ram.isBlank())"RAM not detected" else "${f.ram}GB DDR RAM kit")},async{componentValue("STORAGE",f.storage,if(f.storage.isBlank())"Storage not detected" else "${f.storage} SSD NVMe")}).awaitAll()}
private suspend fun market(query:String):MarketResult=coroutineScope{val device=async{request(query)};val comp=async{components(query)};val root=device.await();val g=parse(root.optJSONObject("google"),query);val e=parse(root.optJSONObject("ebay"),query);val eg=g.filter{it.tier==MatchTier.EXACT};val ee=e.filter{it.tier==MatchTier.EXACT};val sg=g.filter{it.tier==MatchTier.SIMILAR};val se=e.filter{it.tier==MatchTier.SIMILAR};val rej=(g+e).filter{it.tier==MatchTier.REJECTED};MarketResult(eg,ee,sg,se,rej,comp.await())}
