package com.buysloans.hub

data class MobilePhoneDeviceEntry(val brand:String,val model:String,val modelNumber:String?,val storage:String,val priceSheetValue:Double?){val hasPrice:Boolean get()=priceSheetValue!=null||LiveDevicePricing.find(brand,model,modelNumber,storage)!=null}
data class MobilePhoneSearchResult(val brand:String,val model:String,val modelNumber:String?,val storages:List<String>,val hasPricedVariant:Boolean)
object MobilePhoneDeviceCatalog {
 private fun key(brand:String,model:String,storage:String)=listOf(brand.trim().lowercase(),model.trim().lowercase(),storage.replace(" ","").lowercase()).joinToString("|")
 val entries:List<MobilePhoneDeviceEntry> by lazy {val imported=ImportedMobilePhoneCatalog.models.flatMap{m->m.storages.map{s->MobilePhoneDeviceEntry(m.brand,m.model,m.modelNumber,s,null)}};val expanded=ExpandedMobilePhoneCatalog.models.flatMap{m->m.storages.map{s->MobilePhoneDeviceEntry(m.brand,m.model,m.modelNumber,s,null)}};val additive=(imported+expanded).distinctBy{key(it.brand,it.model,it.storage)};val byKey=additive.associateBy{key(it.brand,it.model,it.storage)};val existingKeys=mutableSetOf<String>();val existing=MobilePhonePricingCatalog.entries.map{p->val k=key(p.brand,p.model,p.storage);existingKeys+=k;val source=byKey[k];MobilePhoneDeviceEntry(p.brand,p.model,source?.modelNumber,p.storage,p.priceSheetValue)};existing+additive.filter{key(it.brand,it.model,it.storage)!in existingKeys}}
 val brandOrder=listOf("Apple","Samsung","Google","OnePlus","Xiaomi","OPPO","Nothing","Motorola","Vivo","Realme","Huawei","HONOR","ASUS","HMD","Nokia","Fairphone","Meizu","Lenovo","Sony","ZTE / nubia","TCL")
 fun brands():List<String>{val a=entries.map{it.brand}.toSet();return brandOrder.filter{it in a}+a.filter{it !in brandOrder}.sorted()}
 private fun generation(model:String):Int{val patterns=listOf(Regex("(?i)iphone\\s+(\\d+)"),Regex("(?i)galaxy\\s+s(\\d+)"),Regex("(?i)galaxy\\s+z\\s+(?:fold|flip)\\s*(\\d+)"),Regex("(?i)galaxy\\s+a(\\d+)"),Regex("(?i)pixel\\s+(\\d+)"),Regex("(?i)oneplus\\s+(\\d+)"),Regex("(?i)find\\s+x(\\d+)"),Regex("(?i)reno\\s*(\\d+)"),Regex("(?i)xiaomi\\s+(\\d+)"),Regex("(?i)fairphone\\s+(\\d+)"));return patterns.firstNotNullOfOrNull{it.find(model)?.groupValues?.getOrNull(1)?.toIntOrNull()}?:Regex("\\d+").find(model)?.value?.toIntOrNull()?:0}
 private fun variantRank(model:String):Int{val v=model.lowercase();return when{"pro max" in v||"ultra" in v->0;"pro" in v->1;"plus" in v->2;"air" in v->3;"edge" in v->4;"fe" in v->5;"mini" in v->6;else->7}}
 private val modelComparator=compareByDescending<String>{generation(it)}.thenBy{variantRank(it)}.thenBy{it.lowercase()}
 fun models(brand:String)=entries.asSequence().filter{it.brand==brand}.map{it.model}.distinct().toList().sortedWith(modelComparator)
 fun variants(brand:String,model:String)=entries.filter{it.brand==brand&&it.model==model}
 fun modelMatches(brand:String,model:String,query:String):Boolean{if(query.isBlank())return true;if(brand.contains(query,true)||model.contains(query,true))return true;return variants(brand,model).any{it.modelNumber?.contains(query,true)==true||it.storage.contains(query,true)||it.storage.replace(" ","").contains(query.replace(" ",""),true)}}
 fun search(query:String,limit:Int=80):List<MobilePhoneSearchResult>{val needle=query.trim();if(needle.isBlank())return emptyList();return brands().asSequence().flatMap{b->models(b).asSequence().map{m->b to m}}.filter{(b,m)->modelMatches(b,m,needle)}.map{(b,m)->val v=variants(b,m);MobilePhoneSearchResult(b,m,v.mapNotNull{it.modelNumber}.firstOrNull(),v.map{it.storage}.distinct(),v.any{it.hasPrice})}.take(limit).toList()}
 fun pricedEntry(entry:MobilePhoneDeviceEntry):MobilePhonePriceEntry?{val live=LiveDevicePricing.find(entry.brand,entry.model,entry.modelNumber,entry.storage);if(live!=null)return MobilePhonePriceEntry(entry.brand,entry.model,entry.storage,live.priceAud);return MobilePhonePricingCatalog.entries.firstOrNull{it.brand==entry.brand&&it.model==entry.model&&key(it.brand,it.model,it.storage)==key(entry.brand,entry.model,entry.storage)}}
}
