import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
function reply(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
async function requireAdmin(req:Request){const h=req.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))throw new Error('AUTH_REQUIRED');const token=h.slice(7).trim();const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw new Error('AUTH_REQUIRED');const {data:p,error:pe}=await admin.from('profiles').select('role,is_enabled').eq('id',data.user.id).single();if(pe||!p?.is_enabled)throw new Error('FORBIDDEN');const {data:o}=await admin.from('user_permission_overrides').select('allowed').eq('user_id',data.user.id).eq('capability','recovery.global').maybeSingle();const {data:r}=await admin.from('role_capabilities').select('allowed').eq('role',p.role).eq('capability','recovery.global').maybeSingle();const allowed=o?.allowed??r?.allowed??false;if(!allowed)throw new Error('FORBIDDEN');return data.user}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return reply({error:'Method not allowed'},405);try{await requireAdmin(req);const [{data:audit,error:ae},{data:findings,error:fe},{count:backupCount,error:be}]=await Promise.all([admin.from('admin_audit_log').select('created_at,target_id,details').eq('action','google_drive_backup_created').order('created_at',{ascending:false}).limit(1).maybeSingle(),admin.from('recovery_health_findings').select('kind,severity,status,summary,last_seen_at').eq('status','open').order('last_seen_at',{ascending:false}).limit(50),admin.from('user_drive_backups').select('id',{count:'exact',head:true}).eq('status','ready')]);if(ae)throw ae;if(fe)throw fe;if(be)throw be;return reply({global_backup:{last_success:audit?.created_at||null,file_id:audit?.target_id||null,recovery_test:audit?.details?.recovery_test||null,retention:audit?.details?.retention||null},user_backup_ready_count:backupCount||0,open_findings:findings||[],restore_mode:'human-controlled',automatic_restore:false,guardian_auto_repair:false})}catch(e){const m=e instanceof Error?e.message:String(e);if(m==='AUTH_REQUIRED')return reply({error:'Authentication required'},401);if(m==='FORBIDDEN')return reply({error:'Administrator recovery permission required'},403);console.error('recovery-readiness',m);return reply({error:'Recovery readiness check failed'},500)}});