(()=>{
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
function loadCss(){if(q('#adminV2Css'))return;const l=document.createElement('link');l.id='adminV2Css';l.rel='stylesheet';l.href='admin-v2.css?v=1';document.head.appendChild(l)}
const navMeta={overview:['Overview','⌂'],users:['Accounts','◎'],devices:['Devices','▣'],tickets:['Support','✉'],passwords:['Passwords','✦'],controls:['Controls','⚙'],release:['Release','↑'],notify:['Notify','●'],announce:['News','◈'],audit:['Audit','≡']};
function addPasswordSection(){const nav=q('.tabs');if(!nav||q('[data-tab="passwords"]'))return;const users=q('[data-tab="users"]');const b=document.createElement('button');b.className='tab';b.dataset.tab='passwords';b.textContent='Passwords';users?.insertAdjacentElement('afterend',b);
const sec=document.createElement('section');sec.id='tab-passwords';sec.className='panel hidden';sec.innerHTML=`<div class="admin-page-head"><div><h2>Password reset</h2><p>Issue a one-time temporary password and force the user to change it at next sign-in.</p></div></div><div class="admin-reset-grid"><div class="card"><h2>Reset a user password</h2><p class="muted">Admin-only. The temporary password is shown once and is never written to the audit log.</p><label>User<select id="adminResetUser"><option value="">Choose an account</option></select></label><button id="adminResetBtn">Generate temporary password</button><div id="adminResetStatus" class="status" role="status" aria-live="polite"></div><div id="adminResetResult" class="admin-reset-output hidden"><small>TEMPORARY PASSWORD</small><code id="adminTempPassword"></code><div class="admin-reset-actions"><button id="adminCopyPassword" class="ghost">Copy password</button><button id="adminSharePassword" class="ghost">Share</button></div></div></div><div class="card"><h2>Send by text message</h2><p class="muted">For no SMS API fee, use the phone's normal Messages app. This uses the device/SIM plan rather than a paid SMS gateway.</p><label>Mobile number<input id="adminResetPhone" type="tel" inputmode="tel" placeholder="04xx xxx xxx"></label><button id="adminOpenSms" class="ghost" disabled>Open SMS app</button><div class="admin-security-note" style="margin-top:12px">Fully automatic server-to-phone SMS is not genuinely free: carriers charge providers to deliver SMS. The no-API-cost option is to open the administrator's SMS app with the message prefilled, then tap Send.</div></div></div>`;
const usersPanel=q('#tab-users');usersPanel?.insertAdjacentElement('afterend',sec);
}
function wireTabs(){qa('.tab[data-tab]').forEach(b=>{if(b.dataset.adminV2Bound)return;b.dataset.adminV2Bound='1';b.addEventListener('click',()=>{qa('.tab[data-tab]').forEach(x=>x.classList.toggle('active',x===b));qa('.panel').forEach(x=>x.classList.add('hidden'));q('#tab-'+b.dataset.tab)?.classList.remove('hidden');q('#adminMoreMenu')?.classList.remove('open');if(b.dataset.tab==='passwords')refreshResetUsers();});});}
function enhanceNav(){const nav=q('.tabs');if(!nav)return;qa('.tab[data-tab]',nav).forEach(b=>{const [label,icon]=navMeta[b.dataset.tab]||[b.textContent,'•'];b.innerHTML=`<span aria-hidden="true">${icon}</span> ${label}`;if(!['overview','users','tickets','release'].includes(b.dataset.tab))b.classList.add('admin-secondary');});const guardian=nav.querySelector('a[href*="guardian"]');guardian?.classList.add('admin-secondary');
if(!q('#adminMoreBtn')){const more=document.createElement('button');more.id='adminMoreBtn';more.className='tab admin-more-toggle';more.type='button';more.innerHTML='<span aria-hidden="true">•••</span> More';nav.appendChild(more);const menu=document.createElement('div');menu.id='adminMoreMenu';menu.className='admin-more-menu';document.body.appendChild(menu);const secondary=[...qa('.admin-secondary',nav)];secondary.forEach(el=>{if(el.tagName==='A'){const a=document.createElement('a');a.href=el.href;a.textContent='Guardian';menu.appendChild(a)}else{const x=document.createElement('button');x.type='button';x.textContent=(navMeta[el.dataset.tab]?.[0]||el.textContent);x.onclick=()=>el.click();menu.appendChild(x)}});more.onclick=()=>menu.classList.toggle('open');document.addEventListener('click',e=>{if(!menu.contains(e.target)&&e.target!==more&&!more.contains(e.target))menu.classList.remove('open')});}}
function addPageHeaders(){const labels={overview:['Command centre','Health, workload and release status at a glance.'],users:['Accounts','Manage approved users, invitations and access.'],devices:['Devices','Registered installs and release adoption.'],tickets:['Support','Triage user issues without hunting through multiple screens.'],controls:['Controls','Operational feature and maintenance controls.'],release:['Release','OTA status, rollout health and support policy.'],notify:['Notifications','Send targeted messages to registered devices.'],announce:['Announcements','Publish in-app notices by audience.'],audit:['Audit','Read-only privileged activity history.']};Object.entries(labels).forEach(([id,[title,desc]])=>{const p=q('#tab-'+id);if(!p||p.querySelector('.admin-page-head'))return;const h=document.createElement('div');h.className='admin-page-head';h.innerHTML=`<div><h2>${title}</h2><p>${desc}</p></div>`;p.prepend(h)})}
async function refreshAttention(){const p=q('#tab-overview');if(!p||!window.sb)return;let box=q('#adminAttention');if(!box){box=document.createElement('div');box.id='adminAttention';box.className='admin-attention';p.querySelector('.grid')?.insertAdjacentElement('beforebegin',box)}try{const [tickets,disabled,devices]=await Promise.all([sb.from('support_tickets').select('id',{count:'exact',head:true}).in('status',['open','in_progress','waiting_on_user']),sb.from('profiles').select('id',{count:'exact',head:true}).eq('is_enabled',false),sb.from('devices').select('id',{count:'exact',head:true})]);box.innerHTML=`<div class="card"><small>SUPPORT NEEDS ATTENTION</small><b>${tickets.count??0}</b></div><div class="card"><small>DISABLED ACCOUNTS</small><b>${disabled.count??0}</b></div><div class="card"><small>REGISTERED DEVICES</small><b>${devices.count??0}</b></div>`}catch{box.innerHTML=''}}
function usersArray(){try{return [...managedUsers.values()]}catch{return[]}}
function refreshResetUsers(){const sel=q('#adminResetUser');if(!sel)return;const chosen=sel.value;const rows=usersArray().filter(u=>u?.id&&u.id!==me?.id).sort((a,b)=>String(a.display_name||a.email).localeCompare(String(b.display_name||b.email)));sel.innerHTML='<option value="">Choose an account</option>'+rows.map(u=>`<option value="${u.id}">${String(u.display_name||u.email||u.id).replace(/[<&]/g,'')} · ${u.role}</option>`).join('');if(rows.some(x=>x.id===chosen))sel.value=chosen}
let issued={password:'',user:null};
function smsMessage(){if(!issued.password||!issued.user)return'';return `B&L Morley temporary password for ${issued.user.display_name||issued.user.email}: ${issued.password}\n\nSign in with this password, then Morley will require you to choose a new password.`}
async function resetPassword(){const id=q('#adminResetUser')?.value,status=q('#adminResetStatus'),btn=q('#adminResetBtn');if(!id){status.textContent='Choose an account first.';return}if(myProfile?.role!=='admin'){status.textContent='Administrator access is required.';return}btn.disabled=true;status.textContent='Generating secure temporary password…';q('#adminResetResult')?.classList.add('hidden');try{const {data,error}=await sb.functions.invoke('admin-user-control',{body:{action:'reset_password',target_user_id:id}});if(error){let msg=error.message||'Password reset failed.';try{const ctx=await error.context?.json();if(ctx?.error)msg=ctx.error}catch{}throw new Error(msg)}if(!data?.ok||!data?.temporary_password)throw new Error(data?.error||'Password reset failed.');const user=usersArray().find(x=>x.id===id)||{id};issued={password:data.temporary_password,user};q('#adminTempPassword').textContent=issued.password;q('#adminResetResult').classList.remove('hidden');q('#adminOpenSms').disabled=false;status.textContent='Temporary password created. The user will be forced to change it at next sign-in.';await refreshAttention()}catch(e){status.textContent=e.message||String(e)}finally{btn.disabled=false}}
async function copyPassword(){if(!issued.password)return;await navigator.clipboard?.writeText(issued.password);q('#adminResetStatus').textContent='Temporary password copied.'}
async function sharePassword(){const text=smsMessage();if(!text)return;if(navigator.share){await navigator.share({title:'B&L Morley temporary password',text})}else{await navigator.clipboard?.writeText(text);q('#adminResetStatus').textContent='Message copied for sharing.'}}
function openSms(){const phone=(q('#adminResetPhone')?.value||'').replace(/[^+\d]/g,''),text=smsMessage();if(!phone||!text){q('#adminResetStatus').textContent='Enter the mobile number and generate a temporary password first.';return}location.href=`sms:${encodeURIComponent(phone)}?body=${encodeURIComponent(text)}`}
function wirePassword(){q('#adminResetBtn')?.addEventListener('click',resetPassword);q('#adminCopyPassword')?.addEventListener('click',copyPassword);q('#adminSharePassword')?.addEventListener('click',sharePassword);q('#adminOpenSms')?.addEventListener('click',openSms)}
function wrapLoaders(){try{const oldUsers=loadUsers;loadUsers=async function(){await oldUsers();refreshResetUsers();};const oldMetrics=loadMetrics;loadMetrics=async function(){await oldMetrics();await refreshAttention();}}catch{}}
function boot(){loadCss();addPasswordSection();enhanceNav();wireTabs();addPageHeaders();wirePassword();wrapLoaders();refreshResetUsers();setTimeout(refreshAttention,200);document.body.classList.add('admin-v2')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();
