(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s);
function appReady(){const app=q('#appView');return !!app&&!app.classList.contains('hidden')}
function loadCss(){if(!q('#adminHomeCss')){const l=document.createElement('link');l.id='adminHomeCss';l.rel='stylesheet';l.href='admin-home.css?v=1';document.head.appendChild(l)}if(!q('#adminPhotoParityCss')){const p=document.createElement('link');p.id='adminPhotoParityCss';p.rel='stylesheet';p.href='admin-photo-parity.css?v=2';document.head.appendChild(p)}if(!q('#adminPhotoParityV2Css')){const p=document.createElement('link');p.id='adminPhotoParityV2Css';p.rel='stylesheet';p.href='admin-photo-parity-v2.css?v=1';document.head.appendChild(p)}}
function loadLifecycle(){for(const [id,src] of [['adminLifecycleScript','admin-lifecycle-management.js?v=1'],['adminLifecycleLinkScript','admin-lifecycle-linking.js?v=1'],['adminAttentionTruthScript','admin-attention-truth.js?v=1']])if(!q('#'+id)){const s=document.createElement('script');s.id=id;s.src=src;s.async=false;document.body.appendChild(s)}}
function clickTab(id){q(`.tabs .tab[data-tab="${id}"]`)?.click()}
function initials(){const raw=(q('#whoami')?.textContent||'Admin').trim();const p=raw.split(/\s+/).filter(Boolean).filter(x=>!x.includes('@'));return p.length?(p[0][0]+(p[1]?.[0]||'')).toUpperCase():'A'}
function enhanceTopbar(){const bar=q('.topbar');if(!bar)return;const title=bar.querySelector('h1');if(title&&!q('.admin-home-tagline',bar)){const tag=document.createElement('div');tag.className='admin-home-tagline';tag.textContent='MANAGE • MONITOR • GROW';title.insertAdjacentElement('afterend',tag)}const badge=bar.querySelector('.badge');if(badge)badge.style.display='none';if(!q('.admin-header-actions',bar)){const a=document.createElement('div');a.className='admin-header-actions';a.innerHTML='<button type="button" class="admin-icon-button" data-admin-head="notify" aria-label="Notifications">◉</button><button type="button" class="admin-icon-button" data-admin-head="settings" aria-label="Controls and settings">⚙</button>';bar.appendChild(a);q('[data-admin-head="notify"]',a).onclick=()=>clickTab('notify');q('[data-admin-head="settings"]',a).onclick=()=>clickTab('controls')}}
function enhanceProfile(){const toolbar=q('.toolbar');if(!toolbar)return;const info=toolbar.firstElementChild;if(!info||info.classList.contains('admin-profile-wrap'))return;const copy=document.createElement('div');copy.className='admin-profile-copy';while(info.firstChild)copy.appendChild(info.firstChild);const avatar=document.createElement('div');avatar.className='admin-profile-avatar';avatar.setAttribute('aria-hidden','true');avatar.textContent=initials();info.className='admin-profile-wrap';info.append(avatar,copy);const update=()=>{avatar.textContent=initials();const role=q('#roleText');if(role&&!q('.admin-role-live',role)&&/admin/i.test(role.textContent||'')){role.innerHTML=(role.textContent||'').replace(/ADMIN/i,'<span class="admin-role-live">ADMIN ●</span>')}};update();new MutationObserver(update).observe(copy,{subtree:true,childList:true,characterData:true})}
function quickCard(label,desc,icon,tab,tone=''){const a=document.createElement('a');a.className='admin-quick-card';if(tone)a.dataset.tone=tone;a.href='#';a.onclick=e=>{e.preventDefault();clickTab(tab)};a.innerHTML=`<span class="admin-quick-icon" aria-hidden="true">${icon}</span><span><span class="admin-quick-label">${label}</span><span class="admin-quick-desc">${desc}</span></span>`;return a}
function enhanceOverview(){const panel=q('#tab-overview');if(!panel||q('#adminHomeQuick',panel))return;const head=document.createElement('div');head.className='admin-home-section';head.innerHTML='<h2>Quick Access</h2><span>Morley Admin</span>';const grid=document.createElement('div');grid.id='adminHomeQuick';grid.className='admin-quick-grid';[['Accounts','Manage users','◎','users',''],['Support','View & resolve','✉','tickets','blue'],['Pricing','Manage pricing','$','pricing','gold'],['Devices','Catalogue & devices','◇','devices','violet'],['Release','Updates & deploy','↗','release','rose'],['Audit','Privileged activity','≡','audit','']].forEach(x=>grid.appendChild(quickCard(...x)));panel.append(head,grid)}
function run(){if(!appReady())return;loadCss();loadLifecycle();enhanceTopbar();enhanceProfile();enhanceOverview();document.documentElement.dataset.adminHome='ready'}
function boot(){let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;run()})};let passes=0;const timer=setInterval(()=>{schedule();if(++passes>=20)clearInterval(timer)},500);new MutationObserver(schedule).observe(q('#appView')||document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});schedule()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();