const SUPABASE_URL='https://ghdhairijqjqivqriigi.supabase.co';
const SUPABASE_KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));let me=null,myProfile=null,config={};
function showLogin(){ $('loginView').classList.remove('hidden');$('appView').classList.add('hidden') } function showApp(){ $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('whoami').textContent=myProfile.display_name||myProfile.email||'Admin';$('roleText').textContent=`${myProfile.role.toUpperCase()} • ${myProfile.email||''}` }
async function loadSession(){const {data:{session}}=await sb.auth.getSession();if(!session)return showLogin();me=session.user;const {data:p,error}=await sb.from('profiles').select('*').eq('id',me.id).single();if(error||!p||!p.is_enabled||!['admin','manager'].includes(p.role)){await sb.auth.signOut();$('loginStatus').textContent=error?.message||'This account is not authorised for Admin Control.';return showLogin()}myProfile=p;showApp();await refreshAll()}
$('loginBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;$('loginStatus').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginStatus').textContent=error.message;return}await loadSession()};$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden')});
async function refreshAll(){await Promise.all([loadUsers(),loadDevices(),loadConfig(),loadAudit(),loadMetrics(),loadNotifications(),loadAnnouncements()])}
async function loadMetrics(){const [u,d,n,c]=await Promise.all([sb.from('profiles').select('id',{count:'exact',head:true}),sb.from('devices').select('id',{count:'exact',head:true}),sb.from('notification_jobs').select('id',{count:'exact',head:true}).eq('status','queued'),sb.from('app_config').select('value').eq('key','current_release').single()]);$('metricUsers').textContent=u.count??0;$('metricDevices').textContent=d.count??0;$('metricQueued').textContent=n.count??0;$('metricVersion').textContent=c.data?.value?.versionName||'—'}
async function secureUserAction(action,target){const label={force_signout:'Force sign out',disable:'Disable',enable:'Enable',delete:'Delete'}[action]||action;if(action==='delete'&&!confirm('Permanently delete this account? This cannot be undone.'))return;if(action==='force_signout'&&!confirm('Sign this account out on all devices?'))return;const {data,error}=await sb.functions.invoke('admin-user-control',{body:{action,target_user_id:target}});if(error){let msg=error.message||`${label} failed`;try{const ctx=await error.context?.json();if(ctx?.error)msg=ctx.error}catch{}alert(msg);return}if(!data?.ok){alert(data?.error||`${label} failed`);return}await refreshAll()}
async function loadUsers(){const {data,error}=await sb.from('profiles').select('*').order('created_at',{ascending:false});if(error){$('usersList').textContent=error.message;return}$('usersList').innerHTML=(data||[]).map(p=>`<div class="row"><div class="row-main"><div class="row-title">${esc(p.display_name||p.email||p.id)}</div><div class="muted">${esc(p.email||p.id)} • ${p.is_enabled?'ACTIVE':'DISABLED'}</div></div><div class="actions"><select data-role="${p.id}" ${myProfile.role!=='admin'?'disabled':''}><option ${p.role==='staff'?'selected':''}>staff</option><option ${p.role==='manager'?'selected':''}>manager</option><option ${p.role==='admin'?'selected':''}>admin</option></select><button class="small ${p.is_enabled?'ghost':'okbtn'}" data-user-action="${p.is_enabled?'disable':'enable'}" data-user="${p.id}" ${myProfile.role!=='admin'?'disabled':''}>${p.is_enabled?'Disable':'Enable'}</button><button class="small ghost" data-user-action="force_signout" data-user="${p.id}" ${myProfile.role!=='admin'||p.id===me.id?'disabled':''}>Force sign out</button><button class="small ghost" data-user-action="delete" data-user="${p.id}" ${myProfile.role!=='admin'||p.id===me.id?'disabled':''}>Delete</button></div></div>`).join('')||'<div class="muted">No accounts yet.</div>';document.querySelectorAll('[data-role]').forEach(s=>s.onchange=async()=>{const {error}=await sb.rpc('admin_set_user_role',{target_user:s.dataset.role,new_role:s.value});if(error)alert(error.message);await refreshAll()});document.querySelectorAll('[data-user-action]').forEach(b=>b.onclick=()=>secureUserAction(b.dataset.userAction,b.dataset.user))}
async function loadDevices(){const {data,error}=await sb.from('devices').select('*').order('last_seen_at',{ascending:false});if(error){$('devicesList').textContent=error.message;return}$('devicesList').innerHTML=(data||[]).map(d=>`<div class="row"><div class="row-main"><div class="row-title">${esc(d.device_name||d.installation_id)}</div><div class="muted">${esc(d.platform)} • ${esc(d.app_version||'unknown')} • last seen ${new Date(d.last_seen_at).toLocaleString()}</div></div><span class="pill ${d.notifications_enabled?'ok':''}">${d.notifications_enabled?'NOTIFY ON':'NOTIFY OFF'}</span></div>`).join('')||'<div class="muted">No devices registered yet.</div>'}
async function loadConfig(){const {data,error}=await sb.from('app_config').select('*').order('key');if(error)return;config=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));const f=config.feature_flags||{};$('featureFlags').innerHTML=['deviceScanner','googlePricing','ebayPricing','valuationHistory','maintenanceMode'].map(k=>`<label class="switchrow"><span>${esc(k)}</span><input type="checkbox" data-flag="${k}" ${f[k]?'checked':''}></label>`).join('');$('maintenanceMessage').value=f.maintenanceMessage||'';const r=config.current_release||{},m=config.minimum_supported_version||{};$('releaseName').value=r.versionName||'';$('releaseCode').value=r.versionCode||'';$('minName').value=m.versionName||'';$('minCode').value=m.versionCode||'';$('forceUpdate').checked=!!m.forceUpdate}
$('saveControlsBtn').onclick=async()=>{const flags={};document.querySelectorAll('[data-flag]').forEach(x=>flags[x.dataset.flag]=x.checked);flags.maintenanceMessage=$('maintenanceMessage').value.trim();$('controlsStatus').textContent='Saving…';const {error}=await sb.rpc('admin_set_config',{config_key:'feature_flags',config_value:flags});$('controlsStatus').textContent=error?error.message:'Controls saved.';if(!error)await Promise.all([loadConfig(),loadAudit()])};
$('saveReleaseBtn').onclick=async()=>{$('releaseStatus').textContent='Publishing…';const current={versionName:$('releaseName').value.trim(),versionCode:Number($('releaseCode').value||0)},minimum={versionName:$('minName').value.trim(),versionCode:Number($('minCode').value||0),forceUpdate:$('forceUpdate').checked};const a=await sb.rpc('admin_set_config',{config_key:'current_release',config_value:current});if(a.error){$('releaseStatus').textContent=a.error.message;return}const b=await sb.rpc('admin_set_config',{config_key:'minimum_supported_version',config_value:minimum});$('releaseStatus').textContent=b.error?b.error.message:'Release settings published.';if(!b.error)await refreshAll()};
async function loadNotifications(){const {data,error}=await sb.from('notification_jobs').select('*').order('created_at',{ascending:false}).limit(30);if(error){$('notificationList').textContent=error.message;return}$('notificationList').innerHTML=(data||[]).map(n=>`<div class="row"><div><strong>${esc(n.title)}</strong><div class="muted">${esc(n.body)} • ${esc(n.audience)} • ${new Date(n.created_at).toLocaleString()}${n.error?` • ${esc(n.error)}`:''}</div></div><span class="pill ${n.status==='sent'?'ok':''}">${esc(n.status)}</span></div>`).join('')||'<div class="muted">No notifications yet.</div>'}
$('queueNotifBtn').onclick=async()=>{const title=$('notifTitle').value.trim(),body=$('notifBody').value.trim(),audience=$('notifAudience').value;if(!title||!body){$('notifStatus').textContent='Enter a title and message.';return}$('notifStatus').textContent='Preparing notification…';const {data:job,error}=await sb.from('notification_jobs').insert({title,body,audience,requested_by:me.id}).select('id').single();if(error){$('notifStatus').textContent=error.message;return}await sb.from('admin_audit_log').insert({actor_user_id:me.id,action:'notification_queued',target_type:'audience',target_id:audience,details:{title}});$('notifStatus').textContent='Sending to registered devices…';const {data:delivery,error:deliveryError}=await sb.functions.invoke('send-admin-notification',{body:{job_id:job.id}});if(deliveryError){let msg=deliveryError.message||'Delivery failed.';try{const ctx=await deliveryError.context?.json();if(ctx?.error)msg=ctx.error}catch{}$('notifStatus').textContent=`Not sent: ${msg}`;}else{$('notifStatus').textContent=`Sent to ${delivery?.sent??0} device${delivery?.sent===1?'':'s'}${delivery?.failed?` (${delivery.failed} failed)`:''}.`;$('notifBody').value='';}await Promise.all([loadMetrics(),loadNotifications(),loadAudit(),loadDevices()])};
async function loadAnnouncements(){const {data,error}=await sb.from('announcements').select('*').order('created_at',{ascending:false}).limit(30);if(error){$('annList').textContent=error.message;return}$('annList').innerHTML=(data||[]).map(a=>`<div class="row"><div><strong>${esc(a.title)}</strong><div class="muted">${esc(a.body)} • ${esc(a.audience)}</div></div><span class="pill ${a.is_active?'ok':''}">${a.is_active?'ACTIVE':'OFF'}</span></div>`).join('')||'<div class="muted">No announcements yet.</div>'}
$('publishAnnBtn').onclick=async()=>{const title=$('annTitle').value.trim(),body=$('annBody').value.trim(),audience=$('annAudience').value;if(!title||!body){$('annStatus').textContent='Enter a title and announcement.';return}const {error}=await sb.from('announcements').insert({title,body,audience,created_by:me.id});$('annStatus').textContent=error?error.message:'Announcement published.';if(!error){$('annBody').value='';await Promise.all([loadAnnouncements(),loadAudit()])}};
async function loadAudit(){const {data,error}=await sb.from('admin_audit_log').select('*').order('created_at',{ascending:false}).limit(75);if(error){$('auditList').textContent=error.message;return}$('auditList').innerHTML=(data||[]).map(a=>`<div class="row"><div><strong>${esc(a.action)}</strong><div class="muted">${new Date(a.created_at).toLocaleString()} • ${esc(a.target_type||'')} ${esc(a.target_id||'')}</div></div></div>`).join('')||'<div class="muted">No audit activity yet.</div>'}
loadSession();