(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
let activity=[],incidents=[],channel=null,selected=null;
function shell(){if($('guardianLiveSessions'))return;const queue=$('guardianList')?.closest('section');if(!queue)return;const s=document.createElement('section');s.className='card';s.id='guardianLiveSessions';s.innerHTML='<div class="actions"><div><h2 style="margin-bottom:4px">Live Guardian sessions</h2><div class="muted">Realtime activity showing what Guardian is assessing, testing and waiting on.</div></div><span id="guardianLiveBadge" class="pill ok">CONNECTING</span></div><div id="guardianLiveSessionList" style="margin-top:12px"></div><div id="guardianLiveDetail" style="margin-top:14px"></div>';queue.insertAdjacentElement('beforebegin',s)}
function statusIcon(s){return s==='success'?'✓':s==='error'?'!':s==='warning'?'△':s==='waiting'?'◷':s==='stopped'?'■':'●'}
function render(){shell();const list=$('guardianLiveSessionList'),detail=$('guardianLiveDetail');if(!list||!detail)return;const active=incidents.filter(x=>!['resolved','ignored'].includes(x.state));list.innerHTML=active.map(x=>{const last=[...activity].reverse().find(a=>a.incident_id===x.id);return `<button class="ghost guardian-live-open" data-id="${esc(x.id)}" style="display:block;width:100%;text-align:left;margin-top:8px;padding:12px"><strong>${esc(label(x.classification||x.source))}</strong><div class="muted" style="margin-top:4px">${esc(label(x.state))}${last?` • ${esc(last.summary)}`:''}</div></button>`}).join('')||'<div class="muted">No active Guardian sessions.</div>';document.querySelectorAll('.guardian-live-open').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render()});const chosen=selected||active[0]?.id;if(!chosen){detail.innerHTML='';return}selected=chosen;const incident=incidents.find(x=>x.id===chosen),events=activity.filter(x=>x.incident_id===chosen);detail.innerHTML=`<div class="guardian-live-detail-card" style="padding:14px;border-radius:14px"><div class="actions"><div><strong>${esc(label(incident?.classification||incident?.source||'Guardian incident'))}</strong><div class="muted">${esc(chosen.slice(0,8))} • ${esc(label(incident?.state||''))}</div></div><span class="pill ok">LIVE</span></div><div style="margin-top:10px">${events.map(e=>`<div class="guardian-live-event" style="display:grid;grid-template-columns:28px 1fr;gap:10px;padding:11px 0;border-bottom:1px solid"><div style="font-weight:900">${statusIcon(e.status)}</div><div><div><strong>${esc(e.summary)}</strong></div><div class="muted" style="margin-top:3px">${new Date(e.created_at).toLocaleTimeString()} • ${esc(label(e.phase))}${e.progress!=null?` • ${Number(e.progress)}%`:''} • ${esc(e.actor||'guardian')}</div>${e.detail?`<div class="muted" style="margin-top:6px">${esc(e.detail)}</div>`:''}</div></div>`).join('')||'<div class="muted">Waiting for Guardian activity…</div>'}</div></div>`}
async function load(){shell();if(!window.sb)return;const [i,a]=await Promise.all([window.sb.from('guardian_incidents').select('id,source,state,classification,ticket_id,created_at').order('created_at',{ascending:false}).limit(100),window.sb.from('guardian_activity').select('id,incident_id,ticket_id,phase,status,summary,detail,visibility,progress,actor,created_at').order('created_at',{ascending:true}).limit(500)]);if(i.error){$('guardianLiveSessionList').textContent=i.error.message;return}if(a.error){$('guardianLiveSessionList').textContent=a.error.message;return}incidents=i.data||[];activity=a.data||[];render()}
async function subscribe(){if(!window.sb||channel)return;channel=window.sb.channel('guardian-admin-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'guardian_activity'},p=>{activity.push(p.new);$('guardianLiveBadge').textContent='LIVE';render()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'guardian_incidents'},p=>{const n=p.new,i=incidents.findIndex(x=>x.id===n.id);if(i>=0)incidents[i]={...incidents[i],...n};else incidents.unshift(n);render()}).subscribe(status=>{$('guardianLiveBadge').textContent=status==='SUBSCRIBED'?'LIVE':String(status||'CONNECTING')})}
async function init(){await load();await subscribe()}
window.loadGuardianLive=load;window.addEventListener('load',init,{once:true});setTimeout(init,600);
})();