(()=>{
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
  const label=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
  const canApprove=s=>['proposed','awaiting_approval'].includes(s);
  const canRetry=s=>['failed','ignored'].includes(s);
  let currentSettings=null,incidentRows=[],auditRows=[],historyPage=1,historyPageSize=10;

  function settingsPayload(killOverride){const kill=killOverride??$('guardianKillSwitch').checked;return{p_enabled:kill?false:$('guardianEnabled').checked,p_auto_fix_enabled:kill?false:$('guardianAutoFix').checked,p_max_auto_risk:$('guardianMaxRisk').value,p_operating_mode:$('guardianMode').value,p_learning_enabled:$('guardianLearning').checked,p_evolution_enabled:$('guardianEvolution').checked,p_confidence_threshold:Number($('guardianConfidence').value||0.85),p_max_parallel_repairs:Number($('guardianParallel').value||1),p_quarantine_on_repeated_failure:$('guardianQuarantine').checked,p_kill_switch:kill,p_kill_switch_reason:kill?$('guardianKillReason').value.trim():null};}
  async function setControls(payload,statusEl){const status=$(statusEl);if(status)status.textContent='Saving…';const{error}=await window.sb.rpc('guardian_set_controls',payload);if(error){if(status)status.textContent=error.message;return false}if(status)status.textContent='Guardian controls saved and audited.';await loadGuardian();return true}
  async function decideGuardian(incidentId,decision){if(!window.sb)return;const status=$('guardianActionStatus');if(status)status.textContent=`${label(decision)} in progress…`;const{error}=await window.sb.rpc('guardian_decide_incident',{incident_id:incidentId,decision});if(error){if(status)status.textContent=error.message;return}if(status)status.textContent=decision==='approve'?'Approval recorded. Guardian is preparing the protected repair candidate.':decision==='retry'?'Incident requeued for immediate Guardian triage.':'Incident rejected and moved to ignored.';await loadGuardian()}

  function incidentCategory(x){return String(x.classification||x.source||'guardian_incident')}
  function incidentTitle(x){return label(x.classification||x.source||'Guardian incident')}
  function incidentSearchText(x){return [x.id,x.ticket_id,x.state,x.risk_level,x.classification,x.source,x.diagnosis_summary,x.proposed_action,x.reproduction_summary,x.test_plan,x.resolution_summary,x.last_error_code,x.worker_version].filter(Boolean).join(' ').toLowerCase()}
  function auditSearchText(x){return [x.action,x.target_type,x.target_id,x.actor_user_id,JSON.stringify(x.details||{})].filter(Boolean).join(' ').toLowerCase()}
  function historyItems(){
    const q=($('guardianHistorySearch')?.value||'').trim().toLowerCase(),kind=$('guardianHistoryKind')?.value||'all',status=$('guardianHistoryStatus')?.value||'all',risk=$('guardianHistoryRisk')?.value||'all',category=$('guardianHistoryCategory')?.value||'all';
    const incidents=incidentRows.filter(x=>{if(kind==='audit')return false;if(status!=='all'){if(status==='open'){if(['resolved','ignored'].includes(x.state))return false}else if(x.state!==status)return false}if(risk!=='all'&&x.risk_level!==risk)return false;if(category!=='all'&&incidentCategory(x)!==category)return false;if(q&&!incidentSearchText(x).includes(q))return false;return true}).map(x=>({kind:'incident',date:x.updated_at||x.created_at,data:x}));
    const audits=auditRows.filter(x=>{if(kind==='incidents')return false;if(status!=='all'&&status!=='audit')return false;if(risk!=='all')return false;if(category!=='all'&&String(x.action||'')!==category)return false;if(q&&!auditSearchText(x).includes(q))return false;return true}).map(x=>({kind:'audit',date:x.created_at,data:x}));
    return [...incidents,...audits].sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));
  }
  function actionButtons(x){return [canApprove(x.state)?`<button class="guardian-action" data-id="${esc(x.id)}" data-decision="approve">Approve</button>`:'',canApprove(x.state)?`<button class="guardian-action ghost" data-id="${esc(x.id)}" data-decision="reject">Reject</button>`:'',canRetry(x.state)?`<button class="guardian-action ghost" data-id="${esc(x.id)}" data-decision="retry">Retry</button>`:''].filter(Boolean).join('')}
  function incidentDetail(x){const confidence=x.confidence==null?'—':`${Math.round(Number(x.confidence)*100)}%`;return `<div class="guardian-history-detail" data-detail-id="${esc(x.id)}" hidden><strong>${esc(incidentTitle(x))}</strong><div class="muted">${esc(label(x.state))} • ${esc(String(x.risk_level||'unknown').toUpperCase())} risk • confidence ${esc(confidence)} • attempts ${Number(x.attempt_count||0)}${x.ticket_id?` • ticket ${esc(x.ticket_id.slice(0,8))}`:''}${x.github_pr_number?` • PR #${Number(x.github_pr_number)}`:''}</div>${x.worker_version?`<div class="muted">Worker: ${esc(x.worker_version)}${x.last_worker_at?` • last run ${new Date(x.last_worker_at).toLocaleString()}`:''}</div>`:''}${x.diagnosis_summary?`<p><strong>Diagnosis:</strong> ${esc(x.diagnosis_summary)}</p>`:''}${x.reproduction_summary?`<p><strong>Reproduction:</strong> ${esc(x.reproduction_summary)}</p>`:''}${x.proposed_action?`<p><strong>Proposed:</strong> ${esc(x.proposed_action)}</p>`:''}${x.test_plan?`<p><strong>Test plan:</strong> ${esc(x.test_plan)}</p>`:''}${x.resolution_summary?`<p><strong>Resolution:</strong> ${esc(x.resolution_summary)}</p>`:''}${x.last_error_code?`<div class="guardian-row-status error">${esc(x.last_error_code)}</div>`:''}<div class="guardian-history-actions">${actionButtons(x)}</div></div>`}
  function renderHistory(){const host=$('guardianList');if(!host)return;const all=historyItems(),pages=Math.max(1,Math.ceil(all.length/historyPageSize));historyPage=Math.min(Math.max(1,historyPage),pages);const page=all.slice((historyPage-1)*historyPageSize,historyPage*historyPageSize);let html='<div class="guardian-history-head"><span>Incident / action</span><span>Status</span><span>Risk</span><span>Category</span><span>Updated</span><span>Actions</span></div>';
    html+=page.map(item=>{if(item.kind==='audit'){const a=item.data,id=`audit-${String(a.created_at||'').replace(/\W/g,'')}-${String(a.target_id||'').slice(0,6)}`;return `<div class="guardian-history-row"><div class="guardian-history-item"><strong>${esc(label(a.action))}</strong><small>${esc(a.target_type||'Guardian audit')} ${esc(a.target_id||'')}</small></div><span class="guardian-state-chip audit">Audit</span><span>—</span><span>${esc(label(a.action))}</span><span>${new Date(a.created_at).toLocaleString()}</span><span class="guardian-history-actions"><button class="ghost guardian-view-toggle" data-detail="${esc(id)}">View</button></span></div><div class="guardian-history-detail" data-detail-id="${esc(id)}" hidden><strong>${esc(label(a.action))}</strong><p class="muted">${esc(a.target_type||'guardian')} ${esc(a.target_id||'')}</p>${a.details?`<pre>${esc(JSON.stringify(a.details,null,2))}</pre>`:''}</div>`}
      const x=item.data;return `<div class="guardian-history-row"><div class="guardian-history-item"><strong>${esc(incidentTitle(x))}</strong><small>ID: ${esc(x.id.slice(0,8))}</small></div><span class="guardian-state-chip ${esc(x.state)}">${esc(label(x.state))}</span><span class="guardian-risk-chip ${esc(x.risk_level||'')}">${esc(label(x.risk_level||'—'))}</span><span>${esc(label(incidentCategory(x)))}</span><span>${new Date(x.updated_at||x.created_at).toLocaleString()}</span><span class="guardian-history-actions"><button class="ghost guardian-view-toggle" data-detail="${esc(x.id)}">View</button></span></div>${incidentDetail(x)}`}).join('');
    if(!page.length)html+='<div class="muted" style="padding:18px">No matching Guardian history.</div>';host.innerHTML=html;$('guardianHistoryCount').textContent=`${all.length} item${all.length===1?'':'s'}`;$('guardianHistoryPage').textContent=`${historyPage} / ${pages}`;$('guardianHistoryPrev').disabled=historyPage<=1;$('guardianHistoryNext').disabled=historyPage>=pages;}
  function renderAuditRaw(){const host=$('guardianAuditList');if(!host)return;host.innerHTML=auditRows.slice(0,80).map(x=>`<div class="row"><div class="row-main"><div class="row-title">${esc(label(x.action))}</div><div class="muted">${new Date(x.created_at).toLocaleString()} • ${esc(x.target_type||'guardian')} ${esc(x.target_id||'')}</div>${x.details?`<div class="muted" style="margin-top:5px">${esc(JSON.stringify(x.details))}</div>`:''}</div></div>`).join('')||'<div class="muted">No Guardian audit activity yet.</div>'}
  function renderQuarantine(){const failed=incidentRows.filter(x=>x.state==='failed'),host=$('guardianQuarantineList');if($('guardianQuarantineCount'))$('guardianQuarantineCount').textContent=`${failed.length} quarantined item${failed.length===1?'':'s'}`;if(!host)return;host.innerHTML=failed.map(x=>`<div class="guardian-quarantine-item"><div><h3>${esc(incidentTitle(x))}</h3><p>${esc(x.last_error_code||x.diagnosis_summary||'Failed Guardian incident requiring review.')}</p><p style="margin-top:4px">${new Date(x.updated_at||x.created_at).toLocaleString()} • ${esc(label(x.risk_level||'unknown'))} risk • ID ${esc(x.id.slice(0,8))}</p><div class="guardian-history-detail" data-detail-id="q-${esc(x.id)}" hidden>${incidentDetail(x).replace(`data-detail-id="${esc(x.id)}"`,`data-detail-id="q-inner-${esc(x.id)}"`)}</div></div><div class="guardian-quarantine-actions"><button class="ghost guardian-view-toggle" data-detail="q-${esc(x.id)}">View</button><button class="guardian-action" data-id="${esc(x.id)}" data-decision="retry">Retry</button></div></div>`).join('')||'<div class="muted" style="padding:4px 0">No quarantined incidents.</div>'}
  function populateCategories(){const sel=$('guardianHistoryCategory');if(!sel)return;const current=sel.value||'all',values=[...new Set([...incidentRows.map(incidentCategory),...auditRows.map(x=>String(x.action||'')).filter(Boolean)])].sort();sel.innerHTML='<option value="all">All incident types</option>'+values.map(v=>`<option value="${esc(v)}">${esc(label(v))}</option>`).join('');if(values.includes(current))sel.value=current}
  function updateModePill(s){const p=$('guardianControlModePill');if(!p)return;p.textContent=s.kill_switch?'KILL SWITCH':s.enabled?`${label(s.operating_mode||'observe')} • ${s.auto_fix_enabled?'AUTO':'MANUAL'}`:'PAUSED';p.classList.toggle('ok',!s.kill_switch&&!!s.enabled)}

  async function loadAudit(){if(!window.sb)return;const{data,error}=await window.sb.from('admin_audit_log').select('actor_user_id,action,target_type,target_id,details,created_at').order('created_at',{ascending:false}).limit(250);if(error){if($('guardianAuditList'))$('guardianAuditList').textContent=error.message;return}auditRows=(data||[]).filter(x=>String(x.action||'').startsWith('guardian_')||String(x.target_type||'').startsWith('guardian'));populateCategories();renderAuditRaw();renderHistory()}
  async function loadGuardian(){if(!window.sb||!$('guardianStatus'))return;$('guardianStatus').textContent='Refreshing Guardian…';const[settingsResult,incidentsResult]=await Promise.all([window.sb.from('guardian_settings').select('*').eq('singleton',true).single(),window.sb.from('guardian_incidents').select('id,ticket_id,source,state,risk_level,classification,confidence,diagnosis_summary,proposed_action,auto_fix_eligible,requires_approval,github_branch,github_pr_number,last_error_code,worker_version,reproduction_summary,test_plan,resolution_summary,last_worker_at,attempt_count,created_at,updated_at').order('created_at',{ascending:false}).limit(150)]);if(settingsResult.error){$('guardianStatus').textContent=settingsResult.error.message;return}if(incidentsResult.error){$('guardianStatus').textContent=incidentsResult.error.message;return}const s=settingsResult.data||{},rows=incidentsResult.data||[];currentSettings=s;incidentRows=rows;
    $('guardianEnabled').checked=!!s.enabled;$('guardianAutoFix').checked=!!s.auto_fix_enabled;$('guardianMaxRisk').value=s.max_auto_risk||'low';$('guardianMode').value=s.operating_mode||'observe';$('guardianLearning').checked=s.learning_enabled!==false;$('guardianEvolution').checked=!!s.evolution_enabled;$('guardianConfidence').value=Number(s.confidence_threshold??0.85).toFixed(2);$('guardianParallel').value=s.max_parallel_repairs||1;$('guardianQuarantine').checked=s.quarantine_on_repeated_failure!==false;$('guardianHumanCode').checked=true;$('guardianKillSwitch').checked=!!s.kill_switch;$('guardianKillReason').value=s.kill_switch_reason||'';
    $('guardianMetricOpen').textContent=rows.filter(x=>!['resolved','ignored'].includes(x.state)).length;$('guardianMetricApproval').textContent=rows.filter(x=>canApprove(x.state)).length;$('guardianMetricResolved').textContent=rows.filter(x=>x.state==='resolved').length;$('guardianMetricFailed').textContent=rows.filter(x=>x.state==='failed').length;updateModePill(s);
    $('guardianStatus').textContent=s.kill_switch?`KILL SWITCH ENGAGED • Guardian stopped${s.kill_switch_reason?` • ${s.kill_switch_reason}`:''}`:s.enabled?`ONLINE • ${label(s.operating_mode||'observe')} mode • ${s.learning_enabled!==false?'learning on':'learning off'} • ${s.evolution_enabled?'evolution proposals on':'evolution proposals off'}`:'PAUSED • Guardian intake disabled';populateCategories();renderHistory();renderQuarantine();await loadAudit()}
  async function saveGuardian(){if(!window.sb)return;if(currentSettings?.kill_switch){$('guardianSaveStatus').textContent='Disengage the kill switch first before changing active operating controls.';return}await setControls(settingsPayload(false),'guardianSaveStatus')}
  async function applyKillSwitch(){if(!window.sb)return;const engaging=$('guardianKillSwitch').checked;if(engaging&&!$('guardianKillReason').value.trim()){$('guardianKillStatus').textContent='Enter a reason before engaging the kill switch.';return}if(engaging&&!confirm('Engage Guardian kill switch now? New intake and automatic repairs will stop immediately.')){$('guardianKillSwitch').checked=!!currentSettings?.kill_switch;return}if(!engaging&&currentSettings?.kill_switch&&!confirm('Disengage Guardian kill switch and restore the saved operating controls?')){$('guardianKillSwitch').checked=true;return}const payload=settingsPayload(engaging);if(!engaging){payload.p_enabled=false;payload.p_auto_fix_enabled=false}const ok=await setControls(payload,'guardianKillStatus');if(ok)$('guardianKillStatus').textContent=engaging?'Kill switch engaged. Guardian intake and automatic repairs are stopped.':'Kill switch disengaged. Guardian remains paused until operating controls are explicitly saved.'}
  function bindFilters(){['guardianHistorySearch','guardianHistoryKind','guardianHistoryStatus','guardianHistoryRisk','guardianHistoryCategory'].forEach(id=>$(id)?.addEventListener(id==='guardianHistorySearch'?'input':'change',()=>{historyPage=1;renderHistory()}));$('guardianHistoryPrev')?.addEventListener('click',()=>{historyPage--;renderHistory()});$('guardianHistoryNext')?.addEventListener('click',()=>{historyPage++;renderHistory()});document.querySelectorAll('[data-focus-filter]').forEach(btn=>btn.addEventListener('click',()=>{const mode=btn.dataset.focusFilter;$('guardianHistoryKind').value='incidents';$('guardianHistoryStatus').value=mode==='approval'?'awaiting_approval':mode==='resolved'?'resolved':mode==='failed'?'failed':'open';historyPage=1;$('guardianHistoryPanel').open=true;renderHistory();$('guardianHistoryPanel').scrollIntoView({behavior:'smooth',block:'start'})}));document.addEventListener('click',e=>{const b=e.target.closest?.('.guardian-view-toggle');if(!b)return;const d=document.querySelector(`[data-detail-id="${CSS.escape(b.dataset.detail)}"]`);if(d)d.hidden=!d.hidden})}
  $('guardianSaveBtn')?.addEventListener('click',saveGuardian);$('guardianKillBtn')?.addEventListener('click',applyKillSwitch);$('guardianRefreshBtn')?.addEventListener('click',loadGuardian);$('guardianAuditRefreshBtn')?.addEventListener('click',loadAudit);bindFilters();window.loadGuardian=loadGuardian;window.sb?.auth?.onAuthStateChange?.((event,session)=>{if(session)setTimeout(loadGuardian,0)});
})();