(function(root,factory){const api=factory(root.MorleyIntelligence);if(typeof module==='object'&&module.exports)module.exports=api;root.MorleyIntelligenceEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(contracts){'use strict';
const clean=v=>typeof v==='string'?v.trim():'';const lower=v=>clean(v).toLowerCase();const arr=v=>Array.isArray(v)?v:[];const num=v=>Number.isFinite(Number(v))?Number(v):null;
function canonicalDevice(input={}){return Object.freeze({id:clean(input.id)||null,category:clean(input.category)||null,brand:clean(input.brand)||null,name:clean(input.name)||null,modelNumber:clean(input.modelNumber)||null,storage:clean(input.storage)||null,colour:clean(input.colour)||null,releaseYear:num(input.releaseYear),imageUrl:clean(input.imageUrl)||null,evidence:arr(input.evidence),status:clean(input.status)||'active'});}
function deviceKey(d){const x=canonicalDevice(d);return [lower(x.category),lower(x.brand),lower(x.name),lower(x.modelNumber),lower(x.storage)].join('|')}
function catalogueFindings(devices=[]){const list=arr(devices).map(canonicalDevice),findings=[];const seen=new Map();for(const d of list){const key=deviceKey(d);if(seen.has(key))findings.push({type:'duplicate',severity:'high',deviceId:d.id,otherDeviceId:seen.get(key),field:null});else seen.set(key,d.id);if(!d.imageUrl)findings.push({type:'missing_image',severity:'medium',deviceId:d.id,field:'imageUrl'});if(!d.modelNumber)findings.push({type:'missing_model_number',severity:'high',deviceId:d.id,field:'modelNumber'});if(!d.releaseYear)findings.push({type:'missing_release_year',severity:'medium',deviceId:d.id,field:'releaseYear'});if(!d.storage&&/phone|tablet|laptop|console/i.test(d.category||''))findings.push({type:'missing_storage',severity:'medium',deviceId:d.id,field:'storage'});}return findings;}
function pricingObservation(input={}){const price=num(input.price);return Object.freeze({source:clean(input.source)||null,sourceType:clean(input.sourceType)||'unknown',price:price!=null&&price>=0?price:null,currency:clean(input.currency)||'AUD',observedAt:clean(input.observedAt)||null,directSeller:input.directSeller===true,confirmed:input.confirmed===true});}
function pricingRecommendation(observations=[],opts={}){const valid=arr(observations).map(pricingObservation).filter(o=>o.price!=null&&o.currency==='AUD'&&o.confirmed);if(!valid.length)return {state:'unavailable',marketLow:null,marketHigh:null,median:null,recommendedBuy:null,recommendedSell:null,expectedGrossMargin:null,confidence:0,evidenceCount:0};const prices=valid.map(o=>o.price).sort((a,b)=>a-b);const mid=Math.floor(prices.length/2),median=prices.length%2?prices[mid]:(prices[mid-1]+prices[mid])/2;const sell=Math.round(median);const marginRate=Math.max(0,Math.min(.9,num(opts.targetGrossMarginRate)??.35));const buy=Math.round(sell*(1-marginRate));return {state:'confirmed',marketLow:prices[0],marketHigh:prices[prices.length-1],median,recommendedBuy:buy,recommendedSell:sell,expectedGrossMargin:sell-buy,confidence:Math.min(1,valid.length/5),evidenceCount:valid.length};}
function sellSpeed(input={}){const sold=num(input.soldCount),days=num(input.windowDays),active=num(input.activeComparableCount);if(sold==null||days==null||days<=0)return {state:'unavailable',score:null,label:'Unknown',confidence:0};const daily=sold/days;const pressure=active&&active>0?daily/active:daily;const score=Math.max(0,Math.min(100,Math.round(pressure*100)));return {state:'confirmed',score,label:score>=65?'Fast':score>=30?'Moderate':'Slow',confidence:Math.min(1,(sold+Math.max(0,active||0))/10)};}
function marketplaceMatch(stock=[],listings=[]){const stocks=arr(stock),ls=arr(listings);const byId=new Map(stocks.map(s=>[clean(s.stockNumber),s]).filter(([k])=>k));const used=new Set(),rows=[];for(const listing of ls){const text=[listing.title,listing.description,listing.url].map(clean).join(' ');const matches=[...byId.keys()].filter(id=>new RegExp(`(^|\\D)${id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(\\D|$)`,'i').test(text));if(matches.length===1){const id=matches[0];used.add(id);const stockItem=byId.get(id);rows.push({status:num(stockItem.price)!=null&&num(listing.price)!=null&&num(stockItem.price)!==num(listing.price)?'price_mismatch':'matched',stockNumber:id,stock:stockItem,listing});}else rows.push({status:matches.length?'uncertain_match':'unmatched_listing',stockNumber:null,stock:null,listing});}for(const [id,s] of byId)if(!used.has(id))rows.push({status:'missing_listing',stockNumber:id,stock:s,listing:null});return rows;}
function smartAlerts(input={}){const out=[];for(const f of arr(input.catalogueFindings))out.push({key:`catalogue:${f.type}:${f.deviceId||''}`,type:'catalogue',severity:f.severity||'medium',detail:f});for(const m of arr(input.marketplace))if(!['matched'].includes(m.status))out.push({key:`marketplace:${m.status}:${m.stockNumber||clean(m.listing?.url)}`,type:'marketplace',severity:m.status==='missing_listing'?'high':'medium',detail:m});for(const x of arr(input.system))if(x&&x.active)out.push({key:`system:${clean(x.id)||clean(x.type)}`,type:'system',severity:clean(x.severity)||'high',detail:x});for(const s of arr(input.support)){const id=clean(s.id)||clean(s.subject);if(!id)continue;const priority=lower(s.priority);if(s.slaRisk===true)out.push({key:`support:sla:${id}`,type:'support',severity:'high',detail:{...s,reason:'sla_risk'}});else if(priority==='urgent'||priority==='high')out.push({key:`support:priority:${id}`,type:'support',severity:'high',detail:{...s,reason:`${priority}_priority`}})}for(const r of arr(input.release)){const id=clean(r.id)||String(r.versionCode??'current');if(r.manifestVerified!==true)out.push({key:`release:manifest:${id}`,type:'release',severity:'critical',detail:{...r,reason:'manifest_unverified'}});if(r.checksumVerified!==true)out.push({key:`release:checksum:${id}`,type:'release',severity:'critical',detail:{...r,reason:'checksum_unverified'}});const source=num(r.sourceVersionCode),ota=num(r.versionCode);if(source!=null&&ota!=null&&source!==ota)out.push({key:`release:drift:${id}`,type:'release',severity:'high',detail:{...r,reason:source>ota?'source_ahead':'ota_ahead'}});const rollout=r.rollout&&typeof r.rollout==='object'?r.rollout:{},current=Math.max(0,num(rollout.current)||0),outdated=Math.max(0,num(rollout.outdated)||0),ahead=Math.max(0,num(rollout.ahead)||0),unknown=Math.max(0,num(rollout.unknown)||0),total=current+outdated+ahead+unknown;if(total&&outdated/total>=.25)out.push({key:`release:rollout:${id}`,type:'release',severity:'medium',detail:{...r,reason:'rollout_lag'}})}return [...new Map(out.map(a=>[a.key,a])).values()];}
function identificationProposal(input={}){const evidence=arr(input.evidence).filter(Boolean);const fields=['brand','name','modelNumber','colour','storage'];const proposed={};for(const f of fields){const value=clean(input[f]);if(value)proposed[f]=value;}return {state:evidence.length?'proposed':'unavailable',requiresStaffConfirmation:true,proposed,evidence,warning:!evidence.length?'No image/label evidence supplied':null};}
function testSession(checks=[]){return arr(checks).map(c=>({name:clean(c.name)||'Unnamed check',state:['pass','fail','unsupported','unavailable'].includes(c.state)?c.state:'unavailable',automated:c.automated===true&&c.platformVerified===true,note:clean(c.note)||null}));}
function novaAction(input={}){if(!contracts?.action)return {status:'unavailable',reason:'Action contracts not loaded'};const a=contracts.action(input);return Object.freeze({...a,requiresHumanApproval:contracts.requiresHumanApproval(a),guardianBoundary:a.classification===contracts.ACTION_CLASSES.PROTECTED});}
return Object.freeze({canonicalDevice,deviceKey,catalogueFindings,pricingObservation,pricingRecommendation,sellSpeed,marketplaceMatch,smartAlerts,identificationProposal,testSession,novaAction});
});
