(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let sourceHealth=null;
function loadCss(){if(q('#morleyMarketplaceManagerCss'))return;const l=document.createElement('link');l.id='morleyMarketplaceManagerCss';l.rel='stylesheet';l.href='marketplace-manager.css?v=1';document.head.appendChild(l)}
function script(id,src,done){if(q('#'+id)){done?.();return}const s=document.createElement('script');s.id=id;s.src=src;s.async=false;s.onload=()=>done?.();document.body.appendChild(s)}
function loadModel(done){if(window.MorleyMarketplaceManager)return done();const existing=q('#morleyMarketplaceManagerModel');if(existing){const wait=()=>window.MorleyMarketplaceManager?done():setTimeout(wait,40);wait();return}script('morleyMarketplaceManagerModel','marketplace-manager-model.js?v=1',done)}
function loadReconciliation(done){const live=()=>window.MorleyMarketplaceLiveSource?done():script('morleyMarketplaceLiveSource','marketplace-live-source.js?v=1',done);const adapter=()=>window.MorleyMarketplaceReconciliation?live():script('morleyMarketplaceReconciliationAdapter','marketplace-reconciliation-adapter.js?v=1',live);if(window.MorleyMarketplaceSource)return adapter();script('morleyMarketplaceSource','marketplace-reconciliation-source.js?v=2',adapter)}
function ensureUi(){const panel=q('#tab-devices');if(!panel||q('#morleyMarketplaceManager'))return;const wrap=document.createElement('section');wrap.id='morleyMarketplaceManager';wrap.className='mmm-centre';wrap.innerHTML='<div class="mmm-head"><div><span class="mmm-kicker">MARKETPLACE MANAGER</span><h2>Listing Reconciliation</h2><p>Evidence-backed matching and exceptions. Reconciliation never deletes a listing.</p></div><button type="button" id="mmmRefresh" class="ghost">Refresh sources</button></div><div id="mmmSource" class="mmm-note">Live source health has not been checked yet.</div><div id="mmmCounts" class="mmm-counts"></div><div class="mmm-tools"><input id="mmmSearch" placeholder="Search stock number, listing title or URL"><select id="mmmStatus"><option value="all">All statuses</option></select><button type="button" id="mmmClear" class="ghost">Clear</button></div><div id="mmmList"></div><div class="mmm-note">Any destructive marketplace action remains separately approval-gated and is not performed by this reconciliation surface.</div>';const autopilot=q('#morleyCatalogueAutopilot',panel);autopilot?.insertAdjacentElement('afterend',wrap)||panel.prepend(wrap);q('#mmmRefresh',wrap).onclick=refreshSources;q('#mmmSearch',wrap).oninput=render;q('#mmmStatus',wrap).onchange=render;q('#mmmClear',wrap).onclick=()=>{q('#mmmSearch',wrap).value='';q('#mmmStatus',wrap).value='all';render()};}
function countCard(label,value){const a=document.createElement('article');a.className='mmm-count';a.innerHTML=`<span>${label}</span><strong>${value}</strong>`;return a}
function label(s){return String(s||'unknown').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function renderSource(){const el=q('#mmmSource');if(!el)return;if(!sourceHealth){el.textContent='Live source health has not been checked yet.';return}const h=sourceHealth.sourceHealth||{},cash=h.cash_converters||{},gum=h.gumtree||{};const stamp=sourceHealth.checkedAt?new Date(sourceHealth.checkedAt).toLocaleString():'time unavailable';if(sourceHealth.state==='confirmed'){el.textContent=`Authoritative snapshot confirmed · Cash Converters ${cash.rows??sourceHealth.stockCount??'—'}/${cash.total??'—'} · Gumtree ${gum.rows??sourceHealth.listingCount??'—'}/${gum.total??'—'} · ${stamp}`;return}el.textContent=`Reconciliation unavailable · Cash Converters ${cash.state||'unavailable'}${cash.total!=null?` ${cash.rows||0}/${cash.total}`:''} · Gumtree ${gum.state||'unavailable'}${gum.total!=null?` ${gum.rows||0}/${gum.total}`:''} · ${sourceHealth.note||'Both complete sources are required.'}`}
async function refreshSources(){const button=q('#mmmRefresh');if(button)button.disabled=true;try{sourceHealth=await window.MorleyMarketplaceLiveSource?.refresh?.()||{state:'unavailable',note:'Live source adapter unavailable'};renderSource();render()}finally{if(button)button.disabled=false}}
function render(){if(!window.MorleyMarketplaceManager||!window.MorleyIntelligenceRuntime)return;ensureUi();renderSource();const snap=window.MorleyIntelligenceRuntime.snapshot(),raw=Array.isArray(snap.marketplace)?snap.marketplace:[];const select=q('#mmmStatus'),search=q('#mmmSearch');if(select&&select.options.length===1){for(const s of window.MorleyMarketplaceManager.statuses(raw)){const o=document.createElement('option');o.value=s;o.textContent=label(s);select.appendChild(o)}}const model=window.MorleyMarketplaceManager.build(raw,{status:select?.value||'all',query:search?.value||''});const counts=q('#mmmCounts'),list=q('#mmmList');if(!counts||!list)return;counts.replaceChildren(countCard('TOTAL',model.counts.total||0),countCard('MATCHED',model.counts.matched||0),countCard('MISSING',model.counts.missing_listing||0),countCard('EXCEPTIONS',(model.counts.price_mismatch||0)+(model.counts.uncertain_match||0)+(model.counts.unmatched_listing||0)+(model.counts.duplicate||0)));if(model.state==='unavailable'){list.innerHTML='<div class="mmm-empty">No complete authoritative Cash Converters ↔ Gumtree snapshot is available. Partial or blank sources are never treated as zero listings.</div>';return}if(!model.rows.length){list.innerHTML='<div class="mmm-empty">No marketplace rows match the current filters.</div>';return}const box=document.createElement('div');box.className='mmm-list';for(const row of model.rows){const article=document.createElement('article');article.className='mmm-row';const title=row.stockNumber?`Stock ${esc(row.stockNumber)}`:esc(row.listing?.title||'Unmatched listing');const listingTitle=esc(row.listing?.title||'Listing unavailable');const url=esc(row.listing?.url||'URL unavailable');article.innerHTML=`<div class="mmm-row-head"><div><h3>${title}</h3><div class="mmm-meta">${listingTitle}<br>${url}</div></div><span class="mmm-pill">${label(row.status)}</span></div><div class="mmm-proposal"><strong>Proposed next step:</strong> ${esc(row.action.label)} · ${esc(row.action.classification)} · non-destructive</div>`;box.appendChild(article)}list.replaceChildren(box)}
function boot(){loadCss();loadModel(()=>loadReconciliation(()=>{ensureUi();window.addEventListener('morley:intelligence-updated',render);window.addEventListener('morley:marketplace-source-health',e=>{sourceHealth=e.detail;renderSource()});render();refreshSources()}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,550),{once:true});else setTimeout(boot,550);
})();
