(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function ai(){return window.MorleyAI}
async function pricingInvoke(body){const {data,error}=await sb.functions.invoke('admin-pricing-control',{body});if(error)throw error;if(data?.error)throw new Error(String(data.error));return data}
async function guardianHealth(){const [{data:settings,error:se},{data:incidents,error:ie}]=await Promise.all([sb.from('guardian_settings').select('*').limit(1).maybeSingle(),sb.from('guardian_incidents').select('id,state,updated_at,created_at,last_seen_at,risk_level,requires_approval,source,occurrence_count').order('updated_at',{ascending:false}).limit(100)]);if(se)throw se;if(ie)throw ie;const rows=incidents||[],open=rows.filter(i=>!['resolved','ignored'].includes(String(i.state||'').toLowerCase())),cutoff=Date.now()-86400000,stale=open.filter(i=>new Date(i.updated_at||i.created_at||0).getTime()<cutoff),approval=open.filter(i=>i.requires_approval),latest=rows[0]?.last_seen_at||rows[0]?.updated_at||rows[0]?.created_at||null;return{settings:settings||{},open_count:open.length,stale_open_count:stale.length,approval_required_count:approval.length,latest_incident_at:latest,kill_switch:!!settings?.kill_switch,enabled:settings?.enabled!==false,mode:settings?.mode||settings?.operating_mode||'observe'}}
async function guardianDiagnostics(){const {data,error}=await sb.from('guardian_incidents').select('id,state,risk_level,classification,confidence,diagnosis_summary,proposed_action,requires_approval,diagnostic_kind,diagnostic_message,route,app_version,occurrence_count,last_seen_at,updated_at').order('updated_at',{ascending:false}).limit(50);if(error)throw error;const rows=data||[],open=rows.filter(i=>!['resolved','ignored'].includes(String(i.state||'').toLowerCase()));return{open_count:open.length,high_risk_count:open.filter(i=>['high','critical'].includes(String(i.risk_level||'').toLowerCase())).length,approval_required_count:open.filter(i=>i.requires_approval).length,recent:open.slice(0,10).map(i=>({id:i.id,risk:i.risk_level,state:i.state,classification:i.classification,confidence:i.confidence,diagnosis:i.diagnosis_summary||i.diagnostic_message||'No diagnosis yet',proposed_action:i.proposed_action||null,route:i.route||null,app_version:i.app_version||null,occurrences:i.occurrence_count||1,last_seen_at:i.last_seen_at||i.updated_at}))}}
async function supportSummary(){const {data,error}=await sb.from('support_tickets').select('id,status,priority,category,updated_at,sla_due_at,subject').order('updated_at',{ascending:false}).limit(100);if(error)throw error;const rows=data||[],active=rows.filter(t=>!['resolved','closed'].includes(t.status)),overdue=active.filter(t=>t.sla_due_at&&new Date(t.sla_due_at).getTime()<Date.now());return{total_recent:rows.length,active_count:active.length,urgent_count:active.filter(t=>t.priority==='urgent').length,high_count:active.filter(t=>t.priority==='high').length,sla_overdue_count:overdue.length,recent:active.slice(0,8)}}
async function releaseSummary(){const {data,error}=await sb.from('app_config').select('key,value').in('key',['current_release','minimum_supported_version','feature_flags']);if(error)throw error;return Object.fromEntries((data||[]).map(x=>[x.key,x.value]))}
async function catalogueSummary(){const {data,error}=await sb.from('device_catalog').select('id,category,brand,model_name,model_number,release_year,ram_options,storage_options,active,updated_at').eq('active',true).order('release_year',{ascending:false}).limit(1000);if(error)throw error;const rows=data||[],counts={};for(const r of rows)counts[r.category]=(counts[r.category]||0)+1;return{active_count:rows.length,by_category:counts,missing_model_number:rows.filter(r=>!r.model_number).length,missing_storage:rows.filter(r=>!Array.isArray(r.storage_options)||r.storage_options.length===0).length,missing_ram_nonapple_phone:rows.filter(r=>r.category==='mobile_phone'&&String(r.brand||'').toLowerCase()!=='apple'&&(!Array.isArray(r.ram_options)||r.ram_options.length===0)).length,newest:rows.slice(0,12).map(r=>({brand:r.brand,model:r.model_name,model_number:r.model_number,year:r.release_year,category:r.category}))}}
async function catalogueSearch(input){const q=String(input.query||'').trim();if(!q)return{query:q,matches:[]};const safe=q.replace(/[%_,]/g,' ').trim();const {data,error}=await sb.from('device_catalog').select('id,category,brand,family,model_name,model_number,release_year,ram_options,storage_options,market_region,source_name').eq('active',true).or(`model_name.ilike.%${safe}%,brand.ilike.%${safe}%,family.ilike.%${safe}%,model_number.ilike.%${safe}%`).limit(20);if(error)throw error;return{query:q,matches:data||[]}}
async function valuationSummary(){const {data,error}=await sb.from('valuation_history').select('id,item_type,item_summary,item_grade,asking_price,market_value,max_buy,expected_profit,confidence,status,bought_price,sold_price,actual_profit,created_at,updated_at').order('created_at',{ascending:false}).limit(250);if(error)throw error;const rows=data||[],closed=rows.filter(v=>v.sold_price!=null||String(v.status||'').toLowerCase()==='sold'),actual=closed.filter(v=>v.actual_profit!=null),open=rows.filter(v=>!['sold','closed','rejected'].includes(String(v.status||'').toLowerCase()));const avg=(arr,key)=>arr.length?arr.reduce((s,x)=>s+(Number(x[key])||0),0)/arr.length:0;return{recent_count:rows.length,open_count:open.length,sold_count:closed.length,average_market_value:avg(rows.filter(v=>v.market_value!=null),'market_value'),average_expected_profit:avg(rows.filter(v=>v.expected_profit!=null),'expected_profit'),average_actual_profit:avg(actual,'actual_profit'),recent:rows.slice(0,10)}}
function registerCapabilities(){if(!ai())return;
ai().register({id:'pricing.list',label:'Read pricing catalogue',domain:'pricing',risk:ai().RISK.READ,execute:async()=>pricingInvoke({action:'list'})});
ai().register({id:'pricing.preview',label:'Preview pricing instructions',domain:'pricing',risk:ai().RISK.READ,execute:async input=>pricingInvoke({action:'assistant_preview',text:String(input.text||'')})});
ai().register({id:'pricing.apply',label:'Apply protected pricing update',domain:'pricing',risk:ai().RISK.PROTECTED,describe:i=>`Apply ${i.brand||''} ${i.model||''} ${i.storage||''} at AUD ${i.price_aud??''}`.trim(),execute:async input=>pricingInvoke({action:'update',...input})});
ai().register({id:'guardian.health',label:'Read Guardian health and incidents',domain:'guardian',risk:ai().RISK.READ,execute:guardianHealth});
ai().register({id:'guardian.diagnostics',label:'Inspect Guardian diagnoses and proposed actions',domain:'guardian',risk:ai().RISK.READ,execute:guardianDiagnostics});
ai().register({id:'support.summary',label:'Read support queue health',domain:'support',risk:ai().RISK.READ,execute:supportSummary});
ai().register({id:'release.summary',label:'Read release and feature state',domain:'release',risk:ai().RISK.READ,execute:releaseSummary});
ai().register({id:'catalogue.summary',label:'Read device catalogue intelligence',domain:'catalogue',risk:ai().RISK.READ,execute:catalogueSummary});
ai().register({id:'catalogue.search',label:'Search live device catalogue',domain:'catalogue',risk:ai().RISK.READ,execute:catalogueSearch});
ai().register({id:'valuation.summary',label:'Read valuation performance intelligence',domain:'valuations',risk:ai().RISK.READ,execute:valuationSummary});
ai().register({id:'system.capabilities',label:'Inspect Morley AI capabilities',domain:'system',risk:ai().RISK.READ,execute:async()=>ai().context()});
}
function renderCapabilities(){const host=$('morleyAiCapabilities');if(!host||!ai())return;host.innerHTML=ai().list().map(c=>`<div class="row"><div class="row-main"><div class="row-title">${esc(c.label)}</div><div class="muted">${esc(c.domain||'system')} • ${esc(c.risk)}</div></div></div>`).join('')}
function addBubble(role,text){const host=$('morleyAiConversation');if(!host)return;const div=document.createElement('div');div.className='card';div.style.margin='10px 0';div.innerHTML=`<strong>${role==='user'?'You':'Morley AI'}</strong><div style="margin-top:6px;white-space:pre-wrap">${esc(text)}</div>`;host.appendChild(div);host.scrollTop=host.scrollHeight}
async function overview(){const [g,s,r,p,c,v]=await Promise.allSettled([ai().run('guardian.health'),ai().run('support.summary'),ai().run('release.summary'),ai().run('pricing.list'),ai().run('catalogue.summary'),ai().run('valuation.summary')]);const lines=[];if(g.status==='fulfilled'){const x=g.value.result;lines.push(`Guardian: ${x.kill_switch?'KILL SWITCH':x.enabled?String(x.mode).toUpperCase():'PAUSED'} • ${x.open_count} open incident(s) • ${x.approval_required_count} need approval • ${x.stale_open_count} stale.`)}else lines.push('Guardian: live health unavailable.');if(s.status==='fulfilled'){const x=s.value.result;lines.push(`Support: ${x.active_count} active ticket(s) • ${x.urgent_count} urgent • ${x.high_count} high • ${x.sla_overdue_count} SLA overdue.`)}else lines.push('Support: queue summary unavailable.');if(r.status==='fulfilled'){const x=r.value.result;lines.push(`Release: ${x.current_release?.versionName||'unknown'} • minimum ${x.minimum_supported_version?.versionName||'unknown'}${x.minimum_supported_version?.forceUpdate?' • forced minimum':''}.`)}else lines.push('Release: state unavailable.');if(p.status==='fulfilled'){const x=p.value.result?.items||[];lines.push(`Pricing: ${x.length} device/storage slot(s) loaded • ${x.filter(i=>i.price_aud==null).length} currently unpriced.`)}else lines.push('Pricing: catalogue summary unavailable.');if(c.status==='fulfilled'){const x=c.value.result;lines.push(`Catalogue: ${x.active_count} active devices • ${x.missing_model_number} missing model number • ${x.missing_storage} missing storage • ${x.missing_ram_nonapple_phone} non-Apple phone RAM gaps.`)}else lines.push('Catalogue: intelligence unavailable.');if(v.status==='fulfilled'){const x=v.value.result;lines.push(`Valuations: ${x.open_count} open • ${x.sold_count} sold in recent history • avg expected profit AUD ${Math.round(x.average_expected_profit||0)} • avg actual profit AUD ${Math.round(x.average_actual_profit||0)}.`)}else lines.push('Valuations: intelligence unavailable.');return lines.join('\n')}
async function handlePrompt(){const input=$('morleyAiInput'),status=$('morleyAiStatus');const text=input?.value.trim();if(!text)return;addBubble('user',text);input.value='';status.textContent='Thinking with live Morley capabilities…';try{const lower=text.toLowerCase();if(/price|pricing/.test(lower)&&(/\$|aud|iphone|galaxy|pixel|oppo|motorola|samsung/.test(lower))){const r=await ai().run('pricing.preview',{text});const ps=r.result?.proposals||[];if(!ps.length)addBubble('ai','I could not produce a confident pricing match from that instruction. I have not changed anything.');else addBubble('ai',ps.map((p,i)=>p.error?`${i+1}. ${p.input}: ${p.error}`:`${i+1}. ${p.device?.brand||''} ${p.device?.model||''} ${p.storage||''} — AUD ${p.price_aud} — ${Math.round((p.confidence||0)*100)}% match`).join('\n')+'\n\nThese are proposals only. Protected pricing still requires explicit approval.');}
else if(/guardian|bug|incident|repair|diagnos/.test(lower)){const r=await ai().run(/diagnos|why|detail|problem/.test(lower)?'guardian.diagnostics':'guardian.health'),x=r.result;if(r.capability==='guardian.diagnostics'){addBubble('ai',`Guardian has ${x.open_count} open incidents, ${x.high_risk_count} high/critical and ${x.approval_required_count} awaiting approval.\n`+(x.recent||[]).slice(0,6).map(i=>`• ${String(i.risk||'unknown').toUpperCase()} ${i.state||''}: ${i.diagnosis}${i.proposed_action?`\n  Proposed: ${i.proposed_action}`:''}${i.occurrences>1?` • ${i.occurrences} occurrences`:''}`).join('\n'));}else addBubble('ai',`Guardian is ${x.kill_switch?'under KILL SWITCH':x.enabled?String(x.mode).toUpperCase():'PAUSED'}. There are ${x.open_count} open incidents, ${x.approval_required_count} requiring human approval and ${x.stale_open_count} stale over 24 hours. I can inspect Guardian state, but protected repair execution remains human-approved.`);}
else if(/catalog|device|model|hardware/.test(lower)){if(/find|search|have|got|is there|lookup|look up/.test(lower)){const q=text.replace(/^(find|search|lookup|look up|do we have|have we got|is there)\s+/i,'').trim();const r=await ai().run('catalogue.search',{query:q}),m=r.result?.matches||[];addBubble('ai',m.length?`Catalogue matches for “${q}”:\n`+m.slice(0,10).map(x=>`• ${x.brand} ${x.model_name}${x.model_number?` (${x.model_number})`:''} • ${x.release_year||'year unknown'} • ${x.category}`).join('\n'):'No active catalogue matches found. I have not created or changed any record.');}else{const r=await ai().run('catalogue.summary'),x=r.result;addBubble('ai',`Live catalogue: ${x.active_count} active devices. ${x.missing_model_number} are missing model numbers, ${x.missing_storage} are missing storage, and ${x.missing_ram_nonapple_phone} non-Apple phones are missing RAM.\nBy category: `+Object.entries(x.by_category||{}).map(([k,v])=>`${k} ${v}`).join(' • '));}}
else if(/valuation|value|profit|buy price|margin/.test(lower)){const r=await ai().run('valuation.summary'),x=r.result;addBubble('ai',`Recent valuation intelligence: ${x.open_count} open valuations and ${x.sold_count} sold records. Average market value is AUD ${Math.round(x.average_market_value||0)}, average expected profit AUD ${Math.round(x.average_expected_profit||0)}, and average realised profit AUD ${Math.round(x.average_actual_profit||0)}.\n`+(x.recent||[]).slice(0,5).map(v=>`• ${v.item_summary||v.item_type||'Item'} — market AUD ${v.market_value??'—'} • max buy AUD ${v.max_buy??'—'} • ${v.status||'status unknown'}`).join('\n'));}
else if(/support|ticket|sla/.test(lower)){const r=await ai().run('support.summary'),x=r.result;addBubble('ai',`Support currently has ${x.active_count} active tickets: ${x.urgent_count} urgent, ${x.high_count} high priority and ${x.sla_overdue_count} SLA overdue.\n`+(x.recent||[]).slice(0,5).map(t=>`• ${t.subject} — ${t.priority||'normal'} — ${t.status}`).join('\n'));}
else if(/release|version|update|feature flag/.test(lower)){const r=await ai().run('release.summary'),x=r.result;addBubble('ai',`Current release: ${x.current_release?.versionName||'unknown'} (${x.current_release?.versionCode||'—'}). Minimum supported: ${x.minimum_supported_version?.versionName||'unknown'}${x.minimum_supported_version?.forceUpdate?' with forced updates below minimum':''}.`);}
else if(/what can you do|capabilit|help/.test(lower)){const caps=ai().list();addBubble('ai','Connected Morley AI capabilities:\n'+caps.map(c=>`• ${c.label} (${c.risk})`).join('\n')+'\n\nProtected and critical writes continue to require explicit approval.');}
else if(/status|everything|overview|health|today|attention/.test(lower)){addBubble('ai',await overview());}
else addBubble('ai','I understand the request, but that domain is not yet attached to a registered Morley AI capability. I will not invent access or make an untracked change. Inventory/sales intelligence and protected catalogue/valuation write skills are the next capabilities to connect.');status.textContent='Ready.'}catch(e){status.textContent=e?.message||String(e);addBubble('ai','That request could not be completed safely. No protected change was made.')}
}
function wire(){registerCapabilities();renderCapabilities();$('morleyAiSendBtn')?.addEventListener('click',handlePrompt);$('morleyAiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handlePrompt()}});document.querySelector('[data-tab="ai"]')?.addEventListener('click',renderCapabilities)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
