(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function ai(){return window.MorleyAI}
async function pricingInvoke(body){const {data,error}=await sb.functions.invoke('admin-pricing-control',{body});if(error)throw error;if(data?.error)throw new Error(String(data.error));return data}
async function guardianHealth(){const [{data:settings,error:se},{data:incidents,error:ie}]=await Promise.all([sb.from('guardian_settings').select('*').limit(1).maybeSingle(),sb.from('guardian_incidents').select('id,state,updated_at,created_at,last_seen_at,risk_level,requires_approval,source,occurrence_count').order('updated_at',{ascending:false}).limit(100)]);if(se)throw se;if(ie)throw ie;const rows=incidents||[],open=rows.filter(i=>!['resolved','ignored'].includes(String(i.state||'').toLowerCase())),cutoff=Date.now()-86400000,stale=open.filter(i=>new Date(i.updated_at||i.created_at||0).getTime()<cutoff),approval=open.filter(i=>i.requires_approval),latest=rows[0]?.last_seen_at||rows[0]?.updated_at||rows[0]?.created_at||null;return{settings:settings||{},open_count:open.length,stale_open_count:stale.length,approval_required_count:approval.length,latest_incident_at:latest,kill_switch:!!settings?.kill_switch,enabled:settings?.enabled!==false,mode:settings?.mode||settings?.operating_mode||'observe'}}
async function supportSummary(){const {data,error}=await sb.from('support_tickets').select('id,status,priority,category,updated_at,sla_due_at,subject').order('updated_at',{ascending:false}).limit(100);if(error)throw error;const rows=data||[],active=rows.filter(t=>!['resolved','closed'].includes(t.status)),overdue=active.filter(t=>t.sla_due_at&&new Date(t.sla_due_at).getTime()<Date.now());return{total_recent:rows.length,active_count:active.length,urgent_count:active.filter(t=>t.priority==='urgent').length,high_count:active.filter(t=>t.priority==='high').length,sla_overdue_count:overdue.length,recent:active.slice(0,8)}}
async function releaseSummary(){const {data,error}=await sb.from('app_config').select('key,value').in('key',['current_release','minimum_supported_version','feature_flags']);if(error)throw error;return Object.fromEntries((data||[]).map(x=>[x.key,x.value]))}
function registerCapabilities(){if(!ai())return;
ai().register({id:'pricing.list',label:'Read pricing catalogue',domain:'pricing',risk:ai().RISK.READ,execute:async()=>pricingInvoke({action:'list'})});
ai().register({id:'pricing.preview',label:'Preview pricing instructions',domain:'pricing',risk:ai().RISK.READ,execute:async input=>pricingInvoke({action:'assistant_preview',text:String(input.text||'')})});
ai().register({id:'pricing.apply',label:'Apply protected pricing update',domain:'pricing',risk:ai().RISK.PROTECTED,describe:i=>`Apply ${i.brand||''} ${i.model||''} ${i.storage||''} at AUD ${i.price_aud??''}`.trim(),execute:async input=>pricingInvoke({action:'update',...input})});
ai().register({id:'guardian.health',label:'Read Guardian health and incidents',domain:'guardian',risk:ai().RISK.READ,execute:guardianHealth});
ai().register({id:'support.summary',label:'Read support queue health',domain:'support',risk:ai().RISK.READ,execute:supportSummary});
ai().register({id:'release.summary',label:'Read release and feature state',domain:'release',risk:ai().RISK.READ,execute:releaseSummary});
ai().register({id:'system.capabilities',label:'Inspect Morley AI capabilities',domain:'system',risk:ai().RISK.READ,execute:async()=>ai().context()});
}
function renderCapabilities(){const host=$('morleyAiCapabilities');if(!host||!ai())return;host.innerHTML=ai().list().map(c=>`<div class="row"><div class="row-main"><div class="row-title">${esc(c.label)}</div><div class="muted">${esc(c.domain||'system')} • ${esc(c.risk)}</div></div></div>`).join('')}
function addBubble(role,text){const host=$('morleyAiConversation');if(!host)return;const div=document.createElement('div');div.className='card';div.style.margin='10px 0';div.innerHTML=`<strong>${role==='user'?'You':'Morley AI'}</strong><div style="margin-top:6px;white-space:pre-wrap">${esc(text)}</div>`;host.appendChild(div);host.scrollTop=host.scrollHeight}
async function overview(){const [g,s,r,p]=await Promise.allSettled([ai().run('guardian.health'),ai().run('support.summary'),ai().run('release.summary'),ai().run('pricing.list')]);const lines=[];if(g.status==='fulfilled'){const x=g.value.result;lines.push(`Guardian: ${x.kill_switch?'KILL SWITCH':x.enabled?String(x.mode).toUpperCase():'PAUSED'} • ${x.open_count} open incident(s) • ${x.approval_required_count} need approval • ${x.stale_open_count} stale.`)}else lines.push('Guardian: live health unavailable.');if(s.status==='fulfilled'){const x=s.value.result;lines.push(`Support: ${x.active_count} active ticket(s) • ${x.urgent_count} urgent • ${x.high_count} high • ${x.sla_overdue_count} SLA overdue.`)}else lines.push('Support: queue summary unavailable.');if(r.status==='fulfilled'){const x=r.value.result;lines.push(`Release: ${x.current_release?.versionName||'unknown'} • minimum ${x.minimum_supported_version?.versionName||'unknown'}${x.minimum_supported_version?.forceUpdate?' • forced minimum':''}.`)}else lines.push('Release: state unavailable.');if(p.status==='fulfilled'){const x=p.value.result?.items||[];lines.push(`Pricing: ${x.length} device/storage slot(s) loaded • ${x.filter(i=>i.price_aud==null).length} currently unpriced.`)}else lines.push('Pricing: catalogue summary unavailable.');return lines.join('\n')}
async function handlePrompt(){const input=$('morleyAiInput'),status=$('morleyAiStatus');const text=input?.value.trim();if(!text)return;addBubble('user',text);input.value='';status.textContent='Thinking with live Morley capabilities…';try{const lower=text.toLowerCase();if(/price|pricing/.test(lower)&&(/\$|aud|iphone|galaxy|pixel|oppo|motorola|samsung/.test(lower))){const r=await ai().run('pricing.preview',{text});const ps=r.result?.proposals||[];if(!ps.length)addBubble('ai','I could not produce a confident pricing match from that instruction. I have not changed anything.');else addBubble('ai',ps.map((p,i)=>p.error?`${i+1}. ${p.input}: ${p.error}`:`${i+1}. ${p.device?.brand||''} ${p.device?.model||''} ${p.storage||''} — AUD ${p.price_aud} — ${Math.round((p.confidence||0)*100)}% match`).join('\n')+'\n\nThese are proposals only. Protected pricing still requires explicit approval.');}
else if(/guardian|bug|incident|repair/.test(lower)){const r=await ai().run('guardian.health'),x=r.result;addBubble('ai',`Guardian is ${x.kill_switch?'under KILL SWITCH':x.enabled?String(x.mode).toUpperCase():'PAUSED'}. There are ${x.open_count} open incidents, ${x.approval_required_count} requiring human approval and ${x.stale_open_count} stale over 24 hours. I can inspect Guardian state, but protected repair execution remains human-approved.`);}
else if(/support|ticket|sla/.test(lower)){const r=await ai().run('support.summary'),x=r.result;addBubble('ai',`Support currently has ${x.active_count} active tickets: ${x.urgent_count} urgent, ${x.high_count} high priority and ${x.sla_overdue_count} SLA overdue.\n`+(x.recent||[]).slice(0,5).map(t=>`• ${t.subject} — ${t.priority||'normal'} — ${t.status}`).join('\n'));}
else if(/release|version|update|feature flag/.test(lower)){const r=await ai().run('release.summary'),x=r.result;addBubble('ai',`Current release: ${x.current_release?.versionName||'unknown'} (${x.current_release?.versionCode||'—'}). Minimum supported: ${x.minimum_supported_version?.versionName||'unknown'}${x.minimum_supported_version?.forceUpdate?' with forced updates below minimum':''}.`);}
else if(/what can you do|capabilit|help/.test(lower)){const caps=ai().list();addBubble('ai','Connected Morley AI capabilities:\n'+caps.map(c=>`• ${c.label} (${c.risk})`).join('\n')+'\n\nProtected and critical writes continue to require explicit approval.');}
else if(/status|everything|overview|health|today|attention/.test(lower)){addBubble('ai',await overview());}
else addBubble('ai','I understand the request, but that domain is not yet attached to a registered Morley AI capability. I will not invent access or make an untracked change. Catalogue mutation, valuation, inventory and release-write skills are the next protected capabilities to connect.');status.textContent='Ready.'}catch(e){status.textContent=e?.message||String(e);addBubble('ai','That request could not be completed safely. No protected change was made.')}
}
function wire(){registerCapabilities();renderCapabilities();$('morleyAiSendBtn')?.addEventListener('click',handlePrompt);$('morleyAiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handlePrompt()}});document.querySelector('[data-tab="ai"]')?.addEventListener('click',renderCapabilities)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
