(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function ai(){return window.MorleyAI}
async function pricingInvoke(body){const {data,error}=await sb.functions.invoke('admin-pricing-control',{body});if(error)throw error;if(data?.error)throw new Error(String(data.error));return data}
function registerCapabilities(){if(!ai())return;
ai().register({id:'pricing.list',label:'Read pricing catalogue',domain:'pricing',risk:ai().RISK.READ,execute:async()=>pricingInvoke({action:'list'})});
ai().register({id:'pricing.preview',label:'Preview pricing instructions',domain:'pricing',risk:ai().RISK.READ,execute:async input=>pricingInvoke({action:'assistant_preview',text:String(input.text||'')})});
ai().register({id:'pricing.apply',label:'Apply protected pricing update',domain:'pricing',risk:ai().RISK.PROTECTED,describe:i=>`Apply ${i.brand||''} ${i.model||''} ${i.storage||''} at AUD ${i.price_aud??''}`.trim(),execute:async input=>pricingInvoke({action:'update',...input})});
ai().register({id:'system.capabilities',label:'Inspect Morley AI capabilities',domain:'system',risk:ai().RISK.READ,execute:async()=>ai().context()});
}
function renderCapabilities(){const host=$('morleyAiCapabilities');if(!host||!ai())return;host.innerHTML=ai().list().map(c=>`<div class="row"><div class="row-main"><div class="row-title">${esc(c.label)}</div><div class="muted">${esc(c.domain||'system')} • ${esc(c.risk)}</div></div></div>`).join('')}
function addBubble(role,text){const host=$('morleyAiConversation');if(!host)return;const div=document.createElement('div');div.className='card';div.style.margin='10px 0';div.innerHTML=`<strong>${role==='user'?'You':'Morley AI'}</strong><div style="margin-top:6px;white-space:pre-wrap">${esc(text)}</div>`;host.appendChild(div);host.scrollTop=host.scrollHeight}
async function handlePrompt(){const input=$('morleyAiInput'),status=$('morleyAiStatus');const text=input?.value.trim();if(!text)return;addBubble('user',text);input.value='';status.textContent='Thinking with live Morley capabilities…';try{const lower=text.toLowerCase();if(/price|pricing/.test(lower)&&(/\$|aud|iphone|galaxy|pixel|oppo|motorola|samsung/.test(lower))){const r=await ai().run('pricing.preview',{text});const ps=r.result?.proposals||[];if(!ps.length)addBubble('ai','I could not produce a confident pricing match from that instruction. I have not changed anything.');else addBubble('ai',ps.map((p,i)=>p.error?`${i+1}. ${p.input}: ${p.error}`:`${i+1}. ${p.device?.brand||''} ${p.device?.model||''} ${p.storage||''} — AUD ${p.price_aud} — ${Math.round((p.confidence||0)*100)}% match`).join('\n')+'\n\nThese are proposals only. Protected pricing still requires approval in Pricing.');}
else if(/what can you do|capabilit|help/.test(lower)){const caps=ai().list();addBubble('ai','I currently have these registered capabilities:\n'+caps.map(c=>`• ${c.label} (${c.risk})`).join('\n')+'\n\nGuardian, catalogue, support, valuation, inventory and release skills will attach through the same protected registry as their server tools are exposed.');}
else if(/status|everything|overview|health/.test(lower)){const ctx=await ai().run('system.capabilities');addBubble('ai',`Morley AI core is active with ${ctx.result.capabilities.length} registered capabilities. Protected and critical actions require approval. I can already inspect and preview pricing safely; the next connected skills are Guardian diagnostics, catalogue intelligence, support, valuations, inventory and release readiness.`);}
else addBubble('ai','I understand the request, but that domain is not connected to a registered Morley AI capability yet. I will not simulate a tool or make an untracked change. Use Pricing now, while the remaining protected skills are wired into this same brain.');status.textContent='Ready.'}catch(e){status.textContent=e?.message||String(e);addBubble('ai','That request could not be completed safely. No protected change was made.')}
}
function wire(){registerCapabilities();renderCapabilities();$('morleyAiSendBtn')?.addEventListener('click',handlePrompt);$('morleyAiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handlePrompt()}});document.querySelector('[data-tab="ai"]')?.addEventListener('click',renderCapabilities)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
