(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v)=>{if(!v)return'Unknown';const d=new Date(v);return Number.isNaN(d.getTime())?'Unknown':d.toLocaleString()};
let points=[];
async function auditPreview(point,components){const sb=window.sb;if(!sb)return;const session=(await sb.auth.getSession())?.data?.session;if(!session?.user?.id)return;await sb.from('restore_events').insert({restore_point_id:point.id,event_type:'restore_previewed',components,details:{targetSourceSha:point.source_sha,requiresExplicitApproval:true},created_by:session.user.id})}
function preview(point){const components=Array.isArray(point.components)?point.components:[];const database=components.includes('database')||components.includes('supabase_schema');const note=database?'Database recovery requires a separately approved recovery plan. Schema/data rollback is never automatic.':'This preview affects only the selected application/deployment components. Production business data is not rolled back.';const target=q('#morleyRestorePreview');if(target)target.innerHTML=`<div class="admin-card"><h3>Restore preview</h3><p><strong>Target:</strong> ${esc(point.change_ref||point.source_sha)}</p><p><strong>Source:</strong> <code>${esc(point.source_sha)}</code></p><p><strong>Components:</strong> ${esc(components.join(', ')||'None')}</p><p>${esc(note)}</p><p><strong>Approval:</strong> Explicit authorised approval is required before any restore execution.</p></div>`;auditPreview(point,components).catch(()=>{})}
function render(){const host=q('#morleyRestoreCentre');if(!host)return;const rows=points.map((p,i)=>`<article class="admin-card" data-restore-id="${esc(p.id)}"><div class="admin-row"><div><strong>${esc(p.change_ref||'Restore point')}</strong><div class="muted">${fmt(p.created_at)} • ${esc(p.lifecycle_state||'captured')}</div></div><button type="button" class="btn secondary" data-preview="${i}">Preview restore</button></div><p><code>${esc(p.source_sha)}</code></p><p>${esc((Array.isArray(p.components)?p.components:[]).join(' • ')||'Repository')}</p></article>`).join('');host.innerHTML=`<section class="admin-home-section"><h2>Backups & Restore</h2><span>Known-good restore points</span></section><p class="muted">Major Morley changes create restore points before deployment. Restores are component-scoped and preview-first.</p><div id="morleyRestorePreview"></div><div class="admin-stack">${rows||'<div class="admin-card"><strong>No restore points yet</strong><p>The first protected deployment after this feature is enabled will create one.</p></div>'}</div>`;host.querySelectorAll('[data-preview]').forEach(btn=>btn.addEventListener('click',()=>preview(points[Number(btn.dataset.preview)])))}
async function load(){const host=q('#morleyRestoreCentre');if(!host||!window.sb)return;host.innerHTML='<div class="admin-card">Loading restore points…</div>';const {data,error}=await window.sb.from('restore_points').select('id,source_sha,change_ref,components,release_refs,web_refs,function_refs,migration_head,lifecycle_state,created_at').order('created_at',{ascending:false}).limit(50);if(error){host.innerHTML=`<div class="admin-card"><strong>Restore points unavailable</strong><p>${esc(error.message||'Could not load restore metadata.')}</p></div>`;return}points=Array.isArray(data)?data:[];render()}
function ensureHost(){if(q('#morleyRestoreCentre'))return q('#morleyRestoreCentre');const controls=q('#tab-controls')||q('#tab-release')||q('#tab-overview');if(!controls)return null;const host=document.createElement('section');host.id='morleyRestoreCentre';host.className='admin-restore-centre';controls.appendChild(host);return host}
function boot(){if(!ensureHost())return;load().catch(()=>{const host=q('#morleyRestoreCentre');if(host)host.innerHTML='<div class="admin-card"><strong>Restore points unavailable</strong><p>Retry after the Admin connection is restored.</p></div>'})}
window.MorleyRestoreCentre=Object.freeze({version:'1.0.0',reload:load,previewRestore:preview,requiresExplicitApproval:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0),{once:true});else setTimeout(boot,0);
})();
