(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s);
function clickTab(id){q(`.tabs .tab[data-tab="${id}"]`)?.click()}
function loadCss(){if(q('#morleySmartAlertsCss'))return;const l=document.createElement('link');l.id='morleySmartAlertsCss';l.rel='stylesheet';l.href='smart-alerts.css?v=1';document.head.appendChild(l)}
function loadModel(done){if(window.MorleySmartAlerts)return done();const existing=q('#morleySmartAlertsModel');if(existing){const wait=()=>window.MorleySmartAlerts?done():setTimeout(wait,40);wait();return}const s=document.createElement('script');s.id='morleySmartAlertsModel';s.src='smart-alerts-model.js?v=2';s.onload=done;document.body.appendChild(s)}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n}
async function refreshEvidence(){const b=q('#msaRefresh'),tasks=[];for(const fn of [window.MorleyDeviceIntelligenceAdapter?.refresh,window.MorleyPricingIntelligenceAdapter?.refresh,window.refreshMorleySupportIntelligenceEvidence,window.refreshMorleyReleaseIntelligenceEvidence,window.MorleyMarketplaceLiveSource?.refresh])if(typeof fn==='function')tasks.push(()=>fn());if(b){b.disabled=true;b.textContent='Refreshing…'}try{if(tasks.length)await Promise.allSettled(tasks.map(run=>Promise.resolve().then(run)));render()}finally{if(b){b.disabled=false;b.textContent='Refresh sources'}}}
function ensureUi(){const panel=q('#tab-overview');if(!panel||q('#morleySmartAlertsCentre'))return;const wrap=el('section','msa-centre');wrap.id='morleySmartAlertsCentre';const head=el('div','msa-head');const copy=el('div');copy.append(el('span','msa-kicker','SMART ALERTS'),el('h2','', 'Needs Attention'),el('p','', 'Evidence-backed catalogue, marketplace, support, release, source-health and system exceptions. Repeated alerts are deduplicated.'));const refresh=el('button','ghost','Refresh sources');refresh.type='button';refresh.id='msaRefresh';head.append(copy,refresh);const counts=el('div','msa-counts');counts.id='msaCounts';const tools=el('div','msa-tools');const sev=document.createElement('select');sev.id='msaSeverity';sev.append(new Option('All severities','all'));const typ=document.createElement('select');typ.id='msaType';typ.append(new Option('All sources','all'));const clear=el('button','ghost','Clear filters');clear.type='button';clear.id='msaClear';tools.append(sev,typ,clear);const list=el('div');list.id='msaList';wrap.append(head,counts,tools,list);const command=q('#morleyIntelligenceCentre',panel);command?command.insertAdjacentElement('afterend',wrap):panel.prepend(wrap);refresh.onclick=refreshEvidence;sev.onchange=render;typ.onchange=render;clear.onclick=()=>{sev.value='all';typ.value='all';render()}}
function countCard(label,value){const a=el('article','msa-count');a.append(el('span','',label),el('strong','',value));return a}
function pretty(v){return String(v||'unknown').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function detailText(row){const d=row.detail||{};if(row.type==='catalogue')return [d.deviceId&&`Device ${d.deviceId}`,d.field&&`Field ${d.field}`].filter(Boolean).join(' · ')||'Catalogue evidence requires review';if(row.type==='marketplace')return [d.stockNumber&&`Stock ${d.stockNumber}`,d.listing?.title].filter(Boolean).join(' · ')||'Marketplace reconciliation requires review';if(row.type==='system')return d.detail||d.message||'System evidence requires review';if(row.type==='support')return [d.priority&&`${pretty(d.priority)} priority`,d.status&&pretty(d.status),d.reason&&pretty(d.reason)].filter(Boolean).join(' · ')||'Support evidence requires review';if(row.type==='release')return [d.versionName&&`OTA ${d.versionName}`,d.versionCode!=null&&`code ${d.versionCode}`,d.reason&&pretty(d.reason)].filter(Boolean).join(' · ')||'Release evidence requires review';if(row.type==='source')return [d.state&&pretty(d.state),d.source,d.checkedAt&&`checked ${d.checkedAt}`].filter(Boolean).join(' · ')||'Required intelligence source needs attention';return 'Evidence requires review'}
function sourceHealthAlerts(snap){const health=window.MorleyIntelligenceSourceHealth?.analyse?.(snap?.sources||{});return window.MorleySmartAlerts?.fromSourceHealth?.(health)||[]}
function render(){if(!window.MorleySmartAlerts||!window.MorleyIntelligenceRuntime)return;ensureUi();const snap=window.MorleyIntelligenceRuntime.snapshot(),raw=[...(Array.isArray(snap.alerts)?snap.alerts:[]),...sourceHealthAlerts(snap)];const severity=q('#msaSeverity'),type=q('#msaType');if(severity){const wanted=severity.value||'all',values=window.MorleySmartAlerts.severities(raw);severity.replaceChildren(new Option('All severities','all'),...values.map(s=>new Option(pretty(s),s)));severity.value=values.includes(wanted)?wanted:'all'}if(type){const wanted=type.value||'all',values=window.MorleySmartAlerts.types(raw);type.replaceChildren(new Option('All sources','all'),...values.map(t=>new Option(pretty(t),t)));type.value=values.includes(wanted)?wanted:'all'}const model=window.MorleySmartAlerts.build(raw,{severity:severity?.value||'all',type:type?.value||'all'});const counts=q('#msaCounts'),list=q('#msaList');if(!counts||!list)return;counts.replaceChildren(countCard('TOTAL',model.counts.total||0),countCard('HIGH',(model.counts.high||0)+(model.counts.critical||0)),countCard('CATALOGUE',model.counts.catalogue||0),countCard('MARKETPLACE',model.counts.marketplace||0),countCard('SUPPORT',model.counts.support||0),countCard('RELEASE',model.counts.release||0),countCard('SOURCES',model.counts.source||0));if(model.state==='clear'){list.replaceChildren(el('div','msa-empty','No evidence-backed alerts are active.'));return}if(!model.rows.length){list.replaceChildren(el('div','msa-empty','No alerts match the selected filters.'));return}const box=el('div','msa-list');for(const row of model.rows){const article=el('article','msa-row');const rowHead=el('div','msa-row-head');const info=el('div');info.append(el('h3','',row.title),el('div','msa-meta',detailText(row)));rowHead.append(info,el('span','msa-pill',pretty(row.severity)));const action=el('div','msa-action');const button=el('button','ghost',row.action.label);button.type='button';button.onclick=()=>clickTab(row.action.target);action.append(button);article.append(rowHead,action);box.append(article)}list.replaceChildren(box)}
function boot(){loadCss();loadModel(()=>{ensureUi();render();window.addEventListener('morley:intelligence-updated',render);window.addEventListener('morley:source-health-updated',render)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,550),{once:true});else setTimeout(boot,550);
})();

// Source Health shares the Smart Alerts evidence surface but remains read-only.
(()=>{const load=()=>{if(document.querySelector('#morleyIntelligenceSourceHealthLoader'))return;const s=document.createElement('script');s.id='morleyIntelligenceSourceHealthLoader';s.src='intelligence-source-health.js?v=2';s.async=false;document.body.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();