(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const SUPABASE_URL='https://ghdhairijqjqivqriigi.supabase.co';
const SUPABASE_KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';
const TURNSTILE_SITE_KEY='0x4AAAAAAEZul-Qo6dqMim2U';
const SESSION_KEY='nova.morley.session.v1';
const nativeFetch=window.fetch.bind(window);
let unlockNetwork,authClientPromise=null;
const networkReady=new Promise(resolve=>{unlockNetwork=resolve});
function loadEcosystemContract(){if(window.MorleyEcosystem||document.querySelector('#morleyEcosystemContract'))return;const script=document.createElement('script');script.id='morleyEcosystemContract';script.src='../morley-core.js?v=1';script.defer=true;document.head.appendChild(script)}
function applyEcosystemPresentation(){const nav=document.querySelector('[data-section="guardian"]');if(nav)nav.textContent='Security';const page=document.querySelector('[data-page="guardian"]');if(page){const heading=page.querySelector('h2');if(heading)heading.textContent='Guardian Enforcement';const intro=page.querySelector(':scope > .card p');if(intro)intro.textContent='Protected Guardian enforcement evidence for Nova. Nova can observe outcomes and recommendations but cannot inherit, bypass or self-approve Guardian authority.'}const footer=document.querySelector('footer');if(footer)footer.textContent='© 2026 Morley Buys · Nova by Morley · Guardian enforcement protected'}
loadEcosystemContract();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',applyEcosystemPresentation,{once:true});else applyEcosystemPresentation();
function shouldGateFetch(input){try{const raw=input instanceof Request?input.url:String(input);const url=new URL(raw,location.href);return url.origin===location.origin||url.origin==='https://api.github.com'}catch(_e){return true}}
window.fetch=(...args)=>shouldGateFetch(args[0])?networkReady.then(()=>nativeFetch(...args)):nativeFetch(...args);

const lockStyle=document.createElement('style');
lockStyle.id='nova-auth-lock-style';
lockStyle.textContent=`body>*:not(#nova-auth-gate){visibility:hidden!important}#nova-auth-gate{visibility:visible!important;position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;padding:20px;background:radial-gradient(circle at 50% 0%,rgba(57,217,163,.13),transparent 36%),linear-gradient(180deg,#07110e,#091510 68%,#06100c);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#e8fff6}.nova-auth-card{width:min(440px,100%);background:linear-gradient(145deg,rgba(16,37,30,.98),rgba(10,26,21,.99));border:1px solid #1d3c31;border-radius:22px;padding:24px;box-shadow:0 24px 70px rgba(0,0,0,.38)}.nova-auth-brand{display:flex;gap:13px;align-items:center;margin-bottom:20px}.nova-auth-mark{width:52px;aspect-ratio:1;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle,#14684f 0,#0d4a39 60%,#092f25 100%);border:1px solid rgba(57,217,163,.65);box-shadow:0 0 0 7px rgba(57,217,163,.06);font-size:23px;font-weight:900}.nova-auth-eyebrow{font-size:.7rem;letter-spacing:.16em;color:#39d9a3;font-weight:900}.nova-auth-card h1{font-size:1.65rem;margin:.12rem 0}.nova-auth-card p{color:#8fb0a3;line-height:1.5;margin:.35rem 0 1rem}.nova-auth-label{display:block;font-size:.78rem;font-weight:800;color:#b9d4ca;margin:12px 0 6px}.nova-auth-input{width:100%;border:1px solid #1d3c31;background:#07110e;color:#e8fff6;border-radius:13px;padding:12px 13px;font:inherit;outline:none}.nova-auth-input:focus{border-color:#39d9a3;box-shadow:0 0 0 3px rgba(57,217,163,.09)}.nova-auth-btn{width:100%;border:1px solid #39d9a3;background:#39d9a3;color:#04110d;border-radius:13px;padding:12px 14px;margin-top:14px;font:inherit;font-weight:900;cursor:pointer}.nova-auth-btn:disabled{opacity:.5;cursor:not-allowed}.nova-auth-msg{min-height:20px;margin-top:10px;font-size:.82rem;color:#8fb0a3}.nova-auth-msg.error{color:#ffb1b1}.nova-auth-note{font-size:.75rem!important;margin-top:14px!important}.nova-auth-logout{position:fixed;z-index:9999;right:18px;bottom:18px;border:1px solid #1d3c31;background:#0c1b16;color:#b9d4ca;border-radius:999px;padding:9px 13px;font:700 12px Inter,system-ui,sans-serif;cursor:pointer;box-shadow:0 10px 30px rgba(0,0,0,.25)}`;
document.head.appendChild(lockStyle);

function ensureMorleyAuthClient(){if(window.MorleyAuthClient)return Promise.resolve(window.MorleyAuthClient);if(authClientPromise)return authClientPromise;authClientPromise=new Promise((resolve,reject)=>{const existing=document.getElementById('morleyAuthClientScript');if(existing){existing.addEventListener('load',()=>window.MorleyAuthClient?resolve(window.MorleyAuthClient):reject(new Error('Morley auth client did not initialise.')),{once:true});existing.addEventListener('error',()=>reject(new Error('Morley auth client failed to load.')),{once:true});return}const script=document.createElement('script');script.id='morleyAuthClientScript';script.src='../morley-auth-client.js?v=1';script.async=false;script.onload=()=>window.MorleyAuthClient?resolve(window.MorleyAuthClient):reject(new Error('Morley auth client did not initialise.'));script.onerror=()=>reject(new Error('Morley auth client failed to load.'));document.head.appendChild(script)});return authClientPromise}
function saveSession(session){sessionStorage.setItem(SESSION_KEY,JSON.stringify(session))}
function clearSession(){sessionStorage.removeItem(SESSION_KEY)}
function loadSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch(_e){return null}}
async function restoreSession(client){let session=loadSession();if(!session)return null;if(await client.validateProfile(session,{roles:['admin']}))return session;session=await client.refreshSession(session);if(session&&await client.validateProfile(session,{roles:['admin']})){saveSession(session);return session}clearSession();return null}

function loadTurnstile(){return new Promise((resolve,reject)=>{if(window.turnstile)return resolve(window.turnstile);const existing=document.querySelector('script[data-nova-turnstile]');if(existing){existing.addEventListener('load',()=>resolve(window.turnstile),{once:true});existing.addEventListener('error',reject,{once:true});return}const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.defer=true;script.dataset.novaTurnstile='1';script.onload=()=>resolve(window.turnstile);script.onerror=()=>reject(new Error('Security check could not be loaded.'));document.head.appendChild(script)})}
function createGate(){const gate=document.createElement('div');gate.id='nova-auth-gate';gate.innerHTML=`<form class="nova-auth-card" id="nova-auth-form" autocomplete="on"><div class="nova-auth-brand"><div class="nova-auth-mark" aria-hidden="true">N</div><div><div class="nova-auth-eyebrow">MORLEY SYSTEMS</div><h1>Sign in to Nova AI</h1></div></div><p>Use the authorised Morley Admin email and password. Nova accepts the enabled Admin account only.</p><label class="nova-auth-label" for="nova-auth-email">Email</label><input class="nova-auth-input" id="nova-auth-email" type="email" autocomplete="username" required><label class="nova-auth-label" for="nova-auth-password">Password</label><input class="nova-auth-input" id="nova-auth-password" type="password" autocomplete="current-password" required><div class="nova-auth-label">Security check</div><div id="nova-auth-turnstile"></div><button class="nova-auth-btn" id="nova-auth-submit" type="submit" disabled>Complete security check</button><div class="nova-auth-msg" id="nova-auth-message" role="status" aria-live="polite"></div><p class="nova-auth-note">Your password is sent directly to Morley’s Supabase authentication service and is never stored by Nova. The signed-in session token is kept only for this browser tab/session.</p></form>`;document.body.appendChild(gate);return gate}
function addLogout(email){const button=document.createElement('button');button.type='button';button.className='nova-auth-logout';button.textContent=email?'Sign out · '+email:'Sign out';button.addEventListener('click',()=>{clearSession();location.reload()});document.body.appendChild(button)}
function unlock(session,client){window.NovaAuth={getAccessToken:()=>session.access_token||'',getUser:()=>session.user||null,rest:path=>client.rest(path,session.access_token),signOut:()=>{clearSession();location.reload()}};document.documentElement.classList.add('nova-auth-unlocked');document.getElementById('nova-auth-gate')?.remove();document.getElementById('nova-auth-lock-style')?.remove();addLogout(session?.user?.email||'');unlockNetwork();window.dispatchEvent(new Event('nova:authenticated'));const script=document.createElement('script');script.src='app-core.js?v=4';script.defer=true;document.head.appendChild(script)}

async function boot(){const factory=await ensureMorleyAuthClient();const client=factory.create({url:SUPABASE_URL,publishableKey:SUPABASE_KEY,fetchImpl:nativeFetch});let session=await restoreSession(client);if(session){unlock(session,client);return}const gate=createGate();const form=gate.querySelector('#nova-auth-form');const submit=gate.querySelector('#nova-auth-submit');const message=gate.querySelector('#nova-auth-message');let captchaToken='';let widgetId=null;try{const turnstile=await loadTurnstile();widgetId=turnstile.render('#nova-auth-turnstile',{sitekey:TURNSTILE_SITE_KEY,theme:'dark',callback:token=>{captchaToken=token;submit.disabled=false;submit.textContent='Sign in securely'},'expired-callback':()=>{captchaToken='';submit.disabled=true;submit.textContent='Complete security check'},'error-callback':()=>{captchaToken='';submit.disabled=true;message.textContent='Security check failed to load. Refresh and try again.';message.className='nova-auth-msg error'}})}catch(error){message.textContent=error.message||'Security check failed to load.';message.className='nova-auth-msg error'}
form.addEventListener('submit',async event=>{event.preventDefault();message.textContent='';message.className='nova-auth-msg';const email=gate.querySelector('#nova-auth-email').value.trim();const password=gate.querySelector('#nova-auth-password').value;if(!email||!password){message.textContent='Enter your email and password.';message.className='nova-auth-msg error';return}if(!captchaToken){message.textContent='Complete the security check first.';message.className='nova-auth-msg error';return}submit.disabled=true;submit.textContent='Verifying…';try{const signed=await client.signInPassword({email,password,captchaToken});if(!await client.validateProfile(signed,{roles:['admin']}))throw new Error('This account is not authorised for Nova AI.');saveSession(signed);unlock(signed,client)}catch(error){message.textContent=error?.message==='This account is not authorised for Nova AI.'?error.message:'Sign-in failed. Check your details and try again.';message.className='nova-auth-msg error';captchaToken='';submit.disabled=true;submit.textContent='Complete security check';try{if(widgetId!==null)window.turnstile.reset(widgetId)}catch(_e){}}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();

// Approved Nova visual layer. This is shared by the hosted control centre and the Nova APK WebView.
(()=>{const load=()=>{if(!document.querySelector('#novaControlCentreVisualCss')){const l=document.createElement('link');l.id='novaControlCentreVisualCss';l.rel='stylesheet';l.href='control-centre-visual.css?v=1';document.head.appendChild(l)}if(!document.querySelector('#novaControlCentreVisualJs')){const s=document.createElement('script');s.id='novaControlCentreVisualJs';s.src='control-centre-visual.js?v=1';s.async=false;document.body.appendChild(s)}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();