(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const state={main:null,prs:[],commits:[],runs:[]};
function activate(name){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.section===name))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b)activate(b.dataset.section)});
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
function riskFor(pr){const text=`${pr.title||''} ${(pr.body||'')}`.toLowerCase();return /risk\s*[:\-]?\s*high|auth|permission|security|pricing|supabase|migration|release|deploy|workflow|guardian|androidmanifest|signing/.test(text)?'high':'normal'}
function prState(pr){if(pr.draft)return{label:'DRAFT',tone:''};if(riskFor(pr)==='high')return{label:'HUMAN GATE',tone:'high'};return{label:'ACTIVE',tone:'ok'}}
function item(title,detail,tag='',tone='',href=''){const inner=`<div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}`;return href?`<a class="item" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${inner}</a>`:`<div class="item">${inner}</div>`}
function latestRun(name){return state.runs.find(r=>r.name===name)||null}
function runLabel(run){if(!run)return'UNKNOWN';if(run.status!=='completed')return'RUNNING';return run.conclusion==='success'?'HEALTHY':String(run.conclusion||'FAILED').toUpperCase()}
function prUrl(pr){return pr.html_url||`https://github.com/${REPO}/pull/${pr.number}`}
function runUrl(run){return run?.html_url||''}
function render(){const novaPrs=state.prs.filter(p=>String(p.head?.ref||'').startsWith('nova/'));const attention=novaPrs.filter(p=>riskFor(p)==='high');const deploy=latestRun('Deploy B&L Morley Web');const failedRuns=state.runs.filter(r=>r.status==='completed'&&r.conclusion&&r.conclusion!=='success'&&r.conclusion!=='skipped');const runningRuns=state.runs.filter(r=>r.status!=='completed');
$('metricPrs').textContent=novaPrs.length;$('metricAttention').textContent=attention.length;$('metricMain').textContent=state.main?.commit?.sha?state.main.commit.sha.slice(0,7):'—';
const queue=$('workQueue');queue.innerHTML=novaPrs.length?novaPrs.map(p=>{const s=prState(p);return item(`#${p.number} ${p.title}`,`${p.head.ref} • updated ${new Date(p.updated_at).toLocaleString()}`,s.label,s.tone,prUrl(p))}).join(''):'<div class="empty">No open Nova pull requests.</div>';
const att=$('attentionList');const alerts=[];attention.forEach(p=>alerts.push(item(`#${p.number} ${p.title}`,'Protected or high-risk Nova work requires explicit human authorisation before merge.','REVIEW','high',prUrl(p))));failedRuns.slice(0,4).forEach(r=>alerts.push(item(r.name,`Latest main workflow failed • ${new Date(r.updated_at).toLocaleString()}`,'BLOCKED','high',runUrl(r))));att.innerHTML=alerts.length?alerts.join(''):'<div class="empty">No current Nova item requires human attention.</div>';
$('developmentList').innerHTML=novaPrs.length?novaPrs.map(p=>{const s=prState(p);return item(`#${p.number} ${p.title}`,`${p.head.ref} → ${p.base.ref}`,s.label,s.tone,prUrl(p))}).join(''):'<div class="empty">No active Nova development PRs.</div>';
const deploymentItem=deploy?item('Production Pages',`${runLabel(deploy)} • run #${deploy.run_number} • ${new Date(deploy.updated_at).toLocaleString()}`,runLabel(deploy),runLabel(deploy)==='HEALTHY'?'ok':runLabel(deploy)==='RUNNING'?'':'high',runUrl(deploy)):'';
$('activityList').innerHTML=deploymentItem+(state.commits.length?state.commits.slice(0,7).map(c=>item(c.commit?.message?.split('\n')[0]||c.sha.slice(0,7),`${c.sha.slice(0,7)} • ${new Date(c.commit?.committer?.date||0).toLocaleString()}`,'','',c.html_url||`https://github.com/${REPO}/commit/${c.sha}`)).join(''):'<div class="empty">No recent activity loaded.</div>');
if(failedRuns.length){$('coreState').textContent='BLOCKED';$('coreTitle').textContent='Nova detected a failed workflow';$('coreSummary').textContent=`${failedRuns.length} recent main workflow${failedRuns.length===1?'':'s'} require investigation before Nova treats the system as healthy.`;$('coreOrb').style.borderColor='rgba(255,140,140,.7)'}else if(attention.length){$('coreState').textContent='ATTENTION';$('coreTitle').textContent='Nova needs a review';$('coreSummary').textContent=`${attention.length} high-risk Nova pull request${attention.length===1?'':'s'} currently require human review before merge.`;$('coreOrb').style.borderColor='rgba(255,140,140,.7)'}else if(runningRuns.length){$('coreState').textContent='RUNNING';$('coreTitle').textContent='Nova is monitoring active checks';$('coreSummary').textContent=`${runningRuns.length} main workflow${runningRuns.length===1?' is':'s are'} still running. No protected action will be inferred from an incomplete result.`;$('coreOrb').style.borderColor='rgba(57,217,163,.65)'}else{$('coreState').textContent='HEALTHY';$('coreTitle').textContent='Nova is online';$('coreSummary').textContent=`Standalone Nova is reading live GitHub state. Production Pages is ${runLabel(deploy).toLowerCase()}; protected write authority remains disabled.`;$('coreOrb').style.borderColor='rgba(57,217,163,.65)'}
}
async function refresh(){const label=$('connectionLabel');label.textContent='Connecting';try{const [main,prs,commits,runs]=await Promise.all([api('/branches/main'),api('/pulls?state=open&per_page=50'),api('/commits?per_page=20'),api('/actions/runs?branch=main&per_page=30')]);state.main=main;state.prs=prs;state.commits=commits;state.runs=runs.workflow_runs||[];render();label.textContent='GitHub connected'}catch(e){console.error(e);label.textContent='Read degraded';$('coreState').textContent='DEGRADED';$('coreTitle').textContent='Nova cannot read GitHub';$('coreSummary').textContent='The standalone shell is running, but its public GitHub read is temporarily unavailable. No protected action was attempted.'}}
$('refreshBtn')?.addEventListener('click',refresh);refresh();
})();
