(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const TRUSTED_KNOWLEDGE=[
  {path:'PRODUCTION_READINESS.md',label:'Production Readiness'},
  {path:'FULL_FEATURE_VALIDATION_2026-09-01.md',label:'Full Feature Validation'},
  {path:'UI_CHANGE_MASTER_CHECKLIST.md',label:'UI Change Master Checklist'}
];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const state={main:null,prs:[],commits:[],runs:[],knowledge:[],catalogue:null,support:null,memory:null};
let refreshVersion=0;
function activate(name){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.section===name))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b)activate(b.dataset.section)});
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
async function localJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`Local ${r.status}`);return r.json()}
function riskFor(pr){const ref=String(pr?.head?.ref||''),text=`${pr?.title||''}\n${pr?.body||''}`;if(!ref.startsWith('nova/'))return'normal';return /\bhigh[- ]risk\b/i.test(text)||/\brisk\s*[:=-]\s*(?:\*\*)?high\b/i.test(text)||/(?:^|\n)#{1,6}\s*risk\s*\n+\s*(?:\*\*)?high\b/im.test(text)?'high':'normal'}
function prState(pr){if(pr.draft)return{label:'DRAFT',tone:''};if(riskFor(pr)==='high')return{label:'HUMAN GATE',tone:'high'};return{label:'ACTIVE',tone:'ok'}}
function item(title,detail,tag='',tone='',href=''){const inner=`<div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}`;return href?`<a class="item" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${inner}</a>`:`<div class="item">${inner}</div>`}
function latestRun(name){return state.runs.find(r=>r.name===name)||null}
function currentWorkflowRuns(){const seen=new Set();return state.runs.filter(run=>{const key=String(run.name||run.workflow_id||run.id);if(seen.has(key))return false;seen.add(key);return true})}
function runLabel(run){if(!run)return'UNKNOWN';if(run.status!=='completed')return'RUNNING';if(run.conclusion==='success')return'HEALTHY';if(run.conclusion==='skipped')return'SKIPPED';return String(run.conclusion||'FAILED').toUpperCase()}
function runTone(run){const label=runLabel(run);return label==='HEALTHY'?'ok':label==='RUNNING'||label==='SKIPPED'?'':'high'}
function prUrl(pr){return pr.html_url||`https://github.com/${REPO}/pull/${pr.number}`}
function runUrl(run){return run?.html_url||''}
function decodeGithubContent(payload){const raw=String(payload?.content||'').replace(/\s/g,'');if(!raw)return'';const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function previewMarkdown(text){const lines=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const useful=lines.filter(x=>!/^#{1,6}\s/.test(x)&&!/^[-*]\s*\[[ xX]\]/.test(x)&&!/^[-*]\s*$/.test(x));const preview=(useful[0]||lines[0]||'No preview available.').replace(/^[-*>]\s*/,'');return preview.length>180?preview.slice(0,177)+'…':preview}
async function loadKnowledge(){return Promise.all(TRUSTED_KNOWLEDGE.map(async source=>{try{const payload=await api(`/contents/${encodeURIComponent(source.path)}?ref=main`);const text=decodeGithubContent(payload);return{...source,ok:true,sha:payload.sha||'',preview:previewMarkdown(text),url:payload.html_url||`https://github.com/${REPO}/blob/main/${source.path}`}}catch(error){return{...source,ok:false,preview:'Trusted source is currently unavailable.',url:`https://github.com/${REPO}/blob/main/${source.path}`}}}))}
async function loadCatalogue(){try{return await localJson('catalogue-health.json')}catch(error){console.error(error);return null}}
async function loadSupport(){try{return await localJson('support-health.json')}catch(error){console.error(error);return null}}
async function loadMemory(){try{return await localJson('memory-health.json')}catch(error){console.error(error);return null}}
function renderKnowledge(){const el=$('knowledgeList');if(!el)return;el.innerHTML=state.knowledge.length?state.knowledge.map(source=>item(source.label,source.preview,source.ok?'TRUSTED':'UNAVAILABLE',source.ok?'ok':'high',source.url)).join(''):'<div class="empty">No trusted project context loaded.</div>'}
function renderMemory(){const data=state.memory;const domains=$('memoryDomainList');if(!domains)return;if(!data){$('memoryKnowledge').textContent='—';$('memoryLearning').textContent='—';$('memoryVerified').textContent='—';$('memoryConfidence').textContent='—';$('memoryChecked').textContent='UNAVAILABLE';$('memoryChecked').className='tag high';domains.innerHTML='<div class="empty">Memory health snapshot is unavailable. Nova did not attempt a protected database read from the public client.</div>';$('memoryBoundary').textContent='Reference memory remains non-authoritative.';return}
const knowledge=data.knowledge_items||{};const learning=data.learning_experiences||{};$('memoryKnowledge').textContent=Number(knowledge.active||0).toLocaleString();$('memoryLearning').textContent=Number(learning.active||0).toLocaleString();$('memoryVerified').textContent=Number(learning.verified||0).toLocaleString();$('memoryConfidence').textContent=Number(learning.average_confidence||0).toFixed(3);$('memoryChecked').textContent=`CHECKED ${data.checked_date||'UNKNOWN'}`;$('memoryChecked').className='tag ok';domains.innerHTML=(data.domains||[]).map(d=>{const total=Number(d.total||0);const verified=Number(d.verified||0);const confidence=Number(d.average_confidence||0);return item(String(d.domain||'unknown').replaceAll('_',' '),`${verified.toLocaleString()} verified / ${total.toLocaleString()} learned • avg confidence ${confidence.toFixed(3)}`,verified===total?'VERIFIED':'PARTIAL',verified===total?'ok':'')}).join('')||'<div class="empty">No learning domains are currently represented.</div>';$('memoryBoundary').textContent=data.boundary_note||'Reference memory and learned experiences remain non-authoritative.'}
function renderCatalogue(){const data=state.catalogue;const list=$('catalogueList');if(!list)return;if(!data){$('catalogueTotal').textContent='—';$('catalogueActive').textContent='—';$('catalogueAu').textContent='—';$('catalogueModelGaps').textContent='—';$('catalogueChecked').textContent='UNAVAILABLE';$('catalogueChecked').className='tag high';list.innerHTML='<div class="empty">Catalogue health snapshot is unavailable. No database access was attempted from the public Nova client.</div>';return}
$('catalogueTotal').textContent=Number(data.total_records||0).toLocaleString();$('catalogueActive').textContent=Number(data.active_records||0).toLocaleString();$('catalogueAu').textContent=Number(data.au_region_records||0).toLocaleString();$('catalogueModelGaps').textContent=Number(data.missing_model_number||0).toLocaleString();$('catalogueChecked').textContent=`CHECKED ${data.checked_date||'UNKNOWN'}`;$('catalogueChecked').className='tag ok';list.innerHTML=(data.categories||[]).map(c=>{const gaps=[];if(c.missing_model_number)gaps.push(`${c.missing_model_number} model-number gap${c.missing_model_number===1?'':'s'}`);if(c.missing_storage&&c.category!=='wearable')gaps.push(`${c.missing_storage} storage gap${c.missing_storage===1?'':'s'}`);const detail=`${Number(c.active||0).toLocaleString()} active / ${Number(c.total||0).toLocaleString()} total • ${Number(c.au_region||0).toLocaleString()} AU mapped${gaps.length?' • '+gaps.join(' • '):''}`;return item(c.label||c.category,detail,gaps.length?'REVIEW':'CLEAN',gaps.length?'high':'ok')}).join('')||'<div class="empty">No category aggregates available.</div>'}
function renderSupport(){const data=state.support;const statusList=$('supportStatusList');const categoryList=$('supportCategoryList');if(!statusList||!categoryList)return;if(!data){$('supportTotal').textContent='—';$('supportActive').textContent='—';$('supportHigh').textContent='—';$('supportSla').textContent='—';$('supportChecked').textContent='UNAVAILABLE';$('supportChecked').className='tag high';statusList.innerHTML='<div class="empty">Support health snapshot is unavailable. No protected ticket read was attempted from the public Nova client.</div>';categoryList.innerHTML='<div class="empty">No category aggregate available.</div>';$('supportResponseCallout').textContent='First-response health is unavailable.';return}
$('supportTotal').textContent=Number(data.total_tickets||0).toLocaleString();$('supportActive').textContent=Number(data.active_tickets||0).toLocaleString();$('supportHigh').textContent=Number(data.high_priority_active||0).toLocaleString();$('supportSla').textContent=Number(data.sla_overdue||0).toLocaleString();const unhealthy=Number(data.high_priority_active||0)>0||Number(data.sla_overdue||0)>0||Number(data.awaiting_first_response||0)>0;$('supportChecked').textContent=`CHECKED ${data.checked_date||'UNKNOWN'}`;$('supportChecked').className=`tag ${unhealthy?'high':'ok'}`;statusList.innerHTML=(data.status_counts||[]).map(s=>item(String(s.status||'unknown').replaceAll('_',' '),`${Number(s.total||0).toLocaleString()} ticket${Number(s.total||0)===1?'':'s'}`,String(s.status||'').toUpperCase(),s.status==='closed'?'ok':'')).join('')||'<div class="empty">No status aggregates available.</div>';categoryList.innerHTML=(data.category_counts||[]).map(c=>item(c.label||String(c.category||'Other'),`${Number(c.total||0).toLocaleString()} ticket${Number(c.total||0)===1?'':'s'}`)).join('')||'<div class="empty">No category aggregates available.</div>';$('supportResponseCallout').textContent=Number(data.awaiting_first_response||0)===0?'No active ticket is waiting for its first response.':`${Number(data.awaiting_first_response).toLocaleString()} active ticket${Number(data.awaiting_first_response)===1?' is':'s are'} still waiting for a first response.`}
function renderMonitoring(){const el=$('monitoringList');if(!el)return;const current=currentWorkflowRuns();const healthy=current.filter(r=>r.status==='completed'&&r.conclusion==='success');const running=current.filter(r=>r.status!=='completed');const skipped=current.filter(r=>r.status==='completed'&&r.conclusion==='skipped');const failed=current.filter(r=>r.status==='completed'&&r.conclusion&&r.conclusion!=='success'&&r.conclusion!=='skipped');$('monitorTracked').textContent=current.length.toLocaleString();$('monitorHealthy').textContent=healthy.length.toLocaleString();$('monitorRunning').textContent=running.length.toLocaleString();$('monitorFailed').textContent=failed.length.toLocaleString();$('monitorState').textContent=failed.length?'BLOCKED':running.length?'RUNNING':skipped.length?'INCOMPLETE':'HEALTHY';$('monitorState').className=`tag ${failed.length?'high':running.length||skipped.length?'':'ok'}`;const rank=r=>{const label=runLabel(r);return label==='HEALTHY'?3:label==='SKIPPED'?2:label==='RUNNING'?1:0};el.innerHTML=current.length?[...current].sort((a,b)=>rank(a)-rank(b)).map(r=>item(r.name||`Workflow ${r.workflow_id}`,`run #${r.run_number} • ${new Date(r.updated_at||r.created_at).toLocaleString()}`,runLabel(r),runTone(r),runUrl(r))).join(''):'<div class="empty">No current main-branch workflow runs loaded.</div>'}
function render(){const novaPrs=state.prs.filter(p=>String(p.head?.ref||'').startsWith('nova/'));const attention=novaPrs.filter(p=>riskFor(p)==='high');const deploy=latestRun('Deploy B&L Morley Web');const currentRuns=currentWorkflowRuns();const failedRuns=currentRuns.filter(r=>r.status==='completed'&&r.conclusion&&r.conclusion!=='success'&&r.conclusion!=='skipped');const runningRuns=currentRuns.filter(r=>r.status!=='completed');const skippedRuns=currentRuns.filter(r=>r.status==='completed'&&r.conclusion==='skipped');
$('metricPrs').textContent=novaPrs.length;$('metricAttention').textContent=attention.length;$('metricMain').textContent=state.main?.commit?.sha?state.main.commit.sha.slice(0,7):'—';
$('workQueue').innerHTML=novaPrs.length?novaPrs.map(p=>{const s=prState(p);return item(`#${p.number} ${p.title}`,`${p.head.ref} • updated ${new Date(p.updated_at).toLocaleString()}`,s.label,s.tone,prUrl(p))}).join(''):'<div class="empty">No open Nova pull requests.</div>';
const alerts=[];attention.forEach(p=>alerts.push(item(`#${p.number} ${p.title}`,'Protected or high-risk Nova work requires explicit human authorisation before merge.','REVIEW','high',prUrl(p))));failedRuns.slice(0,4).forEach(r=>alerts.push(item(r.name,`Current main workflow failed • ${new Date(r.updated_at).toLocaleString()}`,'BLOCKED','high',runUrl(r))));$('attentionList').innerHTML=alerts.length?alerts.join(''):'<div class="empty">No current Nova item requires human attention.</div>';
$('developmentList').innerHTML=novaPrs.length?novaPrs.map(p=>{const s=prState(p);return item(`#${p.number} ${p.title}`,`${p.head.ref} → ${p.base.ref}`,s.label,s.tone,prUrl(p))}).join(''):'<div class="empty">No active Nova development PRs.</div>';
const deploymentItem=deploy?item('Production Pages',`${runLabel(deploy)} • run #${deploy.run_number} • ${new Date(deploy.updated_at).toLocaleString()}`,runLabel(deploy),runTone(deploy),runUrl(deploy)):'';$('activityList').innerHTML=deploymentItem+(state.commits.length?state.commits.slice(0,7).map(c=>item(c.commit?.message?.split('\n')[0]||c.sha.slice(0,7),`${c.sha.slice(0,7)} • ${new Date(c.commit?.committer?.date||0).toLocaleString()}`,'','',c.html_url||`https://github.com/${REPO}/commit/${c.sha}`)).join(''):'<div class="empty">No recent activity loaded.</div>');
renderKnowledge();renderMemory();renderCatalogue();renderSupport();renderMonitoring();
if(failedRuns.length){$('coreState').textContent='BLOCKED';$('coreTitle').textContent='Nova detected a current failed workflow';$('coreSummary').textContent=`${failedRuns.length} latest main workflow${failedRuns.length===1?'':'s'} require investigation. Older failures with a newer successful run are not counted as current blockers.`;$('coreOrb').style.borderColor='rgba(255,140,140,.7)'}else if(attention.length){$('coreState').textContent='ATTENTION';$('coreTitle').textContent='Nova needs a review';$('coreSummary').textContent=`${attention.length} high-risk Nova pull request${attention.length===1?'':'s'} currently require human review before merge.`;$('coreOrb').style.borderColor='rgba(255,140,140,.7)'}else if(runningRuns.length){$('coreState').textContent='RUNNING';$('coreTitle').textContent='Nova is monitoring active checks';$('coreSummary').textContent=`${runningRuns.length} latest main workflow${runningRuns.length===1?' is':'s are'} still running. No protected action will be inferred from an incomplete result.`;$('coreOrb').style.borderColor='rgba(57,217,163,.65)'}else if(skippedRuns.length){$('coreState').textContent='INCOMPLETE';$('coreTitle').textContent='Nova is waiting on complete evidence';$('coreSummary').textContent=`${skippedRuns.length} latest main workflow${skippedRuns.length===1?' was':'s were'} skipped. Nova will not describe skipped evidence as a successful health result.`;$('coreOrb').style.borderColor='rgba(57,217,163,.45)'}else{$('coreState').textContent='HEALTHY';$('coreTitle').textContent='Nova is online';const learned=Number(state.memory?.learning_experiences?.active||0);$('coreSummary').textContent=`Standalone Nova is reading live GitHub state, ${state.knowledge.filter(x=>x.ok).length} trusted project sources, aggregate catalogue/support health, and ${learned.toLocaleString()} non-authoritative learned experiences. Production Pages is ${runLabel(deploy).toLowerCase()}; protected write authority remains disabled.`;$('coreOrb').style.borderColor='rgba(57,217,163,.65)'}
}
async function refresh(){const requestVersion=++refreshVersion;const label=$('connectionLabel');label.textContent='Connecting';try{const [main,prs,commits,runs,knowledge,catalogue,support,memory]=await Promise.all([api('/branches/main'),api('/pulls?state=open&per_page=50'),api('/commits?per_page=20'),api('/actions/runs?branch=main&per_page=30'),loadKnowledge(),loadCatalogue(),loadSupport(),loadMemory()]);if(requestVersion!==refreshVersion)return;state.main=main;state.prs=prs;state.commits=commits;state.runs=runs.workflow_runs||[];state.knowledge=knowledge;state.catalogue=catalogue;state.support=support;state.memory=memory;render();label.textContent='GitHub connected'}catch(e){if(requestVersion!==refreshVersion)return;console.error(e);label.textContent='Read degraded';$('coreState').textContent='DEGRADED';$('coreTitle').textContent='Nova cannot read GitHub';$('coreSummary').textContent='The standalone shell is running, but its public GitHub read is temporarily unavailable. No protected action was attempted.'}}
const permissionsScript=document.createElement('script');permissionsScript.src='permissions.js?v=1';permissionsScript.async=true;document.head.appendChild(permissionsScript);
$('refreshBtn')?.addEventListener('click',refresh);refresh();
})();