(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const RULES=[
 {re:/about:srcdoc|srcdoc/i,title:'Web srcdoc runtime',files:['index.html','web-base.html','guardian-live.js'],why:'The production web shell generates the app inside an iframe srcdoc; runtime line numbers must be mapped back to the generator/source scripts.'},
 {re:/recent is not defined|recentEl|\brecent\b.*ReferenceError/i,title:'Recent activity renderer',files:['web-base.html','index.html','web-initial-render-fix.js'],why:'Known recent-activity render path; verify the guarded recent element anchor and avoid reintroducing a stale fallback.'},
 {re:/guardian/i,title:'Guardian runtime',files:['guardian-live.js','index.html','web-base.html'],why:'Guardian diagnostics should be correlated with the actual generated source and existing protected repair records.'},
 {re:/pricing|valuation|market-search|ebay/i,title:'Pricing / market evidence',files:['morley-central-pricing.js','web-universal-buy.js','secure-pricing.js'],why:'Check query identity, source filtering and response contracts before touching protected pricing logic.'},
 {re:/support|ticket|sla/i,title:'Support surface',files:['admin/support.html','nova/live-support.js','nova/support-triage.js'],why:'Separate layout/query failures from protected ticket mutations and customer data.'},
 {re:/cannot read properties of null|querySelector|undefined.*(?:innerHTML|textContent|classList)/i,title:'DOM lifecycle / missing element',files:['web-initial-render-fix.js','mobile-layout-fix.js','more-menu-v2.js'],why:'Likely renderer timing, route parity or stale element assumption. Reproduce the exact route/viewport before patching.'},
 {re:/network|fetch|cors|failed to fetch|http 4\d\d|http 5\d\d/i,title:'Network / service contract',files:['connection-status.js','web-diagnostics.js','web-auth.js'],why:'Confirm endpoint, authentication, origin and current service health before changing client behavior.'}
];
function analyse(raw){const text=String(raw||'').trim(),matches=RULES.filter(r=>r.re.test(text)),error=(text.match(/(?:ReferenceError|TypeError|SyntaxError|Error):?\s*([^\n]+)/i)||[])[0]||text.split('\n')[0]||'Unknown error';const stack=[...text.matchAll(/([A-Za-z0-9_.\/-]+\.js|index\.html|web-base\.html)(?::(\d+))?(?::(\d+))?/g)].map(m=>({file:m[1],line:m[2]||'',column:m[3]||''}));const files=[...new Set([...stack.map(x=>x.file),...matches.flatMap(x=>x.files)])];return{error,matches,stack,files,confidence:matches.length?Math.min(.95,.55+.12*matches.length):.35}}
function install(){const page=$('[data-page="development"]');if(!page||$('#novaBugTriage'))return;const card=document.createElement('article');card.className='card';card.id='novaBugTriage';card.innerHTML=`<div class="section-head"><div><div class="eyebrow">AUTONOMOUS BUG TRIAGE</div><h2>Error → likely source</h2></div><span id="bugTriageState" class="tag">READY</span></div><p>Paste a browser error, app log or support diagnostic. Nova maps likely generating layers and recommends a safe investigation path. It does not execute Guardian repairs or merge fixes from this view.</p><textarea id="bugTriageInput" rows="7" placeholder="Paste error / stack trace / diagnostic here" style="box-sizing:border-box;width:100%;border:1px solid #1d3c31;background:#07110e;color:#e8fff6;border-radius:12px;padding:12px;resize:vertical"></textarea><button id="bugTriageRun" type="button" style="margin-top:10px">Analyse bug</button><div id="bugTriageResult" class="stack" style="margin-top:12px"><div class="empty">No diagnostic analysed yet.</div></div><div class="callout">Protected repair execution, auth, pricing and production writes remain outside this triage surface.</div>`;page.appendChild(card);$('#bugTriageRun').addEventListener('click',run)}
function run(){const raw=$('#bugTriageInput')?.value||'',d=analyse(raw),out=$('#bugTriageResult');if(!raw.trim())return;const row=(a,b,tag='',tone='')=>`<div class="item"><div><b>${esc(a)}</b><small>${esc(b)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}</div>`;const rows=[row(d.error,`Triage confidence ${Math.round(d.confidence*100)}% • ${d.stack.length} explicit stack reference${d.stack.length===1?'':'s'}`,'DIAGNOSIS',d.confidence>=.75?'ok':'')];for(const m of d.matches)rows.push(row(m.title,m.why,'PATTERN'));for(const f of d.files.slice(0,12)){const hit=d.stack.find(x=>x.file===f);rows.push(row(f,hit&&hit.line?`Explicit stack location line ${hit.line}${hit.column?`, column ${hit.column}`:''}`:'Candidate source based on matched runtime architecture.','SOURCE'))}rows.push(row('Safest next path',d.matches.some(x=>/srcdoc|Guardian/i.test(x.title))?'Reproduce against current main, map the generated runtime back to its source, add regression coverage, then prepare a narrow PR. Do not bypass Guardian approval boundaries.':'Reproduce on current main, isolate the smallest source path, add regression coverage, run relevant gates, then prepare a narrow PR.','PLAN','ok'));out.innerHTML=rows.join('');$('#bugTriageState').textContent='ANALYSED';$('#bugTriageState').className='tag ok'}
window.NovaBugTriage={analyse};if(document.readyState==='loading')addEventListener('DOMContentLoaded',install,{once:true});else install();addEventListener('nova:authenticated',install);
})();
