(()=>{'use strict';
const SUPABASE_URL='https://ghdhairijqjqivqriigi.supabase.co',SUPABASE_KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const RULES=[
 {re:/about:srcdoc|srcdoc/i,title:'Web srcdoc runtime',files:['index.html','web-base.html','guardian-live.js'],why:'The production web shell generates the app inside an iframe srcdoc; runtime line numbers must be mapped back to the generator/source scripts.'},
 {re:/recent is not defined|recentEl|\brecent\b.*ReferenceError/i,title:'Recent activity renderer',files:['web-base.html','index.html','web-initial-render-fix.js'],why:'Known recent-activity render path; verify the guarded recent element anchor and avoid reintroducing a stale fallback.'},
 {re:/guardian/i,title:'Guardian runtime',files:['guardian-live.js','index.html','web-base.html'],why:'Guardian diagnostics should be correlated with the actual generated source and existing protected repair records.'},
 {re:/pricing|valuation|market-search|ebay/i,title:'Pricing / market evidence',files:['morley-central-pricing.js','web-universal-buy.js','secure-pricing.js'],why:'Check query identity, source filtering and response contracts before touching protected pricing logic.'},
 {re:/support|ticket|sla/i,title:'Support surface',files:['admin/support.html','nova/live-support.js','nova/support-triage.js'],why:'Separate layout/query failures from protected ticket mutations and customer data.'},
 {re:/cannot read properties of null|querySelector|undefined.*(?:innerHTML|textContent|classList)/i,title:'DOM lifecycle / missing element',files:['web-initial-render-fix.js','mobile-layout-fix.js','more-menu-v2.js'],why:'Likely renderer timing, route parity or stale element assumption. Reproduce the exact route/viewport before patching.'},
 {re:/network|fetch|cors|failed to fetch|http 4\d\d|http 5\d\d/i,title:'Network / service contract',files:['connection-status.js','web-diagnostics.js','web-auth.js'],why:'Confirm endpoint, authentication, origin and current service health before changing client behavior.'},
 {re:/android|apk|activity|java|gradle|manifest|crash/i,title:'Android runtime',files:['android/novaapp/src/main/java/com/buysloans/nova/MainActivity.java','android/novaapp/build.gradle','android/novaapp/src/main/AndroidManifest.xml'],why:'Check the exact installed version, compiled source transformation, lifecycle and Android regression tests before patching.'}
];
let current=null,currentPatch=null;
function analyse(raw){const text=String(raw||'').trim(),matches=RULES.filter(r=>r.re.test(text)),error=(text.match(/(?:ReferenceError|TypeError|SyntaxError|Exception|Error):?\s*([^\n]+)/i)||[])[0]||text.split('\n')[0]||'Unknown error';const stack=[...text.matchAll(/([A-Za-z0-9_.\/-]+\.(?:js|java|kt|html|gradle|xml)|index\.html|web-base\.html)(?::(\d+))?(?::(\d+))?/g)].map(m=>({file:m[1],line:m[2]||'',column:m[3]||''}));const files=[...new Set([...stack.map(x=>x.file),...matches.flatMap(x=>x.files)])];const confidence=matches.length?Math.min(.95,.55+.12*matches.length):.35;return{raw:text,error,matches,stack,files,confidence,testPlan:['Reproduce on current main/current release and capture the exact failing route/device/version.','Map generated/runtime references back to checked-in source before editing.','Add a regression test that fails before the patch.','Make the smallest source change needed and run Security, Quality, Nova Guard and Ultimate Parity.','Prepare a narrow draft PR; Nova must not merge, release or deploy it automatically.']}}
async function invoke(name,body){const token=window.NovaAuth?.getAccessToken?.()||'';if(!token)throw new Error('Nova Admin authentication is required.');const r=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(body),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`${name} returned HTTP ${r.status}`);return d}
function row(a,b,tag='',tone=''){return `<div class="item"><div><b>${esc(a)}</b><small>${esc(b)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}</div>`}
function install(){const page=$('[data-page="development"]');if(!page||$('#novaBugTriage'))return;const card=document.createElement('article');card.className='card';card.id='novaBugTriage';card.innerHTML=`<div class="section-head"><div><div class="eyebrow">AUTONOMOUS BUG TRIAGE</div><h2>Error → source → patch → draft PR</h2></div><span id="bugTriageState" class="tag">READY</span></div><p>Paste a browser error, app log or support diagnostic. Nova maps likely source, can ask the guarded code-proposal service for a low-risk replacement-file patch, and can create a draft PR through the restricted GitHub broker. Protected paths, merge, release and deploy remain blocked.</p><textarea id="bugTriageInput" rows="7" placeholder="Paste error / stack trace / diagnostic here" style="box-sizing:border-box;width:100%;border:1px solid #1d3c31;background:#07110e;color:#e8fff6;border-radius:12px;padding:12px;resize:vertical"></textarea><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button id="bugTriageRun" type="button">Analyse bug</button><button id="bugTriageSave" type="button" class="secondary" disabled>Save engineering proposal</button><button id="bugTriagePatch" type="button" class="secondary" disabled>Generate guarded patch</button><button id="bugTriagePr" type="button" class="secondary" disabled>Create draft PR</button></div><div id="bugTriageResult" class="stack" style="margin-top:12px"><div class="empty">No diagnostic analysed yet.</div></div><div class="callout" id="bugTriageBoundary">Nova can prepare low-risk draft PRs only. Auth/security, Guardian authority, pricing writes, Android signing/manifest/versioning, workflows, release/OTA/deploy, secrets and destructive paths are rejected server-side.</div>`;page.appendChild(card);$('#bugTriageRun').addEventListener('click',run);$('#bugTriageSave').addEventListener('click',save);$('#bugTriagePatch').addEventListener('click',generatePatch);$('#bugTriagePr').addEventListener('click',createDraftPr)}
function renderDiagnosis(d){const rows=[row(d.error,`Triage confidence ${Math.round(d.confidence*100)}% • ${d.stack.length} explicit stack reference${d.stack.length===1?'':'s'}`,'DIAGNOSIS',d.confidence>=.75?'ok':'')];for(const m of d.matches)rows.push(row(m.title,m.why,'PATTERN'));for(const f of d.files.slice(0,12)){const hit=d.stack.find(x=>x.file===f);rows.push(row(f,hit&&hit.line?`Explicit stack location line ${hit.line}${hit.column?`, column ${hit.column}`:''}`:'Candidate source based on matched runtime architecture.','SOURCE'))}for(const [i,step] of d.testPlan.entries())rows.push(row(`Plan ${i+1}`,step,'TEST'));return rows}
function run(){const raw=$('#bugTriageInput')?.value||'',d=analyse(raw),out=$('#bugTriageResult');if(!raw.trim())return;current=d;currentPatch=null;out.innerHTML=renderDiagnosis(d).join('');$('#bugTriageState').textContent='ANALYSED';$('#bugTriageState').className='tag ok';$('#bugTriageSave').disabled=false;$('#bugTriagePatch').disabled=!d.files.length;$('#bugTriagePr').disabled=true;$('#bugTriageSave').textContent='Save engineering proposal';$('#bugTriagePatch').textContent='Generate guarded patch';$('#bugTriagePr').textContent='Create draft PR'}
async function save(){if(!current)return;const btn=$('#bugTriageSave');btn.disabled=true;btn.textContent='Saving…';try{const area=current.matches[0]?.title||'Unclassified runtime';const d=await invoke('nova-actions',{action:'engineering_proposal',title:`${area}: ${current.error}`.slice(0,220),summary:`${current.error}\n\n${current.matches.map(x=>x.why).join(' ')}\n\nProposal is regression-first and must be reviewed before any patch is merged.`,confidence:current.confidence,candidate_files:current.files.slice(0,20),test_plan:current.testPlan});btn.textContent=`Proposal saved #${d.item?.id||''}`;$('#bugTriageState').textContent='PROPOSED'}catch(e){btn.textContent='Save failed';btn.title=e.message||String(e);setTimeout(()=>{btn.disabled=false;btn.textContent='Save engineering proposal'},1800)}}
async function generatePatch(){if(!current)return;const btn=$('#bugTriagePatch');btn.disabled=true;btn.textContent='Generating…';$('#bugTriagePr').disabled=true;try{const d=await invoke('nova-code-proposal',{diagnostic:current.raw,candidate_files:current.files.slice(0,4)}),p=d.proposal||{};currentPatch=p;const out=$('#bugTriageResult'),rows=renderDiagnosis(current);rows.push(row('Patch proposal',p.summary||'No proposal summary.',`CONF ${Math.round(Number(p.confidence||0)*100)}%`,Number(p.confidence||0)>=.7?'ok':''));for(const c of p.changes||[])rows.push(row(c.path,c.reason||'Smallest eligible replacement-file change proposed.','PATCH'));for(const t of p.tests||[])rows.push(row('Required validation',t,'TEST'));for(const u of p.uncertainties||[])rows.push(row('Uncertainty',u,'REVIEW','high'));if(!(p.changes||[]).length)rows.push(row('No patch generated','Evidence was insufficient or every candidate path was protected/unsupported.','STOP','high'));out.innerHTML=rows.join('');const usable=(p.changes||[]).length>0&&Number(p.confidence||0)>=.55;$('#bugTriagePr').disabled=!usable;btn.textContent=usable?'Patch ready':'No safe patch';$('#bugTriageState').textContent=usable?'PATCH READY':'REVIEW NEEDED';$('#bugTriageState').className=usable?'tag ok':'tag high'}catch(e){btn.textContent='Patch failed';btn.title=e.message||String(e);$('#bugTriageState').textContent='DEGRADED';$('#bugTriageState').className='tag high';setTimeout(()=>{btn.disabled=false;btn.textContent='Generate guarded patch'},1800)}}
async function createDraftPr(){if(!current||!currentPatch||(currentPatch.changes||[]).length===0)return;const btn=$('#bugTriagePr');btn.disabled=true;btn.textContent='Creating draft…';try{const title=(current.matches[0]?.title||'Nova bug fix')+': '+current.error;const summary=`${currentPatch.summary||current.error}\n\nProposed by Nova from current-main source. Tests have not been claimed as run by the proposal service. Review the exact diff and CI before merge.`;const d=await invoke('nova-github',{action:'prepare_draft_pr',title:title.slice(0,180),summary,files:(currentPatch.changes||[]).map(x=>({path:x.path,content:x.content}))});const url=d.pr?.url||'';btn.textContent=d.pr?.number?`Draft PR #${d.pr.number}`:'Draft PR created';$('#bugTriageState').textContent='DRAFT PR';$('#bugTriageState').className='tag ok';const out=$('#bugTriageResult');out.insertAdjacentHTML('beforeend',row('Draft PR created',`${url||'GitHub draft created'} • branch ${d.branch||'nova/auto-*'} • merge/deploy still blocked.`,'DRAFT','ok'));if(url)$('#bugTriageBoundary').innerHTML=`Draft PR created: <a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(url)}</a>. Nova cannot merge, release or deploy it.`}catch(e){btn.textContent='Draft PR failed';btn.title=e.message||String(e);$('#bugTriageState').textContent='BROKER BLOCKED';$('#bugTriageState').className='tag high';setTimeout(()=>{btn.disabled=false;btn.textContent='Create draft PR'},1800)}}
window.NovaBugTriage={analyse,save,generatePatch,createDraftPr};if(document.readyState==='loading')addEventListener('DOMContentLoaded',install,{once:true});else install();addEventListener('nova:authenticated',install);
})();
