(()=>{'use strict';
const base=window.NovaCommands;if(!base)return;
const HISTORY_KEY='nova.command.history.v1';
const MAX_HISTORY=50;
const CHAIN_RE=/\s*(?:;|\band then\b|\bthen\b|\bfollowed by\b)\s*/i;
const NEGATION=/\b(?:not|dont|cannot|cant|wont|never|stop|avoid)\b/i;
const SECRET_ASSIGNMENT=/\b(password|passwd|passphrase|access[_ -]?token|refresh[_ -]?token|api[_ -]?key|apikey|secret|authorization)\b\s*([:=]|\bis\b)\s*(?:"[^"]*"|'[^']*'|\S+)/gi;
const BEARER=/\bbearer\s+[a-z0-9._~+\/-]{8,}/gi;
const JWT=/\beyJ[a-zA-Z0-9_-]{8,}\.[a-zA-Z0-9_-]{8,}\.[a-zA-Z0-9_-]{8,}\b/g;
function sanitizeInput(value){return String(value??'').replace(BEARER,'Bearer [REDACTED]').replace(JWT,'[REDACTED JWT]').replace(SECRET_ASSIGNMENT,(_m,label,separator)=>`${label} ${separator} [REDACTED]`).slice(0,1000)}
function sanitizeRow(row){if(!row||typeof row!=='object')return null;return{...row,input:sanitizeInput(row.input)}}
function loadHistory(){try{const raw=JSON.parse(sessionStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(raw)?raw.map(sanitizeRow).filter(Boolean).slice(0,MAX_HISTORY):[]}catch(_e){return[]}}
function saveHistory(rows){try{sessionStorage.setItem(HISTORY_KEY,JSON.stringify(rows.map(sanitizeRow).filter(Boolean).slice(0,MAX_HISTORY)))}catch(_e){}}
let history=loadHistory();saveHistory(history);
function record(entry){const safe=Object.freeze({...entry,input:sanitizeInput(entry?.input),at:new Date().toISOString()});history.unshift(safe);history=history.slice(0,MAX_HISTORY);saveHistory(history);window.dispatchEvent(new CustomEvent('nova:command-history',{detail:safe}))}
function split(input){const raw=String(input??'').trim();if(!raw||NEGATION.test(raw))return[raw];const parts=raw.split(CHAIN_RE).map(x=>x.trim()).filter(Boolean);return parts.length>1?parts:[raw]}
function safeResolved(resolved){const c=resolved?.command;return !!c&&c.risk==='safe'&&!c.requiresGuardian&&typeof c.handler==='function'}
function plan(input){const parts=split(input);if(parts.length<2)return null;const steps=parts.map(text=>({text,resolved:base.resolve(text)}));const invalid=steps.find(step=>!step.resolved);if(invalid)return{ok:false,type:'unknown',steps,message:`Nova could not safely resolve “${invalid.text}”, so no chained command was run.`};const protectedStep=steps.find(step=>!safeResolved(step.resolved));if(protectedStep)return{ok:false,type:'protected',steps,message:`Nova will not chain “${protectedStep.text}” because it is not a safe read-only command. No step in this chain was run.`};return{ok:true,type:'plan',steps,message:`Ready to run ${steps.length} safe commands.`}}
const oldExecute=base.execute.bind(base);
async function execute(input){const planned=plan(input);if(!planned){const result=await oldExecute(input);record({input:String(input),ok:!!result?.ok,type:result?.type||'single',commands:result?.command?[result.command]:[]});return result}if(!planned.ok){record({input:String(input),ok:false,type:planned.type,commands:planned.steps.filter(s=>s.resolved).map(s=>s.resolved.command.id)});return planned}const results=[];for(const step of planned.steps){const result=await oldExecute(step.text);results.push(result);if(!result?.ok){record({input:String(input),ok:false,type:'chain-partial',commands:results.map(r=>r.command).filter(Boolean)});return{ok:false,type:'chain-partial',message:`Stopped after ${results.length} of ${planned.steps.length} safe commands: ${result?.message||'a command failed.'}`,results}}const commands=results.map(r=>r.command).filter(Boolean);record({input:String(input),ok:true,type:'chain',commands});return{ok:true,type:'chain',commands,results,message:results.map((r,i)=>`${i+1}. ${r.message}`).join('\n')}}
function historyText(limit=10){const rows=history.slice(0,Math.max(1,Math.min(Number(limit)||10,25)));if(!rows.length)return'No Nova command history exists in this browser session.';return rows.map((row,i)=>`${i+1}. ${row.ok?'OK':'FAILED'} · ${row.type} · ${row.input}`).join('\n')}
function clearHistory(){history=[];saveHistory(history);renderHistory();return true}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderHistory(){const list=document.getElementById('nova-command-history-list');if(!list)return;list.innerHTML=history.length?history.slice(0,20).map(row=>`<div class="nova-command-browser-item"><em>${row.ok?'OK':'FAILED'} · ${esc(row.type||'command')}</em><b>${esc(row.input)}</b><small>${esc((row.commands||[]).join(' · ')||'No canonical action recorded')}<br>${esc(row.at||'')}</small></div>`).join(''):'<div class="nova-command-browser-item">No command history in this browser session.</div>'}
function installHistoryUI(){const browser=document.getElementById('nova-command-browser'),card=browser?.querySelector('.nova-command-browser-card');if(!card||document.getElementById('nova-command-history'))return;const panel=document.createElement('section');panel.id='nova-command-history';panel.innerHTML='<div class="nova-command-browser-head"><div><b>Recent command history</b><small>Session-only · sensitive values are redacted before storage</small></div><button type="button" data-clear-history>Clear</button></div><div class="nova-command-browser-list" id="nova-command-history-list"></div>';card.appendChild(panel);panel.querySelector('[data-clear-history]')?.addEventListener('click',clearHistory);renderHistory()}
const enhanced=Object.freeze({...base,execute,planChain:plan,splitChain:split,getHistory:()=>[...history],clearHistory,historyText,sanitizeHistoryInput:sanitizeInput});
window.NovaCommands=enhanced;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installHistoryUI,{once:true});else installHistoryUI();window.addEventListener('nova:command-history',renderHistory);window.addEventListener('nova:open-command-browser',installHistoryUI);window.dispatchEvent(new Event('nova:command-chains-ready'));
})();