(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const REPO='beaustwrt248-netizen/Buys-Mock',API=`https://api.github.com/repos/${REPO}`,TERMINAL=new Set(['resolved','ignored','closed','dismissed']);
async function gh(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
async function mainRuns(){const commit=await gh('/commits/main'),sha=String(commit?.sha||'');if(!sha)throw new Error('GitHub did not return current main SHA.');const payload=await gh(`/actions/runs?head_sha=${encodeURIComponent(sha)}&per_page=100`);return{sha,runs:(payload.workflow_runs||[]).filter(r=>String(r.head_sha||'')===sha)}}
function base(){const o=location.origin;return o.includes('github.io')?`${o}/Buys-Mock`:o}
function item(title,detail,href,tag='OPEN'){return `<a class="item" href="${esc(href)}" target="_blank" rel="noopener noreferrer"><div><b>${esc(title)}</b><small>${esc(detail)}</small></div><span class="tag ok">${esc(tag)}</span></a>`}
function install(){const nav=$('.nav'),main=$('main');if(!nav||!main||$('[data-section="control"]'))return;const b=document.createElement('button');b.dataset.section='control';b.textContent='Control Centre';const first=nav.querySelector('[data-section="overview"]')?.nextSibling;nav.insertBefore(b,first||null);const p=document.createElement('section');p.className='page';p.dataset.page='control';p.innerHTML=`<div class="card"><div class="section-head"><div><div class="eyebrow">CROSS-APP OPERATOR</div><h2>Nova Control Centre</h2></div><span id="controlState" class="tag">LOADING</span></div><p>One read-only operating view across Morley web, Admin, Guardian, catalogue, support, releases and GitHub. Opening another surface does not grant Nova extra permissions.</p></div><div class="grid-two"><article class="card"><div class="eyebrow">SURFACES</div><h2>Open workspace</h2><div id="controlLinks" class="stack"></div></article><article class="card"><div class="eyebrow">LIVE HEALTH</div><h2>Cross-app status</h2><div id="controlHealth" class="stack"><div class="empty">Loading current signals…</div></div><div class="callout">Protected actions still execute only inside their existing authorised surface and approval flow.</div></article></div>`;const overview=main.querySelector('[data-page="overview"]');main.insertBefore(p,overview?.nextSibling||main.firstChild);renderLinks();refresh()}
function renderLinks(){const root=base(),list=$('#controlLinks');if(!list)return;list.innerHTML=[item('Morley Web','Main valuation and business workspace.',root+'/'),item('Morley Admin','Authorised admin workspace.',root+'/admin/'),item('Guardian Control Centre','Protected Guardian evidence and repair workflow.',root+'/admin/guardian.html'),item('Nova AI','Standalone Nova operator app.',root+'/nova/'),item('GitHub repository','Source, pull requests, checks and releases.',`https://github.com/${REPO}`)].join('')}
async function refresh(){const list=$('#controlHealth');if(!list)return;try{const[release,catalogue,support,guardian]=await Promise.all([mainRuns().catch(()=>({sha:'',runs:[]})),window.NovaCatalogueLive?.load?.().catch(()=>null),window.NovaSupportLive?.load?.().catch(()=>null),window.NovaGuardianLive?.load?.().catch(()=>[])]),seen=new Set(),current=release.runs.filter(r=>{if(seen.has(r.name))return false;seen.add(r.name);return true}),failed=current.filter(r=>r.status==='completed'&&r.conclusion&&!['success','skipped'].includes(r.conclusion)),activeG=(guardian||[]).filter(x=>!TERMINAL.has(String(x.state||'').toLowerCase())),rows=[];rows.push(item('GitHub / Releases',`main ${release.sha.slice(0,8)||'unknown'} • ${failed.length} current failed • ${current.filter(r=>r.status!=='completed').length} running`,`https://github.com/${REPO}/actions`,failed.length?'CHECK':'HEALTH'));if(catalogue)rows.push(`<div class="item"><div><b>Catalogue</b><small>${Number(catalogue.active_records||0).toLocaleString()} active • ${Number(catalogue.missing_model_number||0)} model-number gaps • ${Number(catalogue.missing_image||0)} image gaps</small></div><span class="tag ${Number(catalogue.missing_model_number||0)?'high':'ok'}">LIVE</span></div>`);if(support)rows.push(`<div class="item"><div><b>Support</b><small>${Number(support.active_tickets||0)} active • ${Number(support.sla_overdue||0)} SLA overdue • ${Number(support.high_priority_active||0)} high/urgent</small></div><span class="tag ${Number(support.sla_overdue||0)?'high':'ok'}">LIVE</span></div>`);rows.push(`<div class="item"><div><b>Guardian</b><small>${activeG.length} current • ${activeG.filter(x=>x.requires_approval===true).length} approval-required • ${activeG.filter(x=>Number(x.occurrence_count||0)>1).length} repeated</small></div><span class="tag ${activeG.some(x=>x.requires_approval===true)?'high':'ok'}">PROTECTED</span></div>`);list.innerHTML=rows.join('');$('#controlState').textContent=failed.length?'ATTENTION':'LIVE';$('#controlState').className=`tag ${failed.length?'high':'ok'}`}catch(error){console.error(error);$('#controlState').textContent='DEGRADED';$('#controlState').className='tag high';list.innerHTML=`<div class="empty">${esc(error.message||String(error))}</div>`}}
window.NovaControlCentre={refresh,terminalStates:[...TERMINAL]};if(document.readyState==='loading')addEventListener('DOMContentLoaded',install,{once:true});else install();addEventListener('nova:authenticated',()=>{install();refresh()});document.addEventListener('click',e=>{if(e.target.closest('[data-section="control"]')||e.target?.id==='refreshBtn')refresh()});
})();
