(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const STORE='nova_conversation_v1';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const text=s=>String(s??'').trim();
let lastIntent='';
let evidence=null;
function loadHistory(){try{const value=JSON.parse(sessionStorage.getItem(STORE)||'[]');return Array.isArray(value)?value.slice(-8):[]}catch{return[]}}
let history=loadHistory();
function saveHistory(){try{sessionStorage.setItem(STORE,JSON.stringify(history.slice(-8)))}catch{}}
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
async function local(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`Local ${r.status}`);return r.json()}
function latestRuns(runs){const seen=new Set();return (runs||[]).filter(r=>{const k=String(r.name||r.workflow_id||r.id);if(seen.has(k))return false;seen.add(k);return true})}
async function loadEvidence(force=false){if(evidence&&!force)return evidence;const [runs,prs,catalogue,support,memory,version]=await Promise.all([
 api('/actions/runs?branch=main&per_page=50').catch(()=>({workflow_runs:[]})),
 api('/pulls?state=open&per_page=50').catch(()=>[]),
 window.NovaCatalogueLive.load().catch(()=>null),local('support-health.json').catch(()=>null),local('memory-health.json').catch(()=>null),local('version.json').catch(()=>null)
]);evidence={runs:latestRuns(runs.workflow_runs||[]),prs:prs||[],catalogue,support,memory,version,loadedAt:Date.now()};return evidence}
function intentFor(raw){const x=text(raw).toLowerCase();if(!x)return'';
 if(/^(why|how so|tell me more|what about that|and that|what do you mean|more|details?)\??$/.test(x)&&lastIntent)return lastIntent;
 if(/\b(what should i do|what next|next step|priority|prioritise|recommend|needs attention|attention|blocker|blocked|problem|issue)\b/.test(x))return'priority';
 if(/\b(release|deploy|deployment|ship|ota|apk|build|checks?|ci|workflow|ready|version)\b/.test(x))return'release';
 if(/\b(support|ticket|tickets|sla|customer issue|response)\b/.test(x))return'support';
 if(/\b(catalogue|catalog|device|devices|model number|model-number|storage|phone|tablet|watch|console|laptop|desktop)\b/.test(x))return'catalogue';
 if(/\b(guardian|repair|incident|approval|protected)\b/.test(x))return'guardian';
 if(/\b(memory|learn|learning|knowledge|remember|context|understand)\b/.test(x))return'knowledge';
 if(/\b(changed|recent|activity|commit|commits|pr|pull request|working on|doing)\b/.test(x))return'activity';
 if(/\b(hello|hey|hi|nova|who are you|what can you do|help)\b/.test(x))return'help';
 return'unknown'}
function failedRuns(e){return e.runs.filter(r=>r.status==='completed'&&r.conclusion&&!['success','skipped'].includes(r.conclusion))}
function runningRuns(e){return e.runs.filter(r=>r.status!=='completed')}
function highRiskPrs(e){return e.prs.filter(p=>String(p?.head?.ref||'').startsWith('nova/')&&/\bhigh[- ]risk\b|\brisk\s*[:=-]\s*(?:\*\*)?high\b/i.test(`${p.title||''}\n${p.body||''}`))}
function answerPriority(e){const failed=failedRuns(e),running=runningRuns(e),high=highRiskPrs(e);if(failed.length)return `The first priority is ${failed[0].name}: its latest main run failed. There ${failed.length===1?'is':'are'} ${failed.length} current failed workflow${failed.length===1?'':'s'} in total. I would clear current failures before discretionary work.`;if(high.length)return `The first priority is human review of Nova PR #${high[0].number}, ${high[0].title}. It declares High risk, so I will not treat it as automatically mergeable.`;const s=e.support;if(s&&(Number(s.sla_overdue||0)||Number(s.high_priority_active||0)))return `The strongest live operational signal is Support: ${Number(s.sla_overdue||0)} SLA overdue and ${Number(s.high_priority_active||0)} active high/urgent ticket${Number(s.high_priority_active||0)===1?'':'s'}. That should come before lower-priority enhancement work.`;const gaps=Number(e.catalogue?.missing_model_number||0);if(gaps)return `No higher-priority workflow or human gate is visible. The next validated data-quality lane is the catalogue: ${gaps} record${gaps===1?'':'s'} currently lack model numbers. I would verify those against authoritative Australian sources before any data change.`;return running.length?`${running.length} current workflow${running.length===1?' is':'s are'} still running. I would wait for complete evidence before declaring the next protected action.`:'No urgent intervention is visible in the read-only evidence I can access. The next step can be a low-risk validated improvement.'}
function answerRelease(e){const failed=failedRuns(e),running=runningRuns(e);const build=e.runs.find(r=>/Build B&L Morley APK/i.test(r.name||''));const deploy=e.runs.find(r=>/Deploy B&L Morley/i.test(r.name||''));const v=e.version?.versionName||e.version?.version||'current';if(failed.length)return `Release readiness is blocked by ${failed.length} current failed workflow${failed.length===1?'':'s'}, starting with ${failed[0].name}. I would not call the release green yet.`;if(running.length)return `Release evidence is still incomplete because ${running.length} current workflow${running.length===1?' is':'s are'} running. ${build?`The latest Morley APK build is ${String(build.conclusion||build.status).toUpperCase()}. `:''}I will not infer success from incomplete checks.`;return `Current read-only release evidence has no failed or running latest workflow. ${build?`The latest Morley APK build is ${String(build.conclusion||build.status).toUpperCase()}. `:''}${deploy?`The latest production deployment is ${String(deploy.conclusion||deploy.status).toUpperCase()}. `:''}Nova app metadata reports ${v}. Protected release authority still stays outside this conversation layer.`}
function answerSupport(e){const s=e.support;if(!s)return 'Support aggregate evidence is unavailable right now, so I cannot safely infer ticket health.';return `Support currently shows ${Number(s.active_tickets||0)} active ticket${Number(s.active_tickets||0)===1?'':'s'}, ${Number(s.high_priority_active||0)} high/urgent, ${Number(s.sla_overdue||0)} SLA overdue, and ${Number(s.awaiting_first_response||0)} awaiting a first response. I only use aggregate support evidence here; I do not read customer identities, subjects, messages or diagnostics.`}
function answerCatalogue(e){const c=e.catalogue;if(!c)return 'Live catalogue health is unavailable right now, so I will not guess about device coverage.';const gaps=Number(c.missing_model_number||0);const top=[...(c.categories||[])].filter(x=>Number(x.missing_model_number||0)>0).sort((a,b)=>Number(b.missing_model_number||0)-Number(a.missing_model_number||0))[0];return `The live catalogue currently shows ${Number(c.active_records||0).toLocaleString()} active records and ${Number(c.au_region_records||0).toLocaleString()} explicitly mapped to Australia. ${gaps?`${gaps} record${gaps===1?'':'s'} are missing model numbers${top?`, with ${top.label||top.category} currently the largest category gap at ${Number(top.missing_model_number).toLocaleString()}`:''}.`:'No model-number gap is reported in the current live result.'} I will not invent exact device specifications from aggregate data.`}
function answerGuardian(e){const open=e.prs.filter(p=>/guardian/i.test(`${p.title||''} ${p.head?.ref||''}`));return open.length?`There ${open.length===1?'is':'are'} ${open.length} open Guardian-related pull request${open.length===1?'':'s'}. Guardian remains an independent protected validation layer; I can explain evidence, but I will not inherit repair or approval authority.`:'I do not see an open Guardian-related pull request in the current GitHub evidence. Guardian still remains independent and protected even when its queue is clear.'}
function answerKnowledge(e){const m=e.memory;if(!m)return 'Nova memory-health evidence is unavailable. I can still reason from current GitHub and local health snapshots, but I will not pretend unavailable memory exists.';const domains=(m.domains||[]).map(d=>String(d.domain||'').replaceAll('_',' ')).filter(Boolean);return `I keep live evidence separate from memory. The current snapshot has ${Number(m.knowledge_items?.active||0).toLocaleString()} active reference item${Number(m.knowledge_items?.active||0)===1?'':'s'} and ${Number(m.learning_experiences?.active||0).toLocaleString()} active learning experience${Number(m.learning_experiences?.active||0)===1?'':'s'}${domains.length?` across ${domains.join(', ')}`:''}. In this chat I also retain the recent conversation topic for follow-ups such as “why?” or “tell me more”, but memory never overrides current source-of-truth evidence.`}
function answerActivity(e){const open=e.prs.slice(0,3);const running=runningRuns(e);if(open.length)return `There ${e.prs.length===1?'is':'are'} ${e.prs.length} open pull request${e.prs.length===1?'':'s'} right now. The first ${Math.min(3,open.length)} ${open.length===1?'is':'are'} ${open.map(p=>`#${p.number} ${p.title}`).join('; ')}. ${running.length?`${running.length} latest workflow${running.length===1?' is':'s are'} still running.`:'No latest workflow is currently running.'}`;return running.length?`There are no open pull requests, and ${running.length} latest workflow${running.length===1?' is':'s are'} still running.`:'There are no open pull requests and no latest workflow is currently running.'}
function answerHelp(){return 'You can talk to me naturally about what needs attention, releases/builds, support health, catalogue gaps, Guardian, memory/knowledge, recent work, or what to do next. I keep the previous topic for short follow-ups instead of treating every message as unrelated.'}
async function answer(raw){const intent=intentFor(raw);if(intent!=='unknown')lastIntent=intent;const e=await loadEvidence(intent==='catalogue');switch(intent){case'priority':return answerPriority(e);case'release':return answerRelease(e);case'support':return answerSupport(e);case'catalogue':return answerCatalogue(e);case'guardian':return answerGuardian(e);case'knowledge':return answerKnowledge(e);case'activity':return answerActivity(e);case'help':return answerHelp();default:return `I understand this as a Morley/Nova conversation, but I do not have enough evidence to answer “${text(raw).slice(0,120)}” reliably yet. Ask me about the current release, support, catalogue, Guardian, memory, recent work, or what needs attention and I will use the live read-only project context instead of guessing.`}}
function render(){const log=$('#novaConversationLog');if(!log)return;log.innerHTML=history.length?history.map(m=>`<div class="nova-conversation-message ${m.role}"><b>${m.role==='user'?'You':'Nova'}</b><div>${esc(m.text)}</div></div>`).join(''):'<div class="nova-conversation-empty">Ask about the project in your own words. I will use current read-only evidence and keep the conversation topic for follow-up questions.</div>';log.scrollTop=log.scrollHeight}
async function send(){const input=$('#novaConversationInput'),button=$('#novaConversationSend');const raw=text(input?.value);if(!raw)return;history.push({role:'user',text:raw});input.value='';render();button.disabled=true;button.textContent='Checking…';try{const reply=await answer(raw);history.push({role:'assistant',text:reply})}catch{history.push({role:'assistant',text:'Current evidence could not be loaded. I will not guess while the project context is unavailable.'})}finally{history=history.slice(-8);saveHistory();render();button.disabled=false;button.textContent='Ask Nova';input.focus()}}
function install(){const overview=document.querySelector('.page[data-page="overview"]');if(!overview||$('#novaConversation'))return;const card=document.createElement('article');card.className='card nova-conversation';card.id='novaConversation';card.innerHTML=`<div class="section-head"><div><div class="eyebrow">CONTEXTUAL ASSISTANT</div><h2>Ask Nova</h2></div><button class="secondary" id="novaConversationRefresh" type="button">Refresh context</button></div><p>Ask naturally about Morley, Nova, current work or operational health. Follow-up questions keep the previous topic.</p><div id="novaConversationLog" class="nova-conversation-log" aria-live="polite"></div><div class="nova-conversation-compose"><input id="novaConversationInput" type="text" autocomplete="off" placeholder="e.g. What needs my attention?" aria-label="Ask Nova"><button id="novaConversationSend" type="button">Ask Nova</button></div><div class="nova-conversation-hint">Read-only project context · no pricing, auth, Guardian repair, production-write or release authority</div>`;const hero=overview.querySelector('.hero');hero?.insertAdjacentElement('afterend',card);render();$('#novaConversationSend')?.addEventListener('click',send);$('#novaConversationInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();send()}});$('#novaConversationRefresh')?.addEventListener('click',async()=>{evidence=null;const b=$('#novaConversationRefresh');b.disabled=true;b.textContent='Refreshing…';try{await loadEvidence(true);b.textContent='Context refreshed'}catch{b.textContent='Refresh failed'}setTimeout(()=>{b.disabled=false;b.textContent='Refresh context'},1200)});}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',install);else install();
})();
