(()=>{'use strict';
const SB='https://ghdhairijqjqivqriigi.supabase.co',KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function evidence(){const r=await fetch('catalogue-semantic-gap-evidence-2026-09-07.json',{cache:'no-store'});if(!r.ok)throw new Error(`Evidence bundle HTTP ${r.status}`);return r.json()}
async function action(body){const token=window.NovaAuth?.getAccessToken?.()||'';if(!token)throw new Error('Nova Admin authentication is required.');const r=await fetch(`${SB}/functions/v1/nova-actions`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(body),cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`Nova action HTTP ${r.status}`);return data}
function proposalFor(c){if(Number(c.device_catalog_id)===1492&&c.field==='storage_options')return{action:'catalogue_finding',device_id:1492,field_name:'storage_options',observed_value:['128GB'],severity:'high',confidence:1,source_url:c.source,source_name:'Motorola Support',source_region:'global',source_tier:2,evidence_excerpt:'Motorola official specifications state 128GB internal storage using UFS 2.2. The user guide separately confirms optional microSD expansion up to 1TB; expansion is not an internal storage variant.',proposed_patch:{storage_options:['128GB']}};return null}
function card(c){const proposal=proposalFor(c),verified=c.result==='verified_current_value',gap=c.result==='confirmed_image_gap';const tag=verified?'VERIFIED':gap?'IMAGE GAP':c.result==='discrepancy'?'DISCREPANCY':'REVIEW';const actionHtml=proposal?`<button type="button" class="secondary" data-evidence-propose="${Number(c.device_catalog_id)}">Propose finding</button>`:gap?`<button type="button" class="secondary" data-evidence-queue="${Number(c.device_catalog_id)}">Queue image review</button>`:'';return `<div class="item"><div><b>${esc(c.device)}</b><small>${esc(c.evidence||c.reason||'')} ${c.source?`• ${esc(c.source)}`:''}</small></div><div style="display:flex;align-items:center;gap:8px"><span class="tag ${c.result==='discrepancy'?'high':''}">${tag}</span>${actionHtml}</div></div>`}
function unresolved(c){return `<div class="item"><div><b>${esc(c.device)}</b><small>${esc(c.reason||'More manufacturer evidence is required.')}</small></div><span class="tag">UNRESOLVED</span></div>`}
async function install(){const page=$('[data-page="catalogue"]');if(!page||$('#catalogueEvidenceReview'))return;const host=document.createElement('article');host.id='catalogueEvidenceReview';host.className='card';host.innerHTML='<div class="section-head"><div><div class="eyebrow">MANUFACTURER EVIDENCE</div><h2>Evidence review</h2></div><span id="catalogueEvidenceState" class="tag">LOADING</span></div><div id="catalogueEvidenceList" class="stack"><div class="empty">Loading reviewed evidence…</div></div><div class="callout">Evidence proposals always require human approval. Verified-current cases are shown specifically to prevent Nova from “fixing” correct data.</div>';page.appendChild(host);try{const data=await evidence(),verified=Array.isArray(data.verified_cases)?data.verified_cases:[],pending=Array.isArray(data.unresolved_cases)?data.unresolved_cases:[];$('#catalogueEvidenceList').innerHTML=[...verified.map(card),...pending.map(unresolved)].join('')||'<div class="empty">No evidence cases are recorded.</div>';$('#catalogueEvidenceState').textContent='VERIFIED';$('#catalogueEvidenceState').className='tag ok'}catch(error){$('#catalogueEvidenceState').textContent='DEGRADED';$('#catalogueEvidenceState').className='tag high';$('#catalogueEvidenceList').innerHTML=`<div class="empty">${esc(error.message||String(error))}</div>`}}
async function propose(btn){btn.disabled=true;btn.textContent='Proposing…';try{const data=await evidence(),c=(data.verified_cases||[]).find(x=>Number(x.device_catalog_id)===Number(btn.dataset.evidencePropose)),body=proposalFor(c||{});if(!body)throw new Error('No guarded evidence proposal is defined for this case.');const out=await action(body);btn.textContent=`Finding ${out.item?.id?'created':'queued'}`;btn.dataset.done='1'}catch(error){btn.textContent='Proposal failed';btn.title=error.message||String(error);setTimeout(()=>{btn.disabled=false;btn.textContent='Propose finding'},1800)}}
async function queue(btn){btn.disabled=true;btn.textContent='Queueing…';try{const out=await action({action:'catalogue_queue',device_id:Number(btn.dataset.evidenceQueue),priority:55,reason:'nova_official_image_review'});btn.textContent=`Queued #${out.item?.id||''}`;btn.dataset.done='1'}catch(error){btn.textContent='Queue failed';btn.title=error.message||String(error);setTimeout(()=>{btn.disabled=false;btn.textContent='Queue image review'},1800)}}
function start(){install();document.addEventListener('click',e=>{const p=e.target.closest?.('[data-evidence-propose]');if(p&&!p.dataset.done){propose(p);return}const q=e.target.closest?.('[data-evidence-queue]');if(q&&!q.dataset.done)queue(q)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('nova:authenticated',install);window.NovaEvidenceReview={evidence,proposalFor};
})();
