(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const REQUIRED=['Repository Security Audit','B&L Morley Quality Gate','Morley Ultimate Parity Gate','Web Release Smoke Checks'];
let refreshVersion=0;
let baseAttentionRows=[];
let attentionTimer=0;
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
function item(title,detail,tag='',tone='',href=''){const inner=`<div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}`;return href?`<a class="item" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${inner}</a>`:`<div class="item">${inner}</div>`}
function mergedItem(title,detail,tag,tone,section){return `<button type="button" class="item" data-nova-merged-attention="1" data-attention-section="${esc(section)}"><div><b>${esc(title)}</b><small>${esc(detail)}</small></div><span class="tag ${esc(tone)}">${esc(tag)}</span></button>`}
function isGuardianRepair(pr){return /^guardian(?:\s+repair)?\s*:/i.test(String(pr?.title||''))}
function runLabel(run){if(!run)return'UNKNOWN';if(run.status!=='completed')return'RUNNING';if(run.conclusion==='success')return'HEALTHY';if(run.conclusion==='skipped')return'SKIPPED';return String(run.conclusion||'FAILED').toUpperCase()}
function runTone(run){const s=runLabel(run);return s==='HEALTHY'?'ok':s==='RUNNING'?'':'high'}
function num(id){const raw=String($(id)?.textContent||'').replace(/[^0-9.-]/g,'');const n=Number(raw);return Number.isFinite(n)?n:0}
function label(id){return String($(id)?.textContent||'').trim().toUpperCase()}
function mergePresentation(){
  const nav=document.querySelector('[data-section="guardian"]');if(nav)nav.textContent='Security & Guardian';
  const page=document.querySelector('[data-page="guardian"]');if(page){const head=page.querySelector('h2');const intro=page.querySelector('p');const eyebrow=page.querySelector('.eyebrow');if(head)head.textContent='Security & Guardian';if(eyebrow)eyebrow.textContent='INDEPENDENT ENFORCEMENT';if(intro)intro.textContent='Guardian is Nova’s independent security and governance layer. Nova can inspect its evidence and explain decisions, but cannot bypass, weaken or inherit Guardian authority.';}
  const attention=document.querySelector('[data-page="attention"] article');if(attention){const eyebrow=attention.querySelector('.eyebrow');const intro=attention.querySelector('p');if(eyebrow)eyebrow.textContent='UNIFIED TRIAGE';if(intro)intro.textContent='Nova combines human and release gates, Guardian enforcement evidence, and privacy-safe support pressure here. Protected decisions remain human-gated.';}
  const boundary=[...document.querySelectorAll('.boundary-list')].find(Boolean);if(boundary){const card=boundary.closest('.card');const title=card?.querySelector('h2');const eyebrow=card?.querySelector('.eyebrow');if(title)title.textContent='Nova + Guardian security boundary';if(eyebrow)eyebrow.textContent='SECURITY & GOVERNANCE';}
  const footer=document.querySelector('footer');if(footer&&/Guardian protected/i.test(footer.textContent||''))footer.textContent='© 2026 Morley Buys · Nova AI · Guardian-enforced security boundary';
}
function captureBaseAttention(){const list=$('attentionList');if(!list)return;const fresh=[...list.children].filter(node=>!node.hasAttribute('data-nova-merged-attention')&&!node.classList.contains('empty'));baseAttentionRows=fresh.map(node=>node.outerHTML)}
function renderUnifiedAttention(){
  const list=$('attentionList');if(!list)return;
  captureBaseAttention();
  const signals=[];
  const supportChecked=label('supportChecked');const supportSla=num('supportSla');const supportHigh=num('supportHigh');
  if(supportChecked==='UNAVAILABLE')signals.push(mergedItem('Support evidence unavailable','Nova cannot verify current aggregate support health. No protected ticket read was attempted.','REVIEW','high','support'));
  else if(supportSla>0||supportHigh>0)signals.push(mergedItem('Support queue pressure',`${supportSla.toLocaleString()} SLA overdue • ${supportHigh.toLocaleString()} high/urgent active. Review the privacy-safe support aggregates before taking action.`,'ACTION','high','support'));
  const guardianState=label('guardianState');const guardianOpen=num('guardianOpen');
  if(['BLOCKED','DEGRADED','INCOMPLETE'].includes(guardianState)||guardianOpen>0){const detail=[guardianState&&guardianState!=='LOADING'?`Guardian ${guardianState.toLowerCase()}`:'Guardian evidence pending',guardianOpen?`${guardianOpen.toLocaleString()} open repair${guardianOpen===1?'':'s'}`:''].filter(Boolean).join(' • ');signals.push(mergedItem('Guardian enforcement needs review',`${detail}. Nova may diagnose and recommend, but protected Guardian decisions remain human-controlled.`,'GUARDED','high','guardian'))}
  const rows=[...baseAttentionRows,...signals];
  list.innerHTML=rows.length?rows.join(''):'<div class="empty">No current item requires human attention.</div>';
  const metric=$('metricAttention');if(metric)metric.textContent=String(rows.length);
}
function scheduleUnifiedAttention(){clearTimeout(attentionTimer);attentionTimer=setTimeout(renderUnifiedAttention,0)}
function bindUnifiedAttention(){['supportChecked','supportSla','supportHigh','guardianState','guardianOpen'].forEach(id=>{const el=$(id);if(el)new MutationObserver(scheduleUnifiedAttention).observe(el,{childList:true,subtree:true,characterData:true,attributes:true})});document.addEventListener('click',e=>{const merged=e.target.closest('[data-attention-section]');if(merged){e.preventDefault();document.querySelector(`[data-section="${merged.dataset.attentionSection}"]`)?.click()}});window.addEventListener('nova:authenticated',scheduleUnifiedAttention);scheduleUnifiedAttention()}
async function refreshGuardian(){mergePresentation();const list=$('guardianEvidence');if(!list)return;const requestVersion=++refreshVersion;try{const [pulls,runsPayload]=await Promise.all([api('/pulls?state=all&per_page=100'),api('/actions/runs?branch=main&per_page=100')]);if(requestVersion!==refreshVersion)return;const repairs=(pulls||[]).filter(isGuardianRepair).sort((a,b)=>new Date(b.updated_at||b.created_at)-new Date(a.updated_at||a.created_at));const open=repairs.filter(pr=>pr.state==='open');const latestMerged=repairs.find(pr=>pr.merged_at)||null;const guardianSha=latestMerged?.merge_commit_sha||null;const runs=(runsPayload.workflow_runs||[]).filter(r=>guardianSha&&r.head_sha===guardianSha);const latestByName=new Map();for(const run of runs){if(!latestByName.has(run.name))latestByName.set(run.name,run)}const evidence=REQUIRED.map(name=>({name,run:latestByName.get(name)||null}));const blocked=evidence.filter(x=>x.run?.status==='completed'&&x.run.conclusion!=='success');const running=evidence.filter(x=>!x.run||x.run.status!=='completed');const healthy=evidence.filter(x=>x.run?.status==='completed'&&x.run.conclusion==='success');
$('guardianLatest').textContent=latestMerged?`#${latestMerged.number}`:'—';$('guardianOpen').textContent=open.length.toLocaleString();$('guardianValidated').textContent=healthy.length.toLocaleString();$('guardianBlocked').textContent=blocked.length.toLocaleString();$('guardianState').textContent=blocked.length?'BLOCKED':running.length?'INCOMPLETE':latestMerged?'ENFORCED':'UNKNOWN';$('guardianState').className=`tag ${blocked.length?'high':running.length?'':'ok'}`;
const rows=[];if(latestMerged)rows.push(item(`#${latestMerged.number} ${latestMerged.title}`,`merged ${new Date(latestMerged.merged_at).toLocaleString()} • ${guardianSha?guardianSha.slice(0,7):'merge SHA unavailable'}`,'LATEST','ok',latestMerged.html_url));else rows.push('<div class="empty">No merged Guardian-titled repair PR was found.</div>');for(const x of evidence){rows.push(item(x.name,x.run?`run #${x.run.run_number} • ${new Date(x.run.updated_at||x.run.created_at).toLocaleString()}`:'No matching run found for the latest Guardian repair',runLabel(x.run),runTone(x.run),x.run?.html_url||''))}for(const pr of open.slice(0,4)){rows.push(item(`#${pr.number} ${pr.title}`,'Open security repair remains under Guardian and human control.','OPEN','high',pr.html_url))}list.innerHTML=rows.join('');$('guardianBoundary').textContent='Guardian is Nova’s enforcement layer: Nova may observe, diagnose and recommend, but cannot approve, merge, deploy, execute, disable or bypass protected Guardian decisions.';scheduleUnifiedAttention()}catch(error){if(requestVersion!==refreshVersion)return;console.error(error);$('guardianState').textContent='DEGRADED';$('guardianState').className='tag high';list.innerHTML='<div class="empty">Security enforcement evidence is temporarily unavailable. Nova did not attempt any protected action.</div>';$('guardianBoundary').textContent='Guardian authority remains independent, fail-closed and protected.';scheduleUnifiedAttention()}}
window.NovaGuardianSupportMerge={render:renderUnifiedAttention};
window.addEventListener('DOMContentLoaded',()=>{mergePresentation();bindUnifiedAttention();refreshGuardian()});document.addEventListener('click',e=>{if(e.target.closest('[data-section="guardian"]'))refreshGuardian();if(e.target?.id==='refreshBtn'){baseAttentionRows=[];refreshGuardian();scheduleUnifiedAttention()}});
})();
