(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const REQUIRED=['Repository Security Audit','B&L Morley Quality Gate','Morley Ultimate Parity Gate','Web Release Smoke Checks'];
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
function item(title,detail,tag='',tone='',href=''){const inner=`<div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}`;return href?`<a class="item" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${inner}</a>`:`<div class="item">${inner}</div>`}
function isGuardianRepair(pr){return /^guardian(?:\s+repair)?\s*:/i.test(String(pr?.title||''))}
function runLabel(run){if(!run)return'UNKNOWN';if(run.status!=='completed')return'RUNNING';if(run.conclusion==='success')return'HEALTHY';if(run.conclusion==='skipped')return'SKIPPED';return String(run.conclusion||'FAILED').toUpperCase()}
function runTone(run){const s=runLabel(run);return s==='HEALTHY'?'ok':s==='RUNNING'?'':'high'}
async function refreshGuardian(){const list=$('guardianEvidence');if(!list)return;try{const [pulls,runsPayload]=await Promise.all([api('/pulls?state=all&per_page=100'),api('/actions/runs?branch=main&per_page=100')]);const repairs=(pulls||[]).filter(isGuardianRepair).sort((a,b)=>new Date(b.updated_at||b.created_at)-new Date(a.updated_at||a.created_at));const open=repairs.filter(pr=>pr.state==='open');const latestMerged=repairs.find(pr=>pr.merged_at)||null;const guardianSha=latestMerged?.merge_commit_sha||null;const runs=(runsPayload.workflow_runs||[]).filter(r=>guardianSha&&r.head_sha===guardianSha);const latestByName=new Map();for(const run of runs){if(!latestByName.has(run.name))latestByName.set(run.name,run)}const evidence=REQUIRED.map(name=>({name,run:latestByName.get(name)||null}));const blocked=evidence.filter(x=>x.run?.status==='completed'&&x.run.conclusion!=='success');const running=evidence.filter(x=>!x.run||x.run.status!=='completed');const healthy=evidence.filter(x=>x.run?.status==='completed'&&x.run.conclusion==='success');
$('guardianLatest').textContent=latestMerged?`#${latestMerged.number}`:'—';$('guardianOpen').textContent=open.length.toLocaleString();$('guardianValidated').textContent=healthy.length.toLocaleString();$('guardianBlocked').textContent=blocked.length.toLocaleString();$('guardianState').textContent=blocked.length?'BLOCKED':running.length?'INCOMPLETE':latestMerged?'VALIDATED':'UNKNOWN';$('guardianState').className=`tag ${blocked.length?'high':running.length?'':'ok'}`;
const rows=[];if(latestMerged)rows.push(item(`#${latestMerged.number} ${latestMerged.title}`,`merged ${new Date(latestMerged.merged_at).toLocaleString()} • ${guardianSha?guardianSha.slice(0,7):'merge SHA unavailable'}`,'LATEST','ok',latestMerged.html_url));else rows.push('<div class="empty">No merged Guardian-titled repair PR was found.</div>');for(const x of evidence){rows.push(item(x.name,x.run?`run #${x.run.run_number} • ${new Date(x.run.updated_at||x.run.created_at).toLocaleString()}`:'No matching run found for the latest Guardian repair',runLabel(x.run),runTone(x.run),x.run?.html_url||''))}for(const pr of open.slice(0,4)){rows.push(item(`#${pr.number} ${pr.title}`,'Open Guardian repair remains human-controlled.','OPEN','high',pr.html_url))}list.innerHTML=rows.join('');$('guardianBoundary').textContent='Nova can observe Guardian repair and validation evidence, but cannot approve, merge, deploy, or execute protected Guardian repairs.';}catch(error){console.error(error);$('guardianState').textContent='DEGRADED';$('guardianState').className='tag high';list.innerHTML='<div class="empty">Guardian evidence is temporarily unavailable. Nova did not attempt any protected action.</div>';$('guardianBoundary').textContent='Guardian authority remains independent and protected.'}}
window.addEventListener('DOMContentLoaded',refreshGuardian);document.addEventListener('click',e=>{if(e.target.closest('[data-section="guardian"]'))refreshGuardian();if(e.target?.id==='refreshBtn')refreshGuardian()});
})();
