(()=>{'use strict';
const SUPABASE_URL='https://ghdhairijqjqivqriigi.supabase.co',SUPABASE_KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function invoke(name,body){const token=window.NovaAuth?.getAccessToken?.();if(!token)throw new Error('Nova authentication is required.');const r=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`${name} returned HTTP ${r.status}`);return d}
async function load(){const [knowledge,learning]=await Promise.all([invoke('nova-knowledge',{action:'summary'}),invoke('nova-learning',{action:'summary'})]);return{checked_at:new Date().toISOString(),knowledge,learning}}
function item(title,detail,tag=''){return `<div class="item"><div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ok">${esc(tag)}</span>`:''}</div>`}
async function refresh(){if(!$('#memoryKnowledge'))return;try{const d=await load();$('#memoryKnowledge').textContent=Number(d.knowledge.active_count||0).toLocaleString();$('#memoryLearning').textContent=Number(d.learning.count||0).toLocaleString();$('#memoryVerified').textContent=Number(d.learning.verified_count||0).toLocaleString();const recent=d.learning.recent||[],avg=recent.length?recent.reduce((n,x)=>n+Number(x.confidence||0),0)/recent.length:0;$('#memoryConfidence').textContent=recent.length?`${Math.round(avg*100)}%`:'—';const domains=Object.entries(d.learning.by_domain||{}).sort((a,b)=>Number(b[1])-Number(a[1]));const list=$('#memoryDomainList');if(list)list.innerHTML=domains.length?domains.map(([domain,total])=>item(domain.replaceAll('_',' '),`${Number(total).toLocaleString()} active learned outcome${Number(total)===1?'':'s'}`,'LIVE')).join(''):'<div class="empty">No active learning domains were returned.</div>';const checked=$('#memoryChecked');if(checked){checked.textContent='LIVE';checked.className='tag ok'}const boundary=$('#memoryBoundary');if(boundary)boundary.textContent=`Live memory: ${Number(d.knowledge.active_count||0)} active knowledge references and ${Number(d.learning.count||0)} active learned outcomes. Nova reads these for context only; this view does not harvest, create, update, archive or delete memory.`}catch(error){console.error(error);const checked=$('#memoryChecked');if(checked){checked.textContent='DEGRADED';checked.className='tag high'}}}
window.NovaMemoryLive={load,refresh};if(document.readyState==='loading')addEventListener('DOMContentLoaded',refresh,{once:true});else refresh();addEventListener('nova:authenticated',refresh);document.addEventListener('click',e=>{if(e.target.closest('[data-section="knowledge"]')||e.target?.id==='refreshBtn')refresh()});
})();
