(()=>{'use strict';
const originalFetch=window.fetch.bind(window);
const PAGE_SIZE=1000;
const ACTIVE=new Set(['open','in_progress','waiting_on_user']);
const categoryLabels={valuation:'Valuation',pricing:'Pricing',inventory:'Inventory',scanner:'Scanner',account:'Account',update:'Update',other:'Other'};
let moduleLoaderPromise=null;
function isSupportSnapshot(input){try{const raw=input instanceof Request?input.url:String(input);const url=new URL(raw,location.href);return url.origin===location.origin&&url.pathname.endsWith('/nova/support-health.json')}catch(_e){return false}}
async function rows(){if(!window.NovaAuth?.rest)throw new Error('Nova authenticated REST access is unavailable.');const all=[];for(let offset=0;;offset+=PAGE_SIZE){const page=await window.NovaAuth.rest(`/rest/v1/support_tickets?select=status,priority,category,sla_due_at,first_response_at,updated_at&order=updated_at.desc&limit=${PAGE_SIZE}&offset=${offset}`);if(!Array.isArray(page))throw new Error('Support health response was invalid.');all.push(...page);if(page.length<PAGE_SIZE)break;}return all}
function aggregate(items){const now=Date.now(),status=new Map(),categories=new Map();let active=0,high=0,overdue=0,awaiting=0;for(const ticket of items){const s=String(ticket?.status||'unknown');const c=String(ticket?.category||'other');status.set(s,(status.get(s)||0)+1);categories.set(c,(categories.get(c)||0)+1);if(ACTIVE.has(s)){active++;if(['high','urgent'].includes(String(ticket?.priority||'')))high++;if(ticket?.sla_due_at&&new Date(ticket.sla_due_at).getTime()<now)overdue++;if(!ticket?.first_response_at)awaiting++;}}
return{checked_date:new Date().toISOString(),total_tickets:items.length,active_tickets:active,high_priority_active:high,sla_overdue:overdue,awaiting_first_response:awaiting,status_counts:[...status.entries()].map(([status,total])=>({status,total})).sort((a,b)=>b.total-a.total||a.status.localeCompare(b.status)),category_counts:[...categories.entries()].map(([category,total])=>({category,label:categoryLabels[category]||category.replaceAll('_',' '),total})).sort((a,b)=>b.total-a.total||a.category.localeCompare(b.category)),boundary_note:'Live aggregate only: subjects, descriptions, messages, identities, assignees and diagnostics were not requested.'}}
async function load(){return aggregate(await rows())}
window.NovaSupportLive={load};
window.fetch=async(...args)=>{if(!isSupportSnapshot(args[0])||!window.NovaAuth?.rest)return originalFetch(...args);try{return new Response(JSON.stringify(await load()),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}catch(error){console.error('Nova live support health failed; using snapshot fallback.',error);return originalFetch(...args)}};
function rejectModuleLoader(script,reject,message){moduleLoaderPromise=null;script.remove();reject(new Error(message))}
function ensureModuleLoader(){if(window.NovaModuleLoader)return Promise.resolve(window.NovaModuleLoader);if(moduleLoaderPromise)return moduleLoaderPromise;moduleLoaderPromise=new Promise((resolve,reject)=>{const existing=document.getElementById('nova-shared-module-loader');if(existing){existing.addEventListener('load',()=>window.NovaModuleLoader?resolve(window.NovaModuleLoader):rejectModuleLoader(existing,reject,'Nova shared module loader did not initialise.'),{once:true});existing.addEventListener('error',()=>rejectModuleLoader(existing,reject,'Nova shared module loader failed to load.'),{once:true});return}const script=document.createElement('script');script.id='nova-shared-module-loader';script.src='module-loader.js?v=1';script.async=false;script.onload=()=>window.NovaModuleLoader?resolve(window.NovaModuleLoader):rejectModuleLoader(script,reject,'Nova shared module loader did not initialise.');script.onerror=()=>rejectModuleLoader(script,reject,'Nova shared module loader failed to load.');document.head.appendChild(script)});return moduleLoaderPromise}
async function loadIntelligence(){const loader=await ensureModuleLoader();const ordered=(src,id)=>loader.load(src,{id,ordered:true});ordered('mode-boundary-sync.js?v=1','nova-mode-boundary-sync-script');ordered('live-intelligence.js?v=1','nova-live-intelligence-script');ordered('pricing-intelligence.js?v=1','nova-pricing-intelligence-script');ordered('guardian-live-analysis.js?v=2','nova-guardian-live-analysis-script');ordered('support-triage.js?v=1','nova-support-triage-script');ordered('live-memory.js?v=1','nova-live-memory-script');ordered('learning-controls.js?v=1','nova-learning-controls-script');ordered('pr-readiness.js?v=1','nova-pr-readiness-script');ordered('catalogue-deep-audit.js?v=2','nova-catalogue-deep-audit-script');ordered('evidence-review.js?v=1','nova-evidence-review-script');ordered('business-intelligence.js?v=1','nova-business-intelligence-script');ordered('scenario-planner.js?v=1','nova-scenario-planner-script');ordered('proactive-alerts.js?v=1','nova-proactive-alerts-script');ordered('camera-valuation-safety.js?v=1','nova-camera-valuation-safety-script');ordered('camera-image-preprocessor.js?v=1','nova-camera-image-preprocessor-script');ordered('camera-assistant.js?v=2','nova-camera-assistant-script');ordered('camera-photo-provenance.js?v=1','nova-camera-photo-provenance-script');ordered('camera-functionality-checklist.js?v=1','nova-camera-functionality-checklist-script');ordered('bug-triage.js?v=1','nova-bug-triage-script');ordered('control-centre.js?v=1','nova-control-centre-script');ordered('explain-mode.js?v=1','nova-explain-mode-script');ordered('knowledge-engine.js?v=1','nova-knowledge-engine-script');ordered('knowledge-integration.js?v=1','nova-knowledge-integration-script');ordered('command-registry.js?v=1','nova-command-registry-script');ordered('domain-command-packs.js?v=1','nova-domain-command-packs-script');ordered('command-discovery.js?v=1','nova-command-discovery-script');ordered('conversation-custom-knowledge.js?v=1','nova-conversation-script');ordered('conversation-consistency.js?v=1','nova-conversation-consistency-script');ordered('voice-assistant.js?v=1','nova-voice-assistant-script');ordered('observability.js?v=1','nova-observability-script');}
window.addEventListener('nova:authenticated',()=>{loadIntelligence().catch(error=>console.error('Nova intelligence module bootstrap failed.',error))});if(window.NovaAuth?.getAccessToken?.())loadIntelligence().catch(error=>console.error('Nova intelligence module bootstrap failed.',error));
})();