(()=>{'use strict';
const originalFetch=window.fetch.bind(window);
const PAGE_SIZE=1000;
const ACTIVE=new Set(['open','in_progress','waiting_on_user']);
const categoryLabels={valuation:'Valuation',pricing:'Pricing',inventory:'Inventory',scanner:'Scanner',account:'Account',update:'Update',other:'Other'};
let moduleLoaderPromise=null;
function isSupportSnapshot(input){try{const raw=input instanceof Request?input.url:String(input);const url=new URL(raw,location.href);return url.origin===location.origin&&url.pathname.endsWith('/nova/support-health.json')}catch(_e){return false}}
async function rows(){if(!window.NovaAuth?.rest)throw new Error('Nova authenticated REST access is unavailable.');const all=[];for(let offset=0;;offset+=PAGE_SIZE){const page=await window.NovaAuth.rest(`/rest/v1/support_tickets?select=status,priority,category,sla_due_at,first_response_at,updated_at&order=updated_at.desc&limit=${PAGE_SIZE}&offset=${offset}`);if(!Array.isArray(page))throw new Error('Support health response was invalid.');all.push(...page);if(page.length<PAGE_SIZE)break;}return all}
function aggregate(items){const now=Date.now(),status=new Map(),categories=new Map();let active=0,high=0,overdue=0,awaiting=0;for(const ticket of items){const s=String(ticket?.status||'unknown');const c=String(ticket?.category||'other');status.set(s,(status.get(s)||0)+1);categories.set(c,(categories.get(c)||0)+1);if(ACTIVE.has(s)){active++;if(['high','urgent'].includes(String(ticket?.priority||'')))high++;if(ticket?.sla_due_at&&new Date(ticket.sla_due_at).getTime()<now)overdue++;if(!ticket?.first_response_at)awaiting++;}}
return{checked_date:new Date().toISOString(),total_tickets:items.length,active_tickets:active,high_priority_active:high,sla_overdue:overdue,awaiting_first_response:awaiting,status_counts:[...status.entries()].map(([status,total])=>({status,total})).sort((a,b)=>b.total-a.total||a.status.localeCompare(b.status)),category_counts:[...categories.entries()].map(([category,total])=>({category,label:categoryLabels[category]||category.replaceAll('_',' '),total})).sort((a,b)=>b.total-a.total||a.category.localeCompare(b.category)),boundary_note:'Live aggregate only: subjects, descriptions, messages, identities, assignees and diagnostics were not requested.'}}
async function load(){return aggregate(await rows())}
window.NovaSupportLive={load};
window.fetch=async(...args)=>{if(!isSupportSnapshot(args[0])||!window.NovaAuth?.rest)return originalFetch(...args);try{return new Response(JSON.stringify(await load()),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}catch(error){console.error('Nova live support health failed; using snapshot fallback.',error);return originalFetch(...args)}};
function ensureModuleLoader(){if(window.NovaModuleLoader)return Promise.resolve(window.NovaModuleLoader);if(moduleLoaderPromise)return moduleLoaderPromise;moduleLoaderPromise=new Promise((resolve,reject)=>{const existing=document.getElementById('nova-shared-module-loader');if(existing){existing.addEventListener('load',()=>window.NovaModuleLoader?resolve(window.NovaModuleLoader):reject(new Error('Nova shared module loader did not initialise.')),{once:true});existing.addEventListener('error',()=>reject(new Error('Nova shared module loader failed to load.')),{once:true});return}const script=document.createElement('script');script.id='nova-shared-module-loader';script.src='module-loader.js?v=1';script.async=false;script.onload=()=>window.NovaModuleLoader?resolve(window.NovaModuleLoader):reject(new Error('Nova shared module loader did not initialise.'));script.onerror=()=>reject(new Error('Nova shared module loader failed to load.'));document.head.appendChild(script)});return moduleLoaderPromise}
async function loadIntelligence(){const loader=await ensureModuleLoader();loader.load('mode-boundary-sync.js?v=1',{id:'nova-mode-boundary-sync-script'});loader.load('live-intelligence.js?v=1',{id:'nova-live-intelligence-script'});loader.load('pricing-intelligence.js?v=1',{id:'nova-pricing-intelligence-script'});loader.load('guardian-live-analysis.js?v=2',{id:'nova-guardian-live-analysis-script'});loader.load('support-triage.js?v=1',{id:'nova-support-triage-script'});loader.load('live-memory.js?v=1',{id:'nova-live-memory-script'});loader.load('learning-controls.js?v=1',{id:'nova-learning-controls-script'});loader.load('pr-readiness.js?v=1',{id:'nova-pr-readiness-script'});loader.load('catalogue-deep-audit.js?v=2',{id:'nova-catalogue-deep-audit-script'});loader.load('evidence-review.js?v=1',{id:'nova-evidence-review-script'});loader.load('business-intelligence.js?v=1',{id:'nova-business-intelligence-script'});loader.load('scenario-planner.js?v=1',{id:'nova-scenario-planner-script'});loader.load('proactive-alerts.js?v=1',{id:'nova-proactive-alerts-script'});loader.load('camera-assistant.js?v=1',{id:'nova-camera-assistant-script'});loader.load('bug-triage.js?v=1',{id:'nova-bug-triage-script'});loader.load('control-centre.js?v=1',{id:'nova-control-centre-script'});loader.load('explain-mode.js?v=1',{id:'nova-explain-mode-script'});loader.load('conversation.js?v=2',{id:'nova-conversation-script'});loader.load('conversation-consistency.js?v=1',{id:'nova-conversation-consistency-script'});loader.load('voice-assistant.js?v=1',{id:'nova-voice-assistant-script'});}
window.addEventListener('nova:authenticated',()=>{loadIntelligence().catch(error=>console.error('Nova intelligence module bootstrap failed.',error))});if(window.NovaAuth?.getAccessToken?.())loadIntelligence().catch(error=>console.error('Nova intelligence module bootstrap failed.',error));
})();