(()=>{'use strict';
const SUPABASE_URL='https://ghdhairijqjqivqriigi.supabase.co',SUPABASE_KEY='sb_publishable_ch49o8WRnDb8pPzowZH3Tg_XZcIbgvt';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function invoke(name,body){const token=window.NovaAuth?.getAccessToken?.();if(!token)throw new Error('Nova authentication is required.');const r=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`${name} returned HTTP ${r.status}`);return d}
async function load(){const [knowledge,learning]=await Promise.all([invoke('nova-knowledge',{action:'summary'}),invoke('nova-learning',{action:'summary'})]);return{checked_at:new Date().toISOString(),knowledge,learning}}
function item(title,detail,tag='',tone=''){return `<div class="item"><div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}</div>`}
function analyseLearning(learning){const recent=Array.isArray(learning?.recent)?learning.recent:[],verified=recent.filter(x=>x.verified===true),unverified=recent.filter(x=>x.verified!==true),low=recent.filter(x=>Number(x.confidence||0)<.7),human=recent.filter(x=>String(x.source_type||'')==='admin_feedback'),authoritative=recent.filter(x=>['sales_records','inventory_items','guardian_incident','guardian_repair'].includes(String(x.source_type||''))),avg=recent.length?recent.reduce((n,x)=>n+Number(x.confidence||0),0)/recent.length:0;return{recent,verified,unverified,low,human,authoritative,avg}}
async function refresh(){if(!$('#memoryKnowledge'))return;try{const d=await load(),a=analyseLearning(d.learning);$('#memoryKnowledge').textContent=Number(d.knowledge.active_count||0).toLocaleString();$('#memoryLearning').textContent=Number(d.learning.count||0).toLocaleString();$('#memoryVerified').textContent=Number(d.learning.verified_count||0).toLocaleString();$('#memoryConfidence').textContent=a.recent.length?`${Math.round(a.avg*100)}%`:'—';const domains=Object.entries(d.learning.by_domain||{}).sort((x,y)=>Number(y[1])-Number(x[1]));const list=$('#memoryDomainList');if(list){const rows=domains.map(([domain,total])=>item(domain.replaceAll('_',' '),`${Number(total).toLocaleString()} active learned outcome${Number(total)===1?'':'s'}`,'LIVE','ok'));rows.push(item('Recent verification boundary',`${a.verified.length} verified • ${a.unverified.length} unverified • ${a.low.length} below 70% confidence`,'GUARDED',a.low.length?'high':'ok'));rows.push(item('Human feedback',`${a.human.length} recent explicit Admin feedback item${a.human.length===1?'':'s'}; feedback is treated as non-authoritative until corroborated by source data.`,'ADVISORY'));rows.push(item('Authoritative outcomes',`${a.authoritative.length} recent outcomes came directly from sales, inventory or Guardian source records.`,'SOURCE','ok'));list.innerHTML=rows.join('')||'<div class="empty">No active learning domains were returned.</div>'}const checked=$('#memoryChecked');if(checked){checked.textContent='LIVE';checked.className='tag ok'}const boundary=$('#memoryBoundary');if(boundary)boundary.textContent=`Live memory: ${Number(d.knowledge.active_count||0)} active knowledge references and ${Number(d.learning.count||0)} active learned outcomes. Recent sample: ${a.verified.length} verified, ${a.unverified.length} unverified, ${a.low.length} low-confidence. Nova may use accepted/rejected feedback as context, but unverified feedback never silently becomes protected pricing, Guardian, security or release authority.`}catch(error){console.error(error);const checked=$('#memoryChecked');if(checked){checked.textContent='DEGRADED';checked.className='tag high'}}}
window.NovaMemoryLive={load,analyseLearning,refresh};if(document.readyState==='loading')addEventListener('DOMContentLoaded',refresh,{once:true});else refresh();addEventListener('nova:authenticated',refresh);document.addEventListener('click',e=>{if(e.target.closest('[data-section="knowledge"]')||e.target?.id==='refreshBtn')refresh()});
})();
