(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
function item(title,detail,tag,tone=''){return `<div class="item"><div><b>${esc(title)}</b><small>${esc(detail)}</small></div><span class="tag ${tone}">${esc(tag)}</span></div>`}
function ensureView(){const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-section="permissions"]')){const button=document.createElement('button');button.dataset.section='permissions';button.textContent='Permissions';const activity=nav.querySelector('[data-section="activity"]');nav.insertBefore(button,activity||null)}
const main=document.querySelector('main');if(main&&!document.querySelector('[data-page="permissions"]')){const section=document.createElement('section');section.className='page';section.dataset.page='permissions';section.innerHTML=`<div class="card"><div class="section-head"><div><div class="eyebrow">AUTHORITY MAP</div><h2>Settings & Permissions</h2></div><span id="permissionsState" class="tag">LOADING</span></div><p>Read-only view of Nova's current operating boundary. This page reports authority; it does not grant, elevate, approve or change permissions.</p></div><div class="grid-two"><article class="card"><div class="eyebrow">ALLOWED</div><h2>Read & advise</h2><div id="permissionsAllowed" class="stack"></div></article><article class="card"><div class="eyebrow">HUMAN GATED</div><h2>Protected actions</h2><div id="permissionsProtected" class="stack"></div></article></div><article class="card"><div class="section-head"><div><div class="eyebrow">POLICY EVIDENCE</div><h2>Current-main governance sources</h2></div><span id="permissionsPolicy" class="tag">CHECKING</span></div><div id="permissionsEvidence" class="stack"><div class="empty">Checking governance evidence…</div></div><div class="callout">Nova and Beau currently share one GitHub identity. Repository reviews, labels, comments or other same-identity metadata cannot prove independent human approval. The repository guard can block protected PR checks, but this UI does not claim that a failed guard is technically impossible to merge unless repository enforcement independently requires it.</div></article>`;const activity=document.querySelector('[data-page="activity"]');main.insertBefore(section,activity||null)}
$('permissionsAllowed').innerHTML=[item('Public GitHub evidence','Branches, pull requests, commits and workflow health may be read for analysis.','READ','ok'),item('Trusted project context','Current-main project documents may inform recommendations.','READ','ok'),item('Aggregate intelligence','Catalogue, support and memory health snapshots may be displayed without protected row-level data.','READ','ok'),item('Recommendations','Nova may prioritise and explain next actions while preserving source-of-truth evidence.','ADVISE','ok')].join('');
$('permissionsProtected').innerHTML=[item('Production writes','Standalone Nova UI has no production write authority.','DISABLED','high'),item('Auth, roles & RLS','Authentication, authorization, roles, permissions and RLS remain human-controlled.','HUMAN','high'),item('Pricing approvals','Protected pricing and approval state remain outside Nova authority.','HUMAN','high'),item('Guardian repairs','Nova may observe evidence but cannot approve, merge, deploy or execute protected Guardian repairs.','HUMAN','high'),item('Releases & signing','Deploy, release, OTA and signing authority remain protected.','HUMAN','high'),item('Workflow governance','Any .github/workflows change is high risk and requires explicit conversational authorization for the specific ready PR/head.','HUMAN','high')].join('')}
async function refreshPolicy(){ensureView();const evidence=$('permissionsEvidence');if(!evidence)return;try{const [policy,guard]=await Promise.all([api('/contents/NOVA_AUTONOMOUS_DEVELOPMENT.md?ref=main'),api('/contents/.github/workflows/nova-pr-guard.yml?ref=main')]);const rows=[];rows.push(item('Nova autonomous-development policy',`${String(policy.sha||'').slice(0,7)} • current main source`,'LOADED','ok'));rows.push(item('Nova PR Guard',`${String(guard.sha||'').slice(0,7)} • read-only workflow evidence`,'LOADED','ok'));evidence.innerHTML=rows.join('');$('permissionsState').textContent='READ ONLY';$('permissionsState').className='tag ok';$('permissionsPolicy').textContent='CURRENT MAIN';$('permissionsPolicy').className='tag ok'}catch(error){console.error(error);evidence.innerHTML='<div class="empty">Governance evidence is temporarily unavailable. Nova did not attempt to change any permission.</div>';$('permissionsState').textContent='DEGRADED';$('permissionsState').className='tag high';$('permissionsPolicy').textContent='UNAVAILABLE';$('permissionsPolicy').className='tag high'}}
window.addEventListener('DOMContentLoaded',refreshPolicy);document.addEventListener('click',e=>{if(e.target.closest('[data-section="permissions"]'))refreshPolicy();if(e.target?.id==='refreshBtn')refreshPolicy()});if(document.readyState!=='loading')refreshPolicy();
})();