(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let refreshVersion=0;
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
function item(title,detail,tag,tone=''){return `<div class="item"><div><b>${esc(title)}</b><small>${esc(detail)}</small></div><span class="tag ${tone}">${esc(tag)}</span></div>`}
function correctOverviewCopy(){const metric=[...document.querySelectorAll('.metric')].find(x=>x.querySelector('span')?.textContent.trim()==='Mode');if(metric){const strong=metric.querySelector('strong'),small=metric.querySelector('small');if(strong)strong.textContent='GUARDED';if(small)small.textContent='audited Admin-only execution'}const summary=$('coreSummary');if(summary&&/without changing production systems/i.test(summary.textContent||''))summary.textContent='Reading live Morley evidence with narrow, audited Admin-only catalogue review actions. Guardian independently enforces protected production authority.';for(const row of document.querySelectorAll('.boundary-list>div')){const b=row.querySelector('b'),s=row.querySelector('span');if(b?.textContent.trim()==='Production writes'&&s)s.textContent='Guardian-gated audit queue / evidence proposals only';if(b?.textContent.trim()==='Auth & permissions'&&s)s.textContent='Admin-only; Guardian-enforced changes remain protected'}}
function ensureView(){correctOverviewCopy();const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-section="permissions"]')){const button=document.createElement('button');button.dataset.section='permissions';button.textContent='Permissions';const activity=nav.querySelector('[data-section="activity"]');nav.insertBefore(button,activity||null)}
const main=document.querySelector('main');if(main&&!document.querySelector('[data-page="permissions"]')){const section=document.createElement('section');section.className='page';section.dataset.page='permissions';section.innerHTML=`<div class="card"><div class="section-head"><div><div class="eyebrow">AUTHORITY MAP</div><h2>Settings & Permissions</h2></div><span id="permissionsState" class="tag">LOADING</span></div><p>Live view of Nova's guarded operating boundary. Guardian is the independent enforcement layer; this page reports authority and cannot elevate, approve or broaden it.</p></div><div class="grid-two"><article class="card"><div class="eyebrow">ALLOWED</div><h2>Read, advise & queue</h2><div id="permissionsAllowed" class="stack"></div></article><article class="card"><div class="eyebrow">GUARDIAN ENFORCED</div><h2>Protected actions</h2><div id="permissionsProtected" class="stack"></div></article></div><article class="card"><div class="section-head"><div><div class="eyebrow">POLICY EVIDENCE</div><h2>Current-main governance sources</h2></div><span id="permissionsPolicy" class="tag">CHECKING</span></div><div id="permissionsEvidence" class="stack"><div class="empty">Checking governance evidence…</div></div><div class="callout">Nova is the unified Admin-only operator. Guardian independently enforces protected authority. Pricing approval, Guardian decisions/repairs, releases/deployments/OTA, user/role changes, destructive deletes and automatic catalogue patch application remain outside Nova authority.</div></article>`;const activity=document.querySelector('[data-page="activity"]');main.insertBefore(section,activity||null)}
$('permissionsAllowed').innerHTML=[item('Admin-only access','Only an enabled Admin profile may enter Nova or use Nova-specific privileged services.','ADMIN','ok'),item('Live evidence','GitHub, catalogue, support, market, Guardian and trusted project evidence may be read for analysis.','READ','ok'),item('Catalogue audit queue','Nova may create an audited review queue item for an active catalogue record.','QUEUE','ok'),item('Evidence-backed findings','Nova may propose a catalogue finding with HTTPS source evidence; the finding remains approval-required.','PROPOSE','ok'),item('Vision intelligence','Admin-only server-side vision may inspect submitted device photos without automatically changing catalogue data.','ANALYSE','ok'),item('Recommendations & learning','Nova may advise, explain and harvest verified outcomes when explicitly requested.','ADVISE','ok')].join('');
$('permissionsProtected').innerHTML=[item('Catalogue patch application','Nova may queue/propose, but Guardian prevents silent catalogue changes.','GUARDIAN','high'),item('Pricing approvals & writes','Protected pricing and approval state remain outside Nova authority.','GUARDIAN','high'),item('Guardian decisions & repairs','Nova may observe and explain evidence but cannot self-approve, disable, bypass or execute Guardian work.','GUARDIAN','high'),item('Releases, deploys & signing','Release, deployment, OTA and signing authority remain protected.','GUARDIAN','high'),item('Users, roles & security policy','User/role changes and authorization/RLS changes require explicit protected implementation and review.','GUARDIAN','high'),item('Destructive operations','Permanent deletes and destructive production operations are prohibited through Nova actions.','BLOCKED','high'),item('Workflow governance','Any .github/workflows change is high risk and requires explicit conversational authorization for the specific ready PR/head.','HUMAN','high')].join('')}
async function refreshPolicy(){ensureView();const evidence=$('permissionsEvidence');if(!evidence)return;const requestVersion=++refreshVersion;try{const [policy,guard]=await Promise.all([api('/contents/NOVA_AUTONOMOUS_DEVELOPMENT.md?ref=main'),api('/contents/.github/workflows/nova-pr-guard.yml?ref=main')]);if(requestVersion!==refreshVersion)return;const rows=[];rows.push(item('Nova autonomous-development policy',`${String(policy.sha||'').slice(0,7)} • current main source`,'LOADED','ok'));rows.push(item('Nova PR Guard',`${String(guard.sha||'').slice(0,7)} • independent repository guard evidence`,'LOADED','ok'));evidence.innerHTML=rows.join('');$('permissionsState').textContent='GUARDIAN ENFORCED';$('permissionsState').className='tag ok';$('permissionsPolicy').textContent='CURRENT MAIN';$('permissionsPolicy').className='tag ok'}catch(error){if(requestVersion!==refreshVersion)return;console.error(error);evidence.innerHTML='<div class="empty">Governance evidence is temporarily unavailable. Nova did not broaden any permission.</div>';$('permissionsState').textContent='DEGRADED';$('permissionsState').className='tag high';$('permissionsPolicy').textContent='UNAVAILABLE';$('permissionsPolicy').className='tag high'}}
function loadModule(src){if(document.querySelector(`script[data-nova-feature="${src}"]`))return;const script=document.createElement('script');script.src=src+'?v=1';script.async=true;script.dataset.novaFeature=src;document.head.appendChild(script)}
function activateLiveSuite(){['live-memory.js','live-intelligence.js','pr-readiness.js','proactive-alerts.js'].forEach(loadModule)}
window.addEventListener('DOMContentLoaded',()=>{refreshPolicy();activateLiveSuite()});document.addEventListener('click',e=>{if(e.target.closest('[data-section="permissions"]'))refreshPolicy();if(e.target?.id==='refreshBtn')refreshPolicy()});if(document.readyState!=='loading'){refreshPolicy();activateLiveSuite()}
})();