(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const REPO='beaustwrt248-netizen/Buys-Mock',API=`https://api.github.com/repos/${REPO}`;
async function github(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
async function guardian(){if(!window.NovaAuth?.rest)return[];const rows=await window.NovaAuth.rest('/rest/v1/guardian_incidents?select=id,state,risk_level,requires_approval,occurrence_count,diagnosis_summary,last_seen_at&order=last_seen_at.desc&limit=100');return Array.isArray(rows)?rows:[]}
function latest(runs){const map=new Map();for(const r of runs||[])if(!map.has(r.name))map.set(r.name,r);return[...map.values()]}
async function load(){const [runPayload,catalogue,support,incidents]=await Promise.all([github('/actions/runs?branch=main&per_page=100').catch(()=>({workflow_runs:[]})),window.NovaCatalogueLive?.load?.().catch(()=>null),window.NovaSupportLive?.load?.().catch(()=>null),guardian().catch(()=>[])]);const alerts=[];for(const r of latest(runPayload.workflow_runs||[]))if(r.status==='completed'&&r.conclusion&&!['success','skipped'].includes(r.conclusion))alerts.push({severity:5,type:'release',title:`${r.name} failed`,detail:`Latest main run #${r.run_number} concluded ${r.conclusion}.`,url:r.html_url||''});if(support){if(Number(support.sla_overdue||0)>0)alerts.push({severity:5,type:'support',title:`${support.sla_overdue} support SLA overdue`,detail:`Active tickets are past their SLA due time.`});if(Number(support.high_priority_active||0)>0)alerts.push({severity:4,type:'support',title:`${support.high_priority_active} high/urgent support tickets`,detail:`Current active queue needs priority review.`})}if(catalogue){if(Number(catalogue.missing_model_number||0)>0)alerts.push({severity:3,type:'catalogue',title:`${catalogue.missing_model_number} catalogue model-number gaps`,detail:`Live catalogue scan found active records without model numbers.`});if(Number(catalogue.missing_release_year||0)>0)alerts.push({severity:3,type:'catalogue',title:`${catalogue.missing_release_year} release-year gaps`,detail:'Exact hardware release years remain incomplete.'});if(Number(catalogue.missing_image||0)>0)alerts.push({severity:2,type:'catalogue',title:`${catalogue.missing_image} catalogue image gaps`,detail:'Active records are missing reference images.'})}const open=incidents.filter(x=>String(x.state||'').toLowerCase()!=='resolved');const approval=open.filter(x=>x.requires_approval===true),repeat=open.filter(x=>Number(x.occurrence_count||0)>1);if(approval.length)alerts.push({severity:5,type:'guardian',title:`${approval.length} Guardian incidents need approval`,detail:'Nova will not approve or execute these protected actions.'});if(repeat.length)alerts.push({severity:4,type:'guardian',title:`${repeat.length} repeated Guardian incidents`,detail:'Repeated fingerprints/patterns should be correlated before another repair attempt.'});return alerts.sort((a,b)=>b.severity-a.severity||a.title.localeCompare(b.title))}
function item(a){return `<div class="item"><div><b>${esc(a.title)}</b><small>${esc(a.detail)}</small></div><span class="tag ${a.severity>=4?'high':''}">${esc(a.type.toUpperCase())}</span></div>`}
async function refresh(){const list=$('#attentionList');if(!list)return;try{const alerts=await load();list.innerHTML=alerts.length?alerts.map(item).join(''):'<div class="empty">No current read-only alert threshold is triggered.</div>';const metric=$('#metricAttention');if(metric)metric.textContent=alerts.filter(x=>x.severity>=4).length.toLocaleString();window.dispatchEvent(new CustomEvent('nova:alerts-refreshed',{detail:{alerts}}))}catch(error){console.error(error);list.innerHTML=`<div class="empty">Alert evidence unavailable: ${esc(error.message||String(error))}</div>`}}
window.NovaProactiveAlerts={load,refresh};if(document.readyState==='loading')addEventListener('DOMContentLoaded',refresh,{once:true});else refresh();addEventListener('nova:authenticated',refresh);document.addEventListener('click',e=>{if(e.target.closest('[data-section="attention"]')||e.target?.id==='refreshBtn')refresh()});
})();
