(()=>{'use strict';
const REPO='beaustwrt248-netizen/Buys-Mock';
const API='https://api.github.com/repos/'+REPO;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let refreshVersion=0;
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
async function local(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`Local ${r.status}`);return r.json()}
function item(title,detail,tag='',tone='',href=''){const inner=`<div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}`;return href?`<a class="item" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${inner}</a>`:`<div class="item">${inner}</div>`}
function latestRuns(runs){const seen=new Set();return (runs||[]).filter(run=>{const key=String(run.name||run.workflow_id||run.id);if(seen.has(key))return false;seen.add(key);return true})}
function declaredHigh(pr){const ref=String(pr?.head?.ref||''),text=`${pr?.title||''}\n${pr?.body||''}`;if(!ref.startsWith('nova/'))return false;return /\bhigh[- ]risk\b/i.test(text)||/\brisk\s*[:=-]\s*(?:\*\*)?high\b/i.test(text)||/(?:^|\n)#{1,6}\s*risk\s*\n+\s*(?:\*\*)?high\b/im.test(text)}
function explicitHumanGate(pr){const text=`${pr?.title||''}\n${pr?.body||''}`;return /\bhuman[- ]merge[- ]only\b/i.test(text)||/\bfinal merge\b[^.\n]{0,120}\bhuman[- ]controlled\b/i.test(text)||/\brequires?\s+(?:explicit\s+)?human\s+(?:approval|authori[sz]ation)\b/i.test(text)}
function requiresHumanDecision(pr){return declaredHigh(pr)||explicitHumanGate(pr)}
window.__NovaRecommendationPolicy={declaredHigh,explicitHumanGate,requiresHumanDecision};
function rec(title,detail,priority,kind,href=''){return{title,detail,priority,kind,href}}
async function refreshRecommendations(){const list=$('recommendationList');if(!list)return;const requestVersion=++refreshVersion;try{const [runsPayload,prs,catalogue,support,memory]=await Promise.all([api('/actions/runs?branch=main&per_page=50'),api('/pulls?state=open&per_page=50'),window.NovaCatalogueLive.load().catch(()=>null),local('support-health.json').catch(()=>null),local('memory-health.json').catch(()=>null)]);if(requestVersion!==refreshVersion)return;const current=latestRuns(runsPayload.workflow_runs||[]);const failed=current.filter(r=>r.status==='completed'&&r.conclusion&&r.conclusion!=='success'&&r.conclusion!=='skipped');const skipped=current.filter(r=>r.status==='completed'&&r.conclusion==='skipped');const highRisk=(prs||[]).filter(declaredHigh);const humanGates=(prs||[]).filter(requiresHumanDecision);const recommendations=[];
failed.forEach(r=>recommendations.push(rec(`Fix current failure: ${r.name}`,`Latest main run #${r.run_number} concluded ${r.conclusion}. Investigate this before lower-priority improvement work.`,1,'BLOCKER',r.html_url||'')));
skipped.forEach(r=>recommendations.push(rec(`Re-establish workflow evidence: ${r.name}`,`Latest main run #${r.run_number} was skipped. Treat this evidence as incomplete and verify a successful current run before discretionary improvement work.`,1,'EVIDENCE',r.html_url||'')));
humanGates.forEach(pr=>recommendations.push(rec(`Human decision: #${pr.number} ${pr.title}`,'This pull request explicitly declares a protected human approval or merge boundary. Keep it stopped until Beau reviews the exact current head and authorises that specific step.',2,'HUMAN',pr.html_url||'')));
if(support){const sla=Number(support.sla_overdue||0),high=Number(support.high_priority_active||0),first=Number(support.awaiting_first_response||0);if(sla||high||first)recommendations.push(rec('Stabilise support queue',`${sla} SLA overdue • ${high} active high/urgent • ${first} awaiting first response. Resolve operational pressure before discretionary enhancements.`,3,'SUPPORT'));}
if(catalogue){const gaps=Number(catalogue.missing_model_number||0);if(gaps){const top=[...(catalogue.categories||[])].filter(x=>Number(x.missing_model_number||0)>0).sort((a,b)=>Number(b.missing_model_number||0)-Number(a.missing_model_number||0))[0];recommendations.push(rec('Close catalogue model-number gaps',`${gaps} catalogue records are missing model numbers${top?`; ${top.label||top.category} has the largest current gap at ${Number(top.missing_model_number).toLocaleString()}`:''}. Verify against authoritative Australian sources before any data change.`,4,'DATA'));}}
if(memory){const domains=memory.domains||[];if(domains.length<2)recommendations.push(rec('Broaden Nova learning coverage',`Active learned experience currently covers ${domains.length?domains.map(d=>d.domain).join(', '):'no domains'}. Add verified, non-authoritative learning from catalogue, support, UI/runtime and release outcomes without allowing memory to override live evidence.`,5,'LEARNING'));}
if(!recommendations.length)recommendations.push(rec('No urgent intervention detected','Current workflow, human-gate, support, catalogue and learning signals contain no higher-priority actionable item. Continue with the next validated low-risk improvement.',6,'CLEAR'));
recommendations.sort((a,b)=>a.priority-b.priority);const urgent=recommendations.filter(r=>r.kind==='BLOCKER'||r.kind==='HUMAN').length;const evidenceIncomplete=recommendations.some(r=>r.kind==='EVIDENCE');const dataGaps=Number(catalogue?.missing_model_number||0);$('recommendUrgent').textContent=urgent.toLocaleString();$('recommendHighRisk').textContent=highRisk.length.toLocaleString();$('recommendDataGaps').textContent=dataGaps.toLocaleString();$('recommendDomains').textContent=Number(memory?.domains?.length||0).toLocaleString();$('recommendState').textContent=urgent?'ATTENTION':evidenceIncomplete?'INCOMPLETE':recommendations[0]?.priority<=4?'IMPROVE':'HEALTHY';$('recommendState').className=`tag ${urgent?'high':evidenceIncomplete?'':'ok'}`;list.innerHTML=recommendations.slice(0,8).map((r,i)=>item(`${i+1}. ${r.title}`,r.detail,r.kind,r.priority<=2&&r.kind!=='EVIDENCE'?'high':r.kind==='CLEAR'?'ok':'',r.href)).join('');$('recommendNext').textContent=`Next action: ${recommendations[0].title}. Nova recommendations are advisory only and cannot bypass approval, Guardian, auth/RLS, pricing or release controls.`;}catch(error){if(requestVersion!==refreshVersion)return;console.error(error);$('recommendState').textContent='DEGRADED';$('recommendState').className='tag high';list.innerHTML='<div class="empty">Recommendation evidence is temporarily unavailable. Nova will not infer a next action from incomplete evidence.</div>';$('recommendNext').textContent='No action is recommended while evidence is degraded.'}}
window.addEventListener('DOMContentLoaded',refreshRecommendations);document.addEventListener('click',e=>{if(e.target.closest('[data-section="recommendations"]'))refreshRecommendations();if(e.target?.id==='refreshBtn')refreshRecommendations()});
})();
(()=>{'use strict';const script=document.createElement('script');script.src='development-history.js?v=1';script.defer=true;document.head.appendChild(script)})();
(()=>{'use strict';const css=document.createElement('link');css.rel='stylesheet';css.href='conversation.css?v=1';document.head.appendChild(css);const script=document.createElement('script');script.src='conversation.js?v=1';script.defer=true;document.head.appendChild(script)})();
(()=>{'use strict';let loaded=false;function load(){if(loaded||window.NovaCommands)return;loaded=true;const script=document.createElement('script');script.src='command-registry.js?v=1';script.defer=true;script.dataset.novaCommands='1';script.addEventListener('load',()=>{if(document.querySelector('script[data-nova-command-packs]'))return;const packs=document.createElement('script');packs.src='domain-command-packs.js?v=1';packs.defer=true;packs.dataset.novaCommandPacks='1';document.head.appendChild(packs)},{once:true});document.head.appendChild(script)}if(window.NovaAuth)load();else window.addEventListener('nova:authenticated',load,{once:true})})();
