(()=>{'use strict';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const ACTIVE=new Set(['open','in_progress','waiting_on_user']);
const normal=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\b(the|a|an|my|app|morley|please|help)\b/g,' ').replace(/\s+/g,' ').trim();
async function tickets(){if(!window.NovaAuth?.rest)throw new Error('Nova authentication is required for support triage.');const path='/rest/v1/support_tickets?select=id,category,subject,description,status,priority,app_version,device_model,android_version,created_at,updated_at,sla_due_at,first_response_at&order=updated_at.desc&limit=300';const rows=await window.NovaAuth.rest(path);return Array.isArray(rows)?rows:[]}
function draft(t){const cat=String(t.category||'other');const intro='Thanks for reporting this. I’ve reviewed the details you provided.';const next={pricing:'We’re checking the pricing evidence and the exact device/model involved before recommending a correction.',valuation:'We’re checking the valuation inputs and comparable evidence so we can identify where the result diverged.',inventory:'We’re checking the inventory workflow and the affected record so we can isolate the issue safely.',scanner:'We’re checking the scanner flow and device compatibility to narrow down the failure.',account:'We’re checking your account/session path and will avoid making any access changes until the cause is confirmed.',update:'We’re checking the installed version and current release state to determine whether this is already fixed or needs a patch.',other:'We’re checking the reported workflow and relevant app state to identify the safest fix.'}[cat]||'We’re checking the reported workflow and relevant app state to identify the safest fix.';return `${intro} ${next} We’ll keep the ticket updated with the confirmed cause and next step.`}
function item(title,detail,tag='',tone=''){return `<div class="item"><div><b>${esc(title)}</b><small>${esc(detail)}</small></div>${tag?`<span class="tag ${tone}">${esc(tag)}</span>`:''}</div>`}
function install(){const page=$('[data-page="support"]');if(!page||$('#supportTriage'))return;const card=document.createElement('article');card.className='card';card.id='supportTriage';card.innerHTML=`<div class="section-head"><div><div class="eyebrow">READ-ONLY TRIAGE</div><h2>Nova support agent</h2></div><span id="supportTriageState" class="tag">LOADING</span></div><p>Nova groups likely duplicate reports, surfaces SLA/priority risk, and prepares draft replies. Nothing is sent and no ticket state changes from this view.</p><div id="supportTriageList" class="stack"><div class="empty">Loading active ticket triage…</div></div><div class="callout" id="supportTriageSummary">Drafts are advisory until a staff member chooses to use them.</div>`;page.appendChild(card);refresh()}
async function refresh(){const list=$('#supportTriageList');if(!list)return;try{const all=await tickets(),active=all.filter(t=>ACTIVE.has(String(t.status||''))),now=Date.now();const groups=new Map();for(const t of active){const key=normal(t.subject)||`${t.category||'other'}:${normal(t.description).slice(0,60)}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(t)}const dup=[...groups.values()].filter(g=>g.length>1).sort((a,b)=>b.length-a.length);const ranked=[...active].sort((a,b)=>{const score=x=>(String(x.priority)==='urgent'?100:String(x.priority)==='high'?60:0)+(x.sla_due_at&&new Date(x.sla_due_at).getTime()<now?80:0)+(!x.first_response_at?20:0);return score(b)-score(a)||new Date(b.updated_at||0)-new Date(a.updated_at||0)}).slice(0,15);const rows=[];for(const g of dup.slice(0,5))rows.push(item(`Likely duplicate cluster: ${g[0].subject||g[0].category||'Support issue'}`,`${g.length} active tickets • category ${g[0].category||'other'} • newest ${new Date(g[0].updated_at).toLocaleString()}`,'DUPLICATE','high'));for(const t of ranked){const overdue=t.sla_due_at&&new Date(t.sla_due_at).getTime()<now;const risk=overdue?'SLA OVERDUE':['urgent','high'].includes(String(t.priority||''))?String(t.priority).toUpperCase():!t.first_response_at?'NEEDS REPLY':'ACTIVE';rows.push(item(t.subject||`${t.category||'Other'} support ticket`,`${t.category||'other'} • ${t.status||'unknown'} • ${t.app_version?`app ${t.app_version} • `:''}${t.device_model||''}${t.device_model&&t.android_version?' • ':''}${t.android_version?`Android ${t.android_version}`:''}\nDraft: ${draft(t)}`,risk,overdue||['urgent','high'].includes(String(t.priority||''))?'high':''))}list.innerHTML=rows.join('')||'<div class="empty">No active support tickets need triage.</div>';const overdue=active.filter(t=>t.sla_due_at&&new Date(t.sla_due_at).getTime()<now).length,unanswered=active.filter(t=>!t.first_response_at).length;$('#supportTriageSummary').textContent=`${active.length} active tickets • ${dup.length} likely duplicate cluster${dup.length===1?'':'s'} • ${overdue} SLA overdue • ${unanswered} awaiting first response. No messages were sent.`;$('#supportTriageState').textContent='LIVE';$('#supportTriageState').className='tag ok'}catch(error){console.error(error);$('#supportTriageState').textContent='DEGRADED';$('#supportTriageState').className='tag high';list.innerHTML=`<div class="empty">${esc(error.message||String(error))}</div>`}}
window.NovaSupportTriage={tickets,refresh};if(document.readyState==='loading')addEventListener('DOMContentLoaded',install,{once:true});else install();addEventListener('nova:authenticated',()=>{install();refresh()});document.addEventListener('click',e=>{if(e.target.closest('[data-section="support"]')||e.target?.id==='refreshBtn')refresh()});
})();
