-- Guardian live activity timeline for Admin Control and user-safe Buys app updates.
-- The activity stream is presentation/telemetry only; it grants no repair, merge,
-- deployment, auth, RLS, secrets or destructive database privileges.

create table if not exists public.guardian_activity (
  id bigint generated by default as identity primary key,
  incident_id uuid not null references public.guardian_incidents(id) on delete cascade,
  ticket_id uuid references public.support_tickets(id) on delete cascade,
  phase text not null default 'received' check (phase in ('received','inspecting','diagnosing','reproducing','researching','preparing_fix','testing','awaiting_approval','applying','verifying','resolved','failed','paused')),
  status text not null default 'working' check (status in ('working','success','warning','error','waiting','stopped')),
  summary text not null check (char_length(summary) between 1 and 500),
  detail text check (detail is null or char_length(detail) <= 3000),
  visibility text not null default 'admin' check (visibility in ('admin','user')),
  progress smallint check (progress is null or progress between 0 and 100),
  actor text not null default 'guardian' check (actor in ('guardian','worker','system','admin')),
  created_at timestamptz not null default now()
);

create index if not exists guardian_activity_incident_created_idx on public.guardian_activity(incident_id, created_at asc);
create index if not exists guardian_activity_ticket_created_idx on public.guardian_activity(ticket_id, created_at desc) where ticket_id is not null;

alter table public.guardian_activity enable row level security;
revoke all on table public.guardian_activity from anon, authenticated;
grant select on table public.guardian_activity to authenticated;

drop policy if exists guardian_activity_read on public.guardian_activity;
create policy guardian_activity_read on public.guardian_activity
for select to authenticated
using (
  private.is_admin_or_manager()
  or (
    visibility = 'user'
    and ticket_id is not null
    and exists (
      select 1 from public.support_tickets t
      where t.id = guardian_activity.ticket_id
        and t.user_id = (select auth.uid())
    )
  )
);

create or replace function private.guardian_activity_fill_ticket()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if new.ticket_id is null then
    select i.ticket_id into new.ticket_id
    from public.guardian_incidents i
    where i.id = new.incident_id;
  end if;
  return new;
end;
$$;
revoke all on function private.guardian_activity_fill_ticket() from public;

drop trigger if exists trg_guardian_activity_fill_ticket on public.guardian_activity;
create trigger trg_guardian_activity_fill_ticket
before insert on public.guardian_activity
for each row execute function private.guardian_activity_fill_ticket();

create or replace function private.guardian_activity_incident_created()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.guardian_activity(incident_id,ticket_id,phase,status,summary,detail,visibility,progress,actor)
  values(
    new.id,new.ticket_id,'received','working','Guardian received the incident.',
    case when new.classification is not null then 'Classification: ' || left(new.classification,120) else null end,
    case when new.ticket_id is null then 'admin' else 'user' end,5,'system'
  );
  insert into public.guardian_activity(incident_id,ticket_id,phase,status,summary,visibility,progress,actor)
  values(new.id,new.ticket_id,'inspecting','working','Collecting diagnostics and identifying the affected area.',case when new.ticket_id is null then 'admin' else 'user' end,10,'guardian');
  return new;
end;
$$;
revoke all on function private.guardian_activity_incident_created() from public;

drop trigger if exists trg_guardian_activity_incident_created on public.guardian_incidents;
create trigger trg_guardian_activity_incident_created
after insert on public.guardian_incidents
for each row execute function private.guardian_activity_incident_created();

create or replace function private.guardian_activity_state_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_phase text;
  v_status text := 'working';
  v_summary text;
  v_progress smallint;
  v_visibility text := case when new.ticket_id is null then 'admin' else 'user' end;
begin
  if new.state is not distinct from old.state then return new; end if;
  v_phase := case new.state
    when 'queued' then 'inspecting'
    when 'diagnosing' then 'diagnosing'
    when 'proposed' then 'preparing_fix'
    when 'awaiting_approval' then 'awaiting_approval'
    when 'applying' then 'applying'
    when 'verifying' then 'verifying'
    when 'resolved' then 'resolved'
    when 'failed' then 'failed'
    when 'ignored' then 'paused'
    else 'inspecting' end;
  v_status := case new.state when 'resolved' then 'success' when 'failed' then 'error' when 'awaiting_approval' then 'waiting' when 'ignored' then 'stopped' else 'working' end;
  v_progress := case new.state when 'queued' then 10 when 'diagnosing' then 30 when 'proposed' then 55 when 'awaiting_approval' then 65 when 'applying' then 75 when 'verifying' then 90 when 'resolved' then 100 when 'failed' then 100 else 20 end;
  v_summary := case new.state
    when 'queued' then 'Guardian queued the incident for assessment.'
    when 'diagnosing' then 'Guardian is diagnosing the likely cause.'
    when 'proposed' then 'Guardian prepared a candidate repair.'
    when 'awaiting_approval' then 'Guardian is waiting for human approval before a protected action.'
    when 'applying' then 'An approved repair is being applied through the guarded pipeline.'
    when 'verifying' then 'Guardian is verifying the repair and checking for regressions.'
    when 'resolved' then 'Guardian verified the incident as resolved.'
    when 'failed' then 'Guardian could not safely complete this repair. The incident requires review.'
    when 'ignored' then 'Guardian stopped work on this incident.'
    else 'Guardian updated the incident.' end;
  insert into public.guardian_activity(incident_id,ticket_id,phase,status,summary,visibility,progress,actor)
  values(new.id,new.ticket_id,v_phase,v_status,v_summary,v_visibility,v_progress,'guardian');
  return new;
end;
$$;
revoke all on function private.guardian_activity_state_change() from public;

drop trigger if exists trg_guardian_activity_state_change on public.guardian_incidents;
create trigger trg_guardian_activity_state_change
after update of state on public.guardian_incidents
for each row execute function private.guardian_activity_state_change();

-- Server-side Guardian workers can insert richer timeline entries using their
-- privileged database connection. Browser roles remain SELECT-only.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'guardian_activity'
     ) then
    execute 'alter publication supabase_realtime add table public.guardian_activity';
  end if;
end $$;
