-- Per-user Google Drive backups. The existing global disaster-recovery backup remains separate.

create table if not exists public.user_drive_backups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  google_permission_id text not null,
  drive_file_id text not null,
  drive_file_name text not null,
  format_version integer not null default 1 check (format_version > 0),
  encryption_algorithm text not null default 'AES-256-GCM' check (encryption_algorithm = 'AES-256-GCM'),
  ciphertext_sha256 text not null,
  byte_size bigint not null default 0 check (byte_size >= 0),
  status text not null default 'ready' check (status in ('creating','ready','restoring','failed')),
  created_at timestamptz not null default now(),
  restored_at timestamptz
);

create index if not exists user_drive_backups_user_created_idx
  on public.user_drive_backups (user_id, created_at desc);

create unique index if not exists user_drive_backups_drive_file_idx
  on public.user_drive_backups (drive_file_id);

alter table public.user_drive_backups enable row level security;

revoke all on public.user_drive_backups from anon;
revoke insert, update, delete on public.user_drive_backups from authenticated;
grant select on public.user_drive_backups to authenticated;

drop policy if exists "Users can read only their own Drive backups" on public.user_drive_backups;
create policy "Users can read only their own Drive backups"
  on public.user_drive_backups
  for select
  to authenticated
  using (user_id = (select auth.uid()));

-- Wrapped data-encryption keys are deliberately kept in a server-only table.
-- Authenticated clients receive no privileges and no RLS policy for this table.
create table if not exists public.user_drive_backup_keys (
  backup_id uuid primary key references public.user_drive_backups(id) on delete cascade,
  wrapped_key text not null,
  wrap_iv text not null,
  created_at timestamptz not null default now()
);

alter table public.user_drive_backup_keys enable row level security;
revoke all on public.user_drive_backup_keys from anon, authenticated;

create table if not exists public.user_drive_backup_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  backup_id uuid references public.user_drive_backups(id) on delete set null,
  event_type text not null check (event_type in (
    'backup_created','backup_failed','backup_verified','backup_deleted',
    'restore_started','restore_completed','restore_failed'
  )),
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_drive_backup_events_user_created_idx
  on public.user_drive_backup_events (user_id, created_at desc);
create index if not exists user_drive_backup_events_backup_id_idx
  on public.user_drive_backup_events (backup_id);

alter table public.user_drive_backup_events enable row level security;
revoke all on public.user_drive_backup_events from anon;
grant select on public.user_drive_backup_events to authenticated;

drop policy if exists "Users can read only their own Drive backup events" on public.user_drive_backup_events;
create policy "Users can read only their own Drive backup events"
  on public.user_drive_backup_events
  for select
  to authenticated
  using (user_id = (select auth.uid()));

comment on table public.user_drive_backups is
  'Metadata for encrypted user-owned backups stored in that user Google Drive appDataFolder.';
comment on table public.user_drive_backup_keys is
  'Server-only AES data-key envelopes for user Drive backups. Never expose to authenticated clients.';
