create table if not exists public.nova_ai_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid null references auth.users(id) on delete set null,
  request_mode text not null,
  provider_mode text not null default 'auto',
  result_mode text not null,
  models_used text[] not null default '{}',
  candidate_models text[] not null default '{}',
  latency_ms integer not null default 0,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  cost_usd numeric(12,6) not null default 0,
  success boolean not null default false,
  degraded boolean not null default false,
  failure_code text null,
  failure_count integer not null default 0
);

alter table public.nova_ai_runs enable row level security;
revoke all on table public.nova_ai_runs from anon, authenticated;
revoke all on sequence public.nova_ai_runs_id_seq from anon, authenticated;

create index if not exists nova_ai_runs_created_at_idx on public.nova_ai_runs(created_at desc);
create index if not exists nova_ai_runs_user_created_idx on public.nova_ai_runs(user_id, created_at desc);
create index if not exists nova_ai_runs_success_created_idx on public.nova_ai_runs(success, created_at desc);
