create table if not exists public.user_sync_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  revision bigint not null default 0 check (revision >= 0),
  state jsonb not null default '{"bm_inv":[],"bm_sales":[],"bm_recent":[]}'::jsonb,
  updated_by_installation text,
  updated_at timestamptz not null default now()
);

alter table public.user_sync_state enable row level security;
revoke all on public.user_sync_state from anon;
revoke insert, update, delete on public.user_sync_state from authenticated;
grant select on public.user_sync_state to authenticated;

drop policy if exists "Users read their own sync state" on public.user_sync_state;
create policy "Users read their own sync state"
on public.user_sync_state for select to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.user_sync_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('pull','push','conflict','merge','offline_replay','sync_failure')),
  revision bigint,
  installation_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_sync_events_user_created_idx
  on public.user_sync_events(user_id, created_at desc);

alter table public.user_sync_events enable row level security;
revoke all on public.user_sync_events from anon;
revoke insert, update, delete on public.user_sync_events from authenticated;
grant select on public.user_sync_events to authenticated;

drop policy if exists "Users read their own sync events" on public.user_sync_events;
create policy "Users read their own sync events"
on public.user_sync_events for select to authenticated
using (user_id = (select auth.uid()));

comment on table public.user_sync_state is 'Per-user cross-device state for OTA web/Android legacy workspace data. Auth/session data is prohibited by service whitelist.';
