create table if not exists public.user_session_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid not null,
  installation_id text not null,
  platform text not null default 'web',
  device_name text,
  app_version text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  trusted_at timestamptz,
  unique (user_id, session_id)
);

create index if not exists user_session_devices_user_last_seen_idx
  on public.user_session_devices(user_id, last_seen_at desc);

alter table public.user_session_devices enable row level security;
revoke all on public.user_session_devices from anon;
revoke insert, update, delete on public.user_session_devices from authenticated;
grant select on public.user_session_devices to authenticated;

drop policy if exists "Users read their own session devices" on public.user_session_devices;
create policy "Users read their own session devices"
on public.user_session_devices for select to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.user_security_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid,
  event_type text not null check (event_type in (
    'new_session','session_seen','trusted_device','signout_others','local_signout',
    'backup_warning','backup_failure','restore_attempt','restore_success','security_notice'
  )),
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_security_events_user_created_idx
  on public.user_security_events(user_id, created_at desc);

alter table public.user_security_events enable row level security;
revoke all on public.user_security_events from anon;
revoke insert, update, delete on public.user_security_events from authenticated;
grant select on public.user_security_events to authenticated;

drop policy if exists "Users read their own security events" on public.user_security_events;
create policy "Users read their own security events"
on public.user_security_events for select to authenticated
using (user_id = (select auth.uid()));

comment on table public.user_session_devices is 'Per-user session/device registry. Tokens are never stored.';
comment on table public.user_security_events is 'Per-user security activity feed. No credentials or tokens are stored.';
