import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const U=Deno.env.get('SUPABASE_URL')||'',K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',GH=Deno.env.get('NOVA_GITHUB_TOKEN')||'';
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});
const OWNER='beaustwrt248-netizen',REPO='Buys-Mock',API=`https://api.github.com/repos/${OWNER}/${REPO}`;
const ORIGINS=new Set(['https://buyshub.me','https://www.buyshub.me','https://beaustwrt248-netizen.github.io']);
const clean=(v:unknown,n=2000)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,n);
function headers(r:Request){const o=r.headers.get('Origin')||'';return{'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://buyshub.me','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'}}
async function auth(r:Request){if(!U||!K)return{error:'Nova GitHub backend unavailable',status:503}as const;const t=(r.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!t)return{error:'Authentication required',status:401}as const;const{data:{user},error}=await db.auth.getUser(t);if(error||!user)return{error:'Invalid session',status:401}as const;const{data:p,error:e}=await db.from('profiles').select('role,is_enabled').eq('id',user.id).maybeSingle();if(e)throw e;if(!p?.is_enabled||p.role!=='admin')return{error:'Admin access required',status:403}as const;return{user}as const}
async function audit(uid:string,action:string,details:any){const{error}=await db.from('admin_audit_log').insert({actor_user_id:uid,action,target_type:'repository',target_id:`${OWNER}/${REPO}`,details:{source:'nova-github',...details}});if(error)throw error}
async function gh(path:string,init:RequestInit={}){if(!GH)throw new Error('Nova GitHub draft broker is not configured with NOVA_GITHUB_TOKEN.');const r=await fetch(`${API}${path}`,{...init,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${GH}`,'Content-Type':'application/json',...(init.headers||{})}});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok)throw new Error(clean(data?.message||`GitHub HTTP ${r.status}`,500));return data}
function slug(v:unknown){return clean(v,80).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,42)||'patch'}
function allowedPath(path:string){const p=path.replace(/^\/+/,''),lower=p.toLowerCase();if(!p||p.includes('..')||p.startsWith('.github/')||p.startsWith('supabase/'))return false;if(/androidmanifest\.xml$|build\.gradle$|gradle\.properties$|settings\.gradle$|proguard|keystore|signing/.test(lower))return false;if(/(^|\/)(auth|security|guardian|pricing|release|ota)([\/_.-]|$)/.test(lower))return false;if(/nova-actions|nova-github|secure-pricing|guardian_decide|guardian_report|service-role|secret/.test(lower))return false;return /\.(js|css|html|json|md|java|kt|xml|txt)$/.test(lower)}
async function prepareDraft(uid:string,b:any){const title=clean(b.title,180),summary=clean(b.summary,3000),files=Array.isArray(b.files)?b.files:[];if(!title||!summary)return{error:'title and summary required',status:400};if(!files.length||files.length>8)return{error:'1 to 8 text file changes required',status:400};for(const f of files){const path=clean(f?.path,300);if(!allowedPath(path))return{error:`Protected or unsupported path: ${path}`,status:403};if(typeof f?.content!=='string'||f.content.length>100000)return{error:`Invalid or oversized content for ${path}`,status:400}}
const main=await gh('/git/ref/heads/main');const baseSha=main?.object?.sha;if(!baseSha)throw new Error('Could not resolve current main SHA');const branch=`nova/auto-${Date.now()}-${slug(title)}`;await gh('/git/refs',{method:'POST',body:JSON.stringify({ref:`refs/heads/${branch}`,sha:baseSha})});
for(const f of files){const path=clean(f.path,300),encodedPath=path.split('/').map(encodeURIComponent).join('/');let existing:any=null;try{existing=await gh(`/contents/${encodedPath}?ref=${encodeURIComponent(branch)}`)}catch(e){if(!String(e).includes('Not Found'))throw e}const body:any={message:`Nova draft patch: ${title}`,content:btoa(unescape(encodeURIComponent(String(f.content)))),branch};if(existing?.sha)body.sha=existing.sha;await gh(`/contents/${encodedPath}`,{method:'PUT',body:JSON.stringify(body)})}
const pr=await gh('/pulls',{method:'POST',body:JSON.stringify({title:`[Nova draft] ${title}`,head:branch,base:'main',body:`## Nova draft PR\n\n${summary}\n\n### Safety\n- Draft only; Nova cannot merge this PR.\n- Protected paths are rejected by the broker.\n- Review exact diff and CI before any merge.\n- Release/deployment remains human-gated.`,draft:true,maintainer_can_modify:true})});await audit(uid,'nova.github.draft_pr',{branch,pr_number:pr.number,pr_url:pr.html_url,base_sha:baseSha,paths:files.map((x:any)=>clean(x.path,300)),draft:true,merge:false,deploy:false});return{ok:true,branch,base_sha:baseSha,pr:{number:pr.number,url:pr.html_url,draft:true}}}
Deno.serve(async(req:Request)=>{const h=headers(req),reply=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:h});if(req.method==='OPTIONS')return new Response('ok',{headers:h});if(req.method!=='POST')return reply({error:'POST required'},405);try{const a=await auth(req);if('error'in a)return reply({error:a.error},a.status);let b:any={};try{b=await req.json()}catch{return reply({error:'Invalid JSON'},400)}const action=clean(b.action,50).toLowerCase();if(action==='status')return reply({ok:true,configured:!!GH,repository:`${OWNER}/${REPO}`,capabilities:['draft_pr_low_risk_files'],protected:['merge','release','deploy','workflow','auth/security','guardian decisions','pricing authority','android manifest/signing']});if(action==='prepare_draft_pr'){const out:any=await prepareDraft(a.user.id,b);if(out?.error)return reply({error:out.error},out.status||400);return reply(out,201)}if(['merge','release','deploy','ota','workflow','delete_branch','force_push'].some(x=>action===x||action.startsWith(x+'.')))return reply({error:'This GitHub action is prohibited for Nova'},403);return reply({error:'Unsupported action'},400)}catch(e){const m=e instanceof Error?e.message:clean(e,500);console.error(`[nova-github] ${m}`);return new Response(JSON.stringify({error:m}),{status:500,headers:headers(req)})}});
